using Content.Shared._CMU14.ZLevels;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class CmuTab : Control
{
    [Dependency] private IConfigurationManager _cfg = default!;

    private const float OldZLevelBlurStrength = 2.0f;

    public event Action<bool, string>? CrtUiPreviewChanged;

    public CmuTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var crtUiEnabled = Control.AddOption(new OptionCrtUiEnabled(Control, _cfg, CrtUiEnabledCheckBox));
        CrtUiColorSlider.Slider.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;
        var crtUiColor = Control.AddOption(new OptionCrtUiColor(Control, _cfg, CrtUiColorSlider));
        crtUiEnabled.PreviewValueChanged += UpdateCrtUiOptionsPreview;
        crtUiColor.PreviewValueChanged += UpdateCrtUiOptionsPreview;

        Control.AddOptionCheckBox(CCVars.ChatEnableRunechatBubbles, RunechatSpeechBubblesCheckBox);
        Control.AddOptionPercentSlider(CCVars.ChatRunechatBubbleScale, RunechatSpeechBubbleScaleSlider, 0.5f, 2f);
        Control.AddOptionCheckBox(CCVars.ChatGhostFollowButton, ChatGhostFollowButton);
        Control.AddOptionPercentSlider(CMUZLevelsCVars.BlurStrength, ZLevelBlurSlider, scale: OldZLevelBlurStrength);

        Control.Initialize();
        UpdateCrtUiOptionsVisibility();
    }

    private void UpdateCrtUiOptionsVisibility()
    {
        CrtUiColorSlider.Visible = CrtUiEnabledCheckBox.Pressed;
    }

    private void UpdateCrtUiOptionsPreview()
    {
        UpdateCrtUiOptionsVisibility();
        CrtUiPreviewChanged?.Invoke(CrtUiEnabledCheckBox.Pressed, CrtUiColorSlider.Slider.Color.ToHex());
    }

    private sealed class OptionCrtUiEnabled : BaseOptionCVar<bool>
    {
        private readonly CheckBox _checkBox;
        private bool _suppressToggle;

        public event Action? PreviewValueChanged;

        protected override bool Value
        {
            get => _checkBox.Pressed;
            set
            {
                _suppressToggle = true;
                try
                {
                    _checkBox.Pressed = value;
                }
                finally
                {
                    _suppressToggle = false;
                }
            }
        }

        public OptionCrtUiEnabled(
            OptionsTabControlRow controller,
            IConfigurationManager cfg,
            CheckBox checkBox)
            : base(controller, cfg, CCVars.CrtUiEnabled)
        {
            _checkBox = checkBox;
            _checkBox.OnToggled += _ =>
            {
                if (_suppressToggle)
                    return;

                ValueChanged();
            };
        }

        public override void LoadValue()
        {
            base.LoadValue();
            NotifyPreviewValueChanged();
        }

        public override void SaveValue()
        {
            base.SaveValue();
            NotifyPreviewValueChanged();
        }

        public override void ResetToDefault()
        {
            base.ResetToDefault();
            NotifyPreviewValueChanged();
        }

        protected override void ValueChanged()
        {
            base.ValueChanged();
            NotifyPreviewValueChanged();
        }

        private void NotifyPreviewValueChanged()
        {
            PreviewValueChanged?.Invoke();
        }
    }

    private sealed class OptionCrtUiColor : BaseOptionCVar<string>
    {
        private readonly OptionColorSlider _slider;
        private bool _suppressColorChanged;

        public event Action? PreviewValueChanged;

        protected override string Value
        {
            get => _slider.Slider.Color.ToHex();
            set
            {
                _suppressColorChanged = true;
                try
                {
                    _slider.Slider.Color = ResolveCrtColor(value);
                }
                finally
                {
                    _suppressColorChanged = false;
                }

                UpdateLabelColor();
            }
        }

        public OptionCrtUiColor(
            OptionsTabControlRow controller,
            IConfigurationManager cfg,
            OptionColorSlider slider)
            : base(controller, cfg, CCVars.CrtUiColor)
        {
            _slider = slider;

            slider.Slider.OnColorChanged += _ =>
            {
                if (_suppressColorChanged)
                {
                    UpdateLabelColor();
                    return;
                }

                ValueChanged();
            };
        }

        public override void LoadValue()
        {
            base.LoadValue();
            NotifyPreviewValueChanged();
        }

        public override void SaveValue()
        {
            base.SaveValue();
            NotifyPreviewValueChanged();
        }

        public override void ResetToDefault()
        {
            base.ResetToDefault();
            NotifyPreviewValueChanged();
        }

        protected override void ValueChanged()
        {
            base.ValueChanged();
            UpdateLabelColor();
            NotifyPreviewValueChanged();
        }

        protected override bool IsValueEqual(string a, string b)
        {
            return ResolveCrtColor(a).ToHex() == ResolveCrtColor(b).ToHex();
        }

        private void UpdateLabelColor()
        {
            _slider.ExampleLabel.FontColorOverride = _slider.Slider.Color;
        }

        private void NotifyPreviewValueChanged()
        {
            PreviewValueChanged?.Invoke();
        }

        private static Color ResolveCrtColor(string value)
        {
            var color = Color.TryFromHex(value);
            if (color != null)
                return color.Value;

            return value switch
            {
                CCVars.CrtUiColorBlue => Color.FromHex("#58CCFF"),
                CCVars.CrtUiColorOrange => Color.FromHex("#FFB454"),
                CCVars.CrtUiColorRed => Color.FromHex("#FF4E5E"),
                CCVars.CrtUiColorPurple => Color.FromHex("#C45BFF"),
                _ => Color.FromHex(CCVars.CrtUiColorDefault),
            };
        }
    }
}
