using System.Linq;
using Content.Shared._CMU14.Threats.Mobs.Wendigo;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CMU14.Threats.Mobs.Wendigo;

[GenerateTypedNameReferences]
public sealed partial class WendigoVoiceWindow : DefaultWindow
{
    private List<WendigoVoiceLine> _allLines = new();
    private string? _selectedCategory;

    public WendigoVoiceWindow()
    {
        RobustXamlLoader.Load(this);
        SearchBar.OnTextChanged += _ => RebuildList();
    }

    public event Action<string>? OnLineSelected;

    public void SetLines(List<WendigoVoiceLine> lines)
    {
        _allLines = lines.OrderBy(l => l.Category).ThenBy(l => l.DisplayName).ToList();
        RebuildCategories();
        RebuildList();
    }

    private void RebuildCategories()
    {
        CategoryList.RemoveAllChildren();

        var allButton = new Button
        {
            Text = "All",
            HorizontalExpand = true,
            ToggleMode = true,
            Pressed = _selectedCategory == null
        };
        allButton.OnPressed += _ =>
        {
            _selectedCategory = null;
            RebuildList();
            UpdateCategoryButtonStates();
        };
        CategoryList.AddChild(allButton);

        foreach (string category in _allLines.Select(l => l.Category).Distinct().OrderBy(c => c))
        {
            string cat = category;
            var button = new Button
            {
                Text = cat,
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = _selectedCategory == cat
            };
            button.OnPressed += _ =>
            {
                _selectedCategory = cat;
                RebuildList();
                UpdateCategoryButtonStates();
            };
            CategoryList.AddChild(button);
        }
    }

    private void UpdateCategoryButtonStates()
    {
        var i = 0;
        foreach (Control child in CategoryList.Children)
        {
            if (child is Button btn)
            {
                btn.Pressed = i == 0
                    ? _selectedCategory == null
                    : btn.Text == _selectedCategory;
            }

            i++;
        }
    }

    private void RebuildList()
    {
        LineList.RemoveAllChildren();

        string search = SearchBar.Text.Trim().ToLowerInvariant();

        List<WendigoVoiceLine> filtered = _allLines
            .Where(l => _selectedCategory == null || l.Category == _selectedCategory)
            .Where(l => string.IsNullOrEmpty(search) || l.DisplayName.ToLowerInvariant().Contains(search))
            .ToList();

        foreach (WendigoVoiceLine line in filtered)
        {
            var button = new Button
            {
                Text = line.DisplayName,
                HorizontalExpand = true,
                StyleClasses = { "OpenRight" }
            };

            string emoteId = line.EmoteId;
            button.OnPressed += _ => OnLineSelected?.Invoke(emoteId);
            LineList.AddChild(button);
        }

        if (!filtered.Any())
        {
            LineList.AddChild(new Label
            {
                Text = "No results.",
                FontColorOverride = Color.FromHex("#888888"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new(0, 12)
            });
        }
    }
}
