- type: loadoutGroup
  id: ColonySynthSuitAU14
  name: rmc-loadout-group-synthetic-suits
  minLimit: 0
  maxLimit: 1
  loadouts:
  - CoatBomberRMC
  - ExternalWebbingRMC
  - HazardVestRMC
  - HazardVestBlueRMC
  - HazardVestYellowRMC
  - HazardVestBlackRMC
  - LabcoatRMC
  - CivilianFullSuitWeYuEngineerAU14
  - QuartermasterJacketRMC
  - CorporateBlackJacketRMC
  - CorporateBrownJacketRMC
  - CorporateBlueJacketRMC
  - JacketWindbreakerRMC
  - BioSuitOuterClothingSynthCMU14 # Unsure about this one maybe when we get researcher for colony synths
  - ExpeditionWindbreakerOuterClothingSynthCMU14
  - LabcoatScienceOuterClothingSynthCMU14
