- type: loadoutGroup
  id: ColonySynthSpecializationAU14
  name: au14-loadout-group-role-specific-ID
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ColonySyntheticSpecializationDefaultAU14
  - ColonySyntheticSpecializationEngineeringAU14
  - ColonySyntheticSpecializationMedicalAU14
  - ColonySyntheticSpecializationCommandAU14
