- type: loadoutGroup
  id: ColonySynthUniformAU14
  name: rmc-loadout-group-synthetic-uniform
  minLimit: 1
  loadouts:
  - CivilianBoilerSuitDarkBlueSynthAU14
  - BlueUtilityUniformSynthCMU14
  - BrownUtilityUniformSynthCMU14
  - RedUtilityUniformSynthCMU14
  - YellowUtilityUniformSynthCMU14
  - WorkingJoeUniformSynthCMU14
  - WhiteBoilerUniformSynthCMU14
  - LightBlueBoilerUniformSynthCMU14
  - KhakiBoilerUniformSynthCMU14
  - GreyBoilerUniformSynthCMU14
  - GreenBoilerUniformSynthCMU14
  - FrontierUniformSynthCMU14
  - OutdatedUniformSynthCMU14
  - CivilianWorkwearYellowAU14
  - CivilianWorkwearPinkAU14
  - CivilianWorkwearBlueAU14
  - CivilianWorkwearGreenAU14
  - JumpsuitDutchBandolierAU14
  - JumpsuitCivilianAU14
  - JumpsuitColonistAU14
  - JumpsuitTShirtWhiteAU14
  - JumpsuitTShirtGrayAU14
  - JumpsuitTShirtRedAU14
  - CivilianWeYuEngineerClothesAU14
  - ScrubsBlueRMC
  - ScrubsLightBlueRMC
  - ScrubsGreenRMC
  - ScrubsPurpleRMC
  - ScrubsOliveRMC
  - ScrubsGreyRMC
