- type: loadoutGroup
  id: EROGlovesAU14
  name: au14-loadout-group-civilian-gloves
  minLimit: 1
  maxLimit: 2
  loadouts:
  - ClothingHandGlovesNitrileAU14
  - HandsLatexAU14
  - HandsVeteranInsulatedAU14
