- type: loadoutGroup
  id: EROJacketAU14
  name: au14-loadout-group-civilian-jacket
  minLimit: 1
  maxLimit: 1
  loadouts:
  - CivilianFullSuitParamedicRedAU14
  - CivilianFullSuitParamedicGreenAU14
  - CivilianFullSuitFirefighterAU14
  - CivilianFullSuitFirefighterUPPAU14
