- type: loadoutGroup
  id: JournalistSpecializationAU14
  name: au14-loadout-group-role-specific-ID
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ColonyJournalistSpecializationDefaultAU14
  - ColonyJournalistSpecializationPhotoJournalistAU14
  - ColonyJournalistSpecializationIndependentAU14
  - ColonyJournalistSpecializationFreePressAU14
