- type: loadoutGroup
  id: ScientistPouchAU14
  name: au14-loadout-group-civilian-pouch
  minLimit: 1
  maxLimit: 1
  loadouts:
  - PouchSyringeFillAU14
  - PouchMedicalAU14
  - PouchAutoinjectorAU14
  - PouchVialFillRightAU14
