- type: loadoutGroup
  id: SynthAccesoriesSpecialAU14
  name: au14-loadout-group-synth-webbing
  minLimit: 1
  maxLimit: 1
  loadouts:
  - WebbingSurgicalBlueAU14
  - WebbingSurgicalGreenCMU14
  # - AU14GOVFORIOHeadset # I dont see OPFOR loadouts so use AU14OPFORIOHeadset for OPFOR

# Doctor
