- type: rank
  id: AU14RankScientistProfessor
  name: Professor
  prefix: Prof.

- type: rank
  id: AU14RankScientistAssociate
  name: Associate Professor
  prefix: Asso-Prof.

- type: rank
  id: AU14RankScientistAssistant
  name: Assistant Professor
  prefix: Assist-Prof.
