using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CMU14.Yautja;

[GenerateTypedNameReferences]
public sealed partial class YautjaBadBloodWeaponChoiceWindow : DefaultWindow
{
    public bool WeaponChosen;

    public YautjaBadBloodWeaponChoiceWindow()
    {
        RobustXamlLoader.Load(this);
        CloseButton.Visible = false;
    }

    public override void Close()
    {
        if (!WeaponChosen)
            return;

        base.Close();
    }
}
