- type: job
  parent: CMJobBase
  id: AU14JobReturningColonist
  roundSide: Civilian
  roundForce: COLONY
  roundRole: ReturningColonist
  roundComponents:
  - type: EquipEntityPreset
    preset: AU14ReturningColonistPreset
  - type: Skills
    skills:
      RMCSkillFireman: 1
      RMCSkillVehicles: 1
      RMCSkillDomestics: 1
      RMCSkillFirearms: 2
  - type: JobPrefix
    prefix: au14-job-prefix-civiliancolonist
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth

  name: au14-job-name-civiliancolonist
  description: au14-job-description-civiliancolonist
  setPreference: true
  playTimeTracker: AU14JobReturningColonist
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCivilianColonist
  spawnMenuRoleName: Colonist (3rd party)
  icon: "CMJobIconEmpty"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  accessGroups:
  - Colonist
  roleWeight: 0.25
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicMisc
  id: AU14JobReturningColonist
  name: Returning Colonist (civilian)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: Returning Colonist (civilian)
    description: You are a local colonist that is returning to the colony. You were on vacations, went to work abroad or any other factinating story. But no one cares now. Get back to work.
    reregister: false
    job: AU14JobReturningColonist
    raffle:
      settings: short
    rules: You do not know what is going on in the colony.

- type: entity
  id: AU14ReturningColonistPreset
  name: returning colonist preset
  categories: [ HideSpawnMenu ]
  components:
  - type: EntityPreset
    randomGearOther:
    -
      - [ CMJumpsuitColonist ]
      - [ RMCJumpsuitCivilian ]
      - [ CMJumpsuitTShirtWhite ]
      - [ CMJumpsuitTShirtGray ]
    -
      - [ RMCShoesBlack ]
      - [ RMCBootsVanBandolier ]
      - [ RMCShoesBrown ]
    -
      - [ AU14SlingSatchelBlue ]
      - [ AU14SlingSatchelBlack ]
      - [ CMSatchel ]
    -
      - [ RMCSpaceCash100 ]
      - [ RMCSpaceCash100 ]
      - [ RMCSpaceCash100 ]
      - [ RMCSpaceCash10 ]
      - [ RMCSpaceCash20 ]
      - [ RMCSpaceCash20 ]
      - [ RMCSpaceCash20 ]
      - [ RMCSpaceCash200 ]
      - [ RMCSpaceCash50 ]
      - [ RMCSpaceCash50 ]
      - [ RMCSpaceCash50 ]
      - [ RMCSpaceCash50 ]

- type: playTimeTracker
  id: AU14JobReturningColonist
  isHumanoid: true
