using System.Numerics;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.UserInterface.Screens;

[GenerateTypedNameReferences]
public sealed partial class SeparatedChatGameScreen : InGameScreen
{
    private const float DefaultChatSplitFraction = 0.6f;
    private const float MinChatSplitFraction = 0.35f;
    private const float MaxChatSplitFraction = 0.85f;
    private const int ApplyChatSplitFrames = 12;

    private float? _pendingChatSplitFraction;
    private int _pendingChatSplitFrames;

    public SeparatedChatGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(ScreenContainer, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(Inventory, LayoutPreset.BottomLeft, margin: 5);
        SetAnchorAndMarginPreset(TopLeftContainer, LayoutPreset.TopLeft, margin: 10);
        SetAnchorAndMarginPreset(Ghost, LayoutPreset.BottomWide, margin: 80);
        SetAnchorAndMarginPreset(Hotbar, LayoutPreset.BottomWide, margin: 5);
        SetAnchorAndMarginPreset(Alerts, LayoutPreset.CenterRight, margin: 10);

        // RMC14
        SetGrowVertical(Alerts, GrowDirection.Both);

        ScreenContainer.OnSplitResizeFinished += OnSplitResizeFinished;

        ViewportContainer.OnResized += ResizeActionContainer;
    }

    private void ResizeActionContainer()
    {
        float indent = 20;
        Actions.ActionsContainer.MaxGridWidth = ViewportContainer.Size.X - indent;
    }

    public override ChatBox ChatBox => GetWidget<ChatBox>()!;

    public override void SetChatSize(Vector2 size)
    {
        ScreenContainer.ResizeMode = SplitContainer.SplitResizeMode.RespectChildrenMinSize;
        _pendingChatSplitFraction = NormalizeChatSplitFraction(size.X);
        _pendingChatSplitFrames = ApplyChatSplitFrames;
        ApplyPendingChatSplitFraction();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_pendingChatSplitFraction == null || _pendingChatSplitFrames <= 0)
            return;

        if (!ApplyPendingChatSplitFraction())
            return;

        _pendingChatSplitFrames--;
        if (_pendingChatSplitFrames == 0)
            _pendingChatSplitFraction = null;
    }

    private void OnSplitResizeFinished()
    {
        _pendingChatSplitFraction = null;
        _pendingChatSplitFrames = 0;
        OnChatResized?.Invoke(new Vector2(ScreenContainer.SplitFraction, 0));
    }

    private bool ApplyPendingChatSplitFraction()
    {
        if (_pendingChatSplitFraction is not { } fraction || ScreenContainer.Size.X <= 0)
            return false;

        ScreenContainer.SplitFraction = fraction;
        return true;
    }

    private static float NormalizeChatSplitFraction(float fraction)
    {
        if (!float.IsFinite(fraction) || fraction <= 0)
            fraction = DefaultChatSplitFraction;

        return Math.Clamp(fraction, MinChatSplitFraction, MaxChatSplitFraction);
    }
}
