using System;
using System.Linq;
using Content.Client._RMC14.Chat;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Chat;
using Content.Client.UserInterface.Systems.Chat.Controls;
using Content.Shared.CCVar;
using Content.Shared.Chat;
using Content.Shared.Input;
using Content.Shared.Radio;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Configuration;
using Robust.Shared.Input;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.LineEdit;

namespace Content.Client.UserInterface.Systems.Chat.Widgets;

[GenerateTypedNameReferences]
[Virtual]
public partial class ChatBox : UIWidget
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private ILogManager _log = default!;
    [Dependency] private IConfigurationManager _config = default!;
    [Dependency] private IPrototypeManager _prototype = default!;

    private readonly ISawmill _sawmill;
    private readonly ChatUIController _controller;
    private readonly Dictionary<string, ChatTabButton> _tabButtons = new();
    private readonly Dictionary<string, int> _tabUnread = new();
    private readonly List<ChatTabSettings> _overflowTabs = new();
    private List<ChatTabSettings> _tabs = new();
    private List<ChatStyleSettings> _styles = new();
    private IReadOnlyList<ChatStyleTarget> _styleTargets = Array.Empty<ChatStyleTarget>();
    private IReadOnlyList<ChatRadioTarget> _radioTargets = Array.Empty<ChatRadioTarget>();
    private string _activeTabId = ChatUserSettings.AllTabId;
    private string _secondaryTabId = ChatUserSettings.RadioTabId;
    private string? _draggingTabId;
    private string? _dragTargetTabId;
    private bool _splitChatEnabled;
    private bool _splitAvailable = true;
    private bool _legacyChatEnabled;
    private bool _forceLegacyPresentation;
    private bool _colorWholeMessage;
    private ChatChannel _legacyChannelMask = (ChatChannel) ushort.MaxValue;
    private int _secondaryRatioPercent = ChatUserSettings.DefaultSplitSecondaryRatioPercent;
    private bool _syncingFilter;
    private bool LegacyPresentation => _forceLegacyPresentation || _legacyChatEnabled;
    private static readonly Color StructuredMessageTextColor = Color.FromHex("#D6DCE0");

    public bool Main { get; set; }

    public ChatSelectChannel SelectedChannel => ChatInput.ChannelSelector.SelectedChannel;

    public void SetSplitAvailable(bool available)
    {
        _splitAvailable = available;
        SplitButton.Visible = available && !LegacyPresentation;
        if (!available)
        {
            SplitButton.Popup.Close();
            SetSplitChatEnabled(false, save: false);
            return;
        }

        SyncSplitControls();
    }

    public void SetForceLegacyPresentation(bool forced)
    {
        var wasLegacy = LegacyPresentation;
        if (_forceLegacyPresentation == forced)
            return;

        _forceLegacyPresentation = forced;
        if (!wasLegacy && LegacyPresentation)
            ResetLegacyChannelMask();

        ApplyChatMode();
        Repopulate();
    }

    // RMC14
    private readonly Queue<RepeatedMessage> _primaryRepeatQueue = new();
    private readonly Queue<RepeatedMessage> _secondaryRepeatQueue = new();
    private readonly Queue<RepeatedMessage> _legacyRepeatQueue = new();
    private readonly HashSet<string> _whitelist = ["mono", "scramble", "bolditalic", "bold", "bullet", "cmdlink", "color", "font", "head", "italic", "langicon"];
    // RMC14

    public ChatBox()
    {
        RobustXamlLoader.Load(this);
        _sawmill = _log.GetSawmill("chat");

        ChatInput.Input.OnTextEntered += OnTextEntered;
        ChatInput.Input.OnKeyBindDown += OnInputKeyBindDown;
        ChatInput.Input.OnTextChanged += OnTextChanged;
        ChatInput.Input.OnFocusEnter += OnFocusEnter;
        ChatInput.Input.OnFocusExit += OnFocusExit;
        ChatInput.ChannelSelector.OnChannelSelect += OnChannelSelect;
        ChatInput.FilterButton.Popup.OnChannelFilter += OnChannelFilter;
        ChatInput.FilterButton.Popup.OnNewHighlights += OnNewHighlights;
        ChatInput.FilterButton.Popup.OnTabSelected += OnSettingsTabSelected;
        ChatInput.FilterButton.Popup.OnTabAdded += OnSettingsTabAdded;
        ChatInput.FilterButton.Popup.OnTabRemoved += OnSettingsTabRemoved;
        ChatInput.FilterButton.Popup.OnTabRenamed += OnSettingsTabRenamed;
        ChatInput.FilterButton.Popup.OnTabMoved += OnSettingsTabMoved;
        ChatInput.FilterButton.Popup.OnRadioFilter += OnSettingsRadioFilter;
        ChatInput.FilterButton.Popup.OnStyleChanged += OnSettingsStyleChanged;
        ChatInput.FilterButton.Popup.OnStyleReset += OnSettingsStyleReset;
        ChatInput.FilterButton.Popup.OnColorWholeMessageChanged += OnSettingsColorWholeMessageChanged;
        ChatInput.FilterButton.Popup.OnLegacyModeChanged += OnSettingsLegacyModeChanged;
        SplitButton.Popup.OnTabSelected += OnSplitTabSelected;
        TabOverflowButton.Popup.OnTabSelected += OnOverflowTabSelected;
        SecondaryResizeHandle.OnDragged += OnSplitResizeDragged;
        SecondaryResizeHandle.OnDragEnded += OnSplitResizeEnded;
        _controller = UserInterfaceManager.GetUIController<ChatUIController>();
        _controller.MessageAdded += OnMessageAdded;
        _controller.HighlightsUpdated += OnHighlightsUpdated;
        _controller.FilterableChannelsChanged += OnFilterableChannelsChanged;
        _controller.RegisterChat(this);
        _config.OnValueChanged(CCVars.ChatLegacyMode, OnLegacyModeCvarChanged);
        _config.OnValueChanged(CCVars.ChatColorWholeMessage, OnColorWholeMessageCvarChanged);

        _tabs = ChatUserSettings.LoadTabs(_config.GetCVar(CCVars.ChatTabs));
        _styles = ChatUserSettings.LoadStyles(_config.GetCVar(CCVars.ChatChannelStyles));
        var split = ChatUserSettings.LoadSplitPane(_config.GetCVar(CCVars.ChatSplitPane));
        _splitChatEnabled = split.Enabled;
        _secondaryTabId = split.SecondaryTabId;
        _secondaryRatioPercent = split.SecondaryRatioPercent;
        _legacyChatEnabled = _config.GetCVar(CCVars.ChatLegacyMode);
        _colorWholeMessage = _config.GetCVar(CCVars.ChatColorWholeMessage);
        var radioChannels = _prototype.EnumeratePrototypes<RadioChannelPrototype>().ToList();
        _styleTargets = ChatUserSettings.CreateStyleTargets(radioChannels);
        _radioTargets = ChatUserSettings.CreateRadioTargets(radioChannels);

        RebuildTabs();
        SetActiveTab(_activeTabId, repopulate: false);
        SetSplitChatEnabled(_splitChatEnabled, repopulate: false, save: false);
        ApplyChatMode();
        Repopulate();
    }

    protected override void Resized()
    {
        base.Resized();
        UpdateTabOverflowControls();
        RefreshVisibleChatLayout();
    }

    private void OnTextEntered(LineEditEventArgs args)
    {
        _controller.SendMessage(this, SelectedChannel);
    }

    private void OnMessageAdded(ChatMessage msg)
    {
        _sawmill.Debug($"{msg.Channel}: {msg.Message}");
        DisplayMessage(msg, fromHistory: false);
    }

    private void DisplayMessage(ChatMessage msg, bool fromHistory)
    {
        if (LegacyPresentation)
        {
            var visible = IsMessageVisibleInLegacy(msg);
            if (visible)
                AddLegacyLine(msg);

            if (fromHistory || !visible)
                return;

            if (msg is { Read: false, AudioPath: { } })
                _entManager.System<AudioSystem>().PlayGlobal(new ResolvedPathSpecifier(msg.AudioPath), Filter.Local(), false, AudioParams.Default.WithVolume(msg.AudioVolume));

            msg.Read = true;
            return;
        }

        if (fromHistory)
        {
            if (IsMessageVisibleInActiveTab(msg))
                AddLine(msg, Contents, _primaryRepeatQueue);

            if (IsMessageVisibleInSecondaryTab(msg))
                AddLine(msg, SecondaryContents, _secondaryRepeatQueue);

            return;
        }

        if (!IsMessageVisibleInAnyPage(msg))
            return;

        if (msg is { Read: false, AudioPath: { } })
            _entManager.System<AudioSystem>().PlayGlobal(new ResolvedPathSpecifier(msg.AudioPath), Filter.Local(), false, AudioParams.Default.WithVolume(msg.AudioVolume));

        msg.Read = true;

        UpdateInactiveTabUnreads(msg);

        if (IsMessageVisibleInActiveTab(msg))
            AddLine(msg, Contents, _primaryRepeatQueue);

        if (IsMessageVisibleInSecondaryTab(msg))
            AddLine(msg, SecondaryContents, _secondaryRepeatQueue);
    }

    private void OnHighlightsUpdated(string highlights)
    {
        ChatInput.FilterButton.Popup.UpdateHighlights(highlights);
    }

    private void OnChannelSelect(ChatSelectChannel channel)
    {
        _controller.UpdateSelectedChannel(this);
    }

    public void Repopulate()
    {
        if (LegacyPresentation)
        {
            LegacyContents.Clear();
            _legacyRepeatQueue.Clear();

            foreach (var message in _controller.History)
            {
                if (IsMessageVisibleInLegacy(message.Item2))
                    AddLegacyLine(message.Item2);
            }

            LegacyContents.ScrollToBottom();
            return;
        }

        Contents.Clear();
        _primaryRepeatQueue.Clear();

        foreach (var message in _controller.History)
        {
            if (IsMessageVisibleInActiveTab(message.Item2))
                AddLine(message.Item2, Contents, _primaryRepeatQueue);
        }

        Contents.ScrollToBottom();

        if (_splitChatEnabled)
            RepopulateSecondary();
    }

    private void OnChannelFilter(ChatChannel channel, bool active)
    {
        if (_syncingFilter)
            return;

        if (LegacyPresentation)
        {
            _legacyChannelMask = active
                ? _legacyChannelMask | channel
                : _legacyChannelMask & ~channel;

            Repopulate();

            if (active)
                _controller.ClearUnfilteredUnreads(channel);

            return;
        }

        var tab = GetActiveTab();
        if (IsAllTab(tab))
            return;

        tab.ChannelMask = active
            ? tab.ChannelMask | channel
            : tab.ChannelMask & ~channel;
        SaveTabs();

        Repopulate();

        if (active)
            _controller.ClearUnfilteredUnreads(channel);
    }

    private void OnNewHighlights(string highlighs)
    {
        _controller.UpdateHighlights(highlighs);
    }

    private void OnFilterableChannelsChanged(ChatChannel _)
    {
        RebuildTabs();
        SyncFilterPopup();
        Repopulate();
    }

    private void RebuildTabs()
    {
        _draggingTabId = null;
        _dragTargetTabId = null;

        foreach (var button in _tabButtons.Values)
        {
            TabBar.RemoveChild(button);
        }

        _tabButtons.Clear();

        foreach (var tab in _tabs)
        {
            if (!IsTabVisible(tab))
                continue;

            var capturedTabId = tab.Id;
            var isAll = IsAllTab(tab);
            var button = new ChatTabButton(tab.Id)
            {
                ToggleMode = true,
                Mode = BaseButton.ActionMode.Release,
                MinWidth = Math.Max(58, tab.Title.Length * 9),
                StyleClasses = { StyleNano.StyleClassChatChannelSelectorButton },
                CanDrag = !isAll
            };
            button.OnPressed += _ => SetActiveTab(capturedTabId);
            button.DragStarted += OnTabDragStarted;
            button.DragEntered += OnTabDragEntered;
            button.DragExited += OnTabDragExited;
            button.DragEnded += OnTabDragEnded;
            TabBar.AddChild(button);
            _tabButtons[capturedTabId] = button;
        }

        if (_tabButtons.Count == 0)
        {
            _tabs = ChatUserSettings.CreateDefaultTabs();
            SaveTabs();
            RebuildTabs();
            return;
        }

        if (!_tabButtons.ContainsKey(_activeTabId))
            _activeTabId = _tabButtons.Keys.First();

        NormalizeSecondaryTab();

        UpdateTabButtons();
        SyncSplitControls();
    }

    private void SetActiveTab(string tabId, bool repopulate = true)
    {
        if (!_tabButtons.ContainsKey(tabId))
            tabId = _tabButtons.Keys.FirstOrDefault() ?? ChatUserSettings.AllTabId;

        _activeTabId = tabId;
        _tabUnread[tabId] = 0;
        UpdateTabButtons();
        SyncFilterPopup();

        if (repopulate)
            Repopulate();
    }

    private void SetSplitChatEnabled(bool enabled, bool repopulate = true, bool save = true)
    {
        enabled &= _splitAvailable;
        _splitChatEnabled = enabled;
        SecondaryPane.Visible = enabled && !LegacyPresentation;

        if (enabled)
        {
            NormalizeSecondaryTab();

            ApplySplitRatio();
            if (repopulate)
                RepopulateSecondary();
        }
        else
        {
            SecondaryContents.Clear();
            _secondaryRepeatQueue.Clear();
        }

        UpdateTabButtons();
        SyncSplitControls();

        if (save)
            SaveSplitSettings();
    }

    private void SetSecondaryTab(string tabId, bool repopulate = true)
    {
        if (!IsSecondaryTabVisible(tabId))
            tabId = GetDefaultSecondaryTabId();

        _secondaryTabId = tabId;
        _tabUnread[tabId] = 0;
        UpdateTabButtons();
        SyncSplitControls();
        SaveSplitSettings();

        if (repopulate)
            RepopulateSecondary();
    }

    private void OnSplitTabSelected(string? tabId)
    {
        if (tabId == null)
        {
            SetSplitChatEnabled(false);
            return;
        }

        SetSecondaryTab(tabId, repopulate: false);
        SetSplitChatEnabled(true);
    }

    private void OnOverflowTabSelected(string tabId)
    {
        SetActiveTab(tabId);
    }

    private void OnTabDragStarted(string tabId)
    {
        if (string.Equals(tabId, ChatUserSettings.AllTabId, StringComparison.OrdinalIgnoreCase))
            return;

        _draggingTabId = tabId;
        _dragTargetTabId = null;
        UpdateTabDragVisuals();
    }

    private void OnTabDragEntered(string targetTabId)
    {
        if (_draggingTabId == null)
            return;

        if (string.Equals(_draggingTabId, targetTabId, StringComparison.OrdinalIgnoreCase) ||
            string.Equals(targetTabId, ChatUserSettings.AllTabId, StringComparison.OrdinalIgnoreCase))
        {
            _dragTargetTabId = null;
            UpdateTabDragVisuals();
            return;
        }

        _dragTargetTabId = targetTabId;
        UpdateTabDragVisuals();
    }

    private void OnTabDragExited(string targetTabId)
    {
        if (_draggingTabId == null ||
            !string.Equals(_dragTargetTabId, targetTabId, StringComparison.OrdinalIgnoreCase))
            return;

        _dragTargetTabId = null;
        UpdateTabDragVisuals();
    }

    private void OnTabDragEnded(string tabId)
    {
        var draggingTabId = _draggingTabId;
        if (draggingTabId == null)
            return;

        var targetTabId = _dragTargetTabId;

        _draggingTabId = null;
        _dragTargetTabId = null;

        UpdateTabDragVisuals();

        if (targetTabId != null)
            MoveTabByDrag(draggingTabId, targetTabId);
    }

    private void UpdateTabDragVisuals()
    {
        foreach (var (tabId, button) in _tabButtons)
        {
            var dragging = string.Equals(tabId, _draggingTabId, StringComparison.OrdinalIgnoreCase);
            var dropTarget = string.Equals(tabId, _dragTargetTabId, StringComparison.OrdinalIgnoreCase);
            button.SetDragVisualState(dragging, dropTarget);
        }
    }

    private void OnSplitResizeDragged(GUIMouseMoveEventArgs args)
    {
        if (!_splitChatEnabled || ChatPanes.Height <= 0)
            return;

        var bottom = ChatPanes.GlobalPosition.Y + ChatPanes.Height;
        var secondaryHeight = bottom - args.GlobalPosition.Y;
        var ratio = (int) Math.Round(secondaryHeight / ChatPanes.Height * 100f);
        var normalized = ChatUserSettings.NormalizeSplitRatioPercent(ratio);
        if (normalized == _secondaryRatioPercent)
            return;

        _secondaryRatioPercent = normalized;
        ApplySplitRatio();
    }

    private void OnSplitResizeEnded()
    {
        if (_splitChatEnabled)
            SaveSplitSettings();
    }

    private void ApplySplitRatio()
    {
        _secondaryRatioPercent = ChatUserSettings.NormalizeSplitRatioPercent(_secondaryRatioPercent);
        Contents.SizeFlagsStretchRatio = 100 - _secondaryRatioPercent;
        SecondaryPane.SizeFlagsStretchRatio = _secondaryRatioPercent;
    }

    private void SyncSplitControls()
    {
        var visibleTabs = _tabs.Where(IsTabVisible).ToList();
        SplitButton.Visible = _splitAvailable && !LegacyPresentation;
        SplitButton.Popup.ConfigureTabs(visibleTabs, _secondaryTabId, _splitChatEnabled);
        SplitButton.SetSplitState(_splitChatEnabled, GetTabTitle(_secondaryTabId));
        UpdateTabOverflowControls();
    }

    private void ApplyChatMode()
    {
        var legacy = LegacyPresentation;
        TabHeader.Visible = !legacy;
        ChatPanes.Visible = !legacy;
        LegacyContents.Visible = legacy;
        SecondaryPane.Visible = !legacy && _splitChatEnabled;
        ChatInput.SetLegacyMode(legacy);
        SyncSplitControls();
        SyncFilterPopup();
    }

    private void RepopulateSecondary()
    {
        SecondaryContents.Clear();
        _secondaryRepeatQueue.Clear();

        if (!_splitChatEnabled)
            return;

        var tab = GetSecondaryTab();
        foreach (var message in _controller.History)
        {
            if (IsMessageVisibleInTab(tab, message.Item2))
                AddLine(message.Item2, SecondaryContents, _secondaryRepeatQueue);
        }

        SecondaryContents.ScrollToBottom();
    }

    private void UpdateTabButtons()
    {
        foreach (var (tabId, button) in _tabButtons)
        {
            button.Text = GetTabButtonText(tabId);
            button.Pressed = tabId == _activeTabId;
            button.Modulate = tabId == _activeTabId
                ? Color.FromHex("#9fd0b3")
                : Color.FromHex("#737987");
        }

        UpdateTabDragVisuals();
        UpdateTabOverflowControls();
    }

    private void UpdateTabOverflowControls()
    {
        if (LegacyPresentation || _tabButtons.Count == 0)
        {
            TabOverflowButton.SetHiddenCount(0);
            foreach (var button in _tabButtons.Values)
            {
                button.Visible = true;
            }
            return;
        }

        var visibleTabs = _tabs.Where(tab => IsTabVisible(tab) && _tabButtons.ContainsKey(tab.Id)).ToList();
        _overflowTabs.Clear();

        var width = TabHeader.Width > 0 ? TabHeader.Width : Width;
        if (width <= 0)
        {
            TabOverflowButton.SetHiddenCount(0);
            foreach (var tab in visibleTabs)
            {
                _tabButtons[tab.Id].Visible = true;
            }
            return;
        }

        var splitWidth = SplitButton.Visible
            ? Math.Max(SplitButton.Width, SplitButton.MinWidth) + 4
            : 0;
        var availableWithOverflow = Math.Max(120, width - splitWidth - 52);
        var hidden = ApplyTabOverflow(visibleTabs, availableWithOverflow);

        if (hidden.Count == 0)
            hidden = ApplyTabOverflow(visibleTabs, Math.Max(120, width - splitWidth - 8));

        _overflowTabs.AddRange(hidden);
        TabOverflowButton.SetHiddenCount(_overflowTabs.Count);
        TabOverflowButton.Popup.ConfigureTabs(_overflowTabs, _activeTabId);
    }

    private List<ChatTabSettings> ApplyTabOverflow(IReadOnlyList<ChatTabSettings> visibleTabs, float availableWidth)
    {
        var hidden = new List<ChatTabSettings>();
        var used = 0f;
        var activeReserved = false;

        foreach (var tab in visibleTabs)
        {
            var button = _tabButtons[tab.Id];
            button.Visible = false;
        }

        var active = visibleTabs.FirstOrDefault(tab => string.Equals(tab.Id, _activeTabId, StringComparison.OrdinalIgnoreCase));
        if (active != null)
        {
            var activeButton = _tabButtons[active.Id];
            activeButton.Visible = true;
            used += GetTabButtonWidth(activeButton);
            activeReserved = true;
        }

        foreach (var tab in visibleTabs)
        {
            if (activeReserved && string.Equals(tab.Id, _activeTabId, StringComparison.OrdinalIgnoreCase))
                continue;

            var button = _tabButtons[tab.Id];
            var width = GetTabButtonWidth(button);
            var next = used <= 0 ? width : used + 2 + width;
            if (next <= availableWidth || used <= 0)
            {
                button.Visible = true;
                used = next;
                continue;
            }

            hidden.Add(tab);
        }

        return hidden;
    }

    private static float GetTabButtonWidth(Button button)
    {
        return Math.Max(button.MinWidth, (button.Text?.Length ?? 0) * 9 + 18);
    }

    private string GetTabButtonText(string tabId)
    {
        var title = GetTabTitle(tabId);
        if (_tabUnread.GetValueOrDefault(tabId) is var unread && unread > 0)
            title += unread > 9 ? " (9+)" : $" ({unread})";

        return title;
    }

    private string GetTabTitle(string tabId)
    {
        return _tabs.FirstOrDefault(tab => tab.Id == tabId)?.Title ?? "TAB";
    }

    private void SyncFilterPopup()
    {
        var activeTab = GetActiveTab();
        var available = _controller.FilterableChannels;

        _syncingFilter = true;
        ChatInput.FilterButton.SetAllowedChannels(available);
        ChatInput.FilterButton.Popup.SetActiveMask(
            LegacyPresentation
                ? _legacyChannelMask & available
                : GetTabChannelMask(activeTab) & available,
            quiet: true);
        ChatInput.FilterButton.Popup.SetFiltersReadOnly(!LegacyPresentation && IsAllTab(activeTab));
        ChatInput.FilterButton.Popup.ConfigureRadioFilters(
            _radioTargets,
            LegacyPresentation || IsAllTab(activeTab) ? Array.Empty<string>() : activeTab.RadioLabels,
            !LegacyPresentation && !IsAllTab(activeTab) && (activeTab.ChannelMask & ChatChannel.Radio) != 0);
        ChatInput.FilterButton.Popup.ConfigureTabs(_tabs.Where(IsTabVisible).ToList(), _activeTabId);
        ChatInput.FilterButton.Popup.ConfigureStyles(_styles, _styleTargets);
        ChatInput.FilterButton.Popup.SetColorWholeMessage(_colorWholeMessage);
        ChatInput.FilterButton.Popup.SetLegacyMode(LegacyPresentation);
        _syncingFilter = false;
    }

    private bool IsTabVisible(ChatTabSettings tab)
    {
        if (tab.Id == ChatUserSettings.AdminTabId)
            return (_controller.FilterableChannels & ChatChannel.AdminRelated) != 0;

        return true;
    }

    private void NormalizeSecondaryTab()
    {
        if (!IsSecondaryTabVisible(_secondaryTabId))
            _secondaryTabId = GetDefaultSecondaryTabId();
    }

    private bool IsSecondaryTabVisible(string tabId)
    {
        return _tabs.Any(tab => tab.Id == tabId && IsTabVisible(tab));
    }

    private bool IsMessageVisibleInActiveTab(ChatMessage message)
    {
        return IsMessageVisibleInTab(GetActiveTab(), message);
    }

    private bool IsMessageVisibleInLegacy(ChatMessage message)
    {
        return ((_legacyChannelMask & _controller.FilterableChannels) & message.Channel) != 0;
    }

    private bool IsMessageVisibleInSecondaryTab(ChatMessage message)
    {
        return !LegacyPresentation && _splitAvailable && _splitChatEnabled && IsMessageVisibleInTab(GetSecondaryTab(), message);
    }

    private bool IsMessageVisibleInTab(ChatTabSettings tab, ChatMessage message)
    {
        if (((GetTabChannelMask(tab) & _controller.FilterableChannels) & message.Channel) == 0)
            return false;

        if (IsAllTab(tab) || message.Channel != ChatChannel.Radio || tab.RadioLabels.Count == 0)
            return true;

        var label = ChatUserSettings.NormalizeRadioLabel(message.Display?.ChannelLabel);
        return !string.IsNullOrWhiteSpace(label) &&
               tab.RadioLabels.Any(radioLabel => string.Equals(radioLabel, label, StringComparison.OrdinalIgnoreCase));
    }

    private bool IsMessageVisibleInAnyPage(ChatMessage message)
    {
        foreach (var tab in _tabs)
        {
            if (!IsTabVisible(tab))
                continue;

            if (IsMessageVisibleInTab(tab, message))
                return true;
        }

        return false;
    }

    private void UpdateInactiveTabUnreads(ChatMessage message)
    {
        foreach (var tab in _tabs)
        {
            if (IsTabOpen(tab.Id) || !IsTabVisible(tab))
                continue;

            if (!IsMessageVisibleInTab(tab, message))
                continue;

            _tabUnread[tab.Id] = _tabUnread.GetValueOrDefault(tab.Id) + 1;
        }

        UpdateTabButtons();
    }

    private bool IsTabOpen(string tabId)
    {
        return string.Equals(tabId, _activeTabId, StringComparison.OrdinalIgnoreCase) ||
               !LegacyPresentation && _splitChatEnabled && string.Equals(tabId, _secondaryTabId, StringComparison.OrdinalIgnoreCase);
    }

    private ChatTabSettings GetActiveTab()
    {
        var active = _tabs.FirstOrDefault(tab => tab.Id == _activeTabId);
        if (active != null)
            return active;

        if (_tabs.Count == 0)
            _tabs = ChatUserSettings.CreateDefaultTabs();

        _activeTabId = _tabs[0].Id;
        return _tabs[0];
    }

    private ChatTabSettings GetSecondaryTab()
    {
        var secondary = _tabs.FirstOrDefault(tab => tab.Id == _secondaryTabId && IsTabVisible(tab));
        if (secondary != null)
            return secondary;

        _secondaryTabId = GetDefaultSecondaryTabId();
        return _tabs.FirstOrDefault(tab => tab.Id == _secondaryTabId) ?? GetActiveTab();
    }

    private string GetDefaultSecondaryTabId()
    {
        var radio = _tabs.FirstOrDefault(tab => tab.Id == ChatUserSettings.RadioTabId && IsTabVisible(tab));
        if (radio != null)
            return radio.Id;

        return _tabs.FirstOrDefault(IsTabVisible)?.Id ?? ChatUserSettings.AllTabId;
    }

    private void OnSettingsTabSelected(string tabId)
    {
        SetActiveTab(tabId);
    }

    private void OnSettingsTabAdded(string title)
    {
        var tab = new ChatTabSettings
        {
            Id = ChatUserSettings.CreateCustomTabId(),
            Title = ChatUserSettings.SanitizeTabTitle(title),
            ChannelMask = _controller.FilterableChannels == ChatChannel.None
                ? ChatChannel.OOC
                : _controller.FilterableChannels,
            RadioLabels = new List<string>()
        };

        _tabs.Add(tab);
        SaveTabs();
        RebuildTabs();
        SetActiveTab(tab.Id);
    }

    private void OnSettingsTabRemoved(string tabId)
    {
        if (_tabs.Count <= 1 || string.Equals(tabId, ChatUserSettings.AllTabId, StringComparison.OrdinalIgnoreCase))
            return;

        var removed = _tabs.RemoveAll(tab => tab.Id == tabId) > 0;
        if (!removed)
            return;

        _tabUnread.Remove(tabId);
        if (_activeTabId == tabId)
            _activeTabId = _tabs.FirstOrDefault(IsTabVisible)?.Id ?? _tabs[0].Id;

        if (_secondaryTabId == tabId)
            _secondaryTabId = GetDefaultSecondaryTabId();

        SaveTabs();
        SaveSplitSettings();
        RebuildTabs();
        SetActiveTab(_activeTabId);
    }

    private void OnSettingsTabRenamed(string tabId, string title)
    {
        if (string.Equals(tabId, ChatUserSettings.AllTabId, StringComparison.OrdinalIgnoreCase))
            return;

        var tab = _tabs.FirstOrDefault(entry => string.Equals(entry.Id, tabId, StringComparison.OrdinalIgnoreCase));
        if (tab == null)
            return;

        var sanitized = ChatUserSettings.SanitizeTabTitle(title);
        if (tab.Title == sanitized)
            return;

        tab.Title = sanitized;
        SaveTabs();
        RebuildTabs();
        SyncFilterPopup();
        RefreshVisibleChatLayout();
    }

    private void OnSettingsTabMoved(string tabId, string targetTabId)
    {
        MoveTabByDrag(tabId, targetTabId);
    }

    private void MoveTabByDrag(string tabId, string targetTabId)
    {
        if (string.Equals(tabId, targetTabId, StringComparison.OrdinalIgnoreCase) ||
            string.Equals(tabId, ChatUserSettings.AllTabId, StringComparison.OrdinalIgnoreCase) ||
            string.Equals(targetTabId, ChatUserSettings.AllTabId, StringComparison.OrdinalIgnoreCase))
            return;

        var from = _tabs.FindIndex(tab => string.Equals(tab.Id, tabId, StringComparison.OrdinalIgnoreCase));
        var to = _tabs.FindIndex(tab => string.Equals(tab.Id, targetTabId, StringComparison.OrdinalIgnoreCase));
        if (from <= 0 || to <= 0 || from == to)
            return;

        var moving = _tabs[from];
        _tabs.RemoveAt(from);
        var insertIndex = Math.Clamp(to, 1, _tabs.Count);
        _tabs.Insert(insertIndex, moving);

        SaveTabs();
        RebuildTabs();
        SyncFilterPopup();
        RefreshVisibleChatLayout();
    }

    private void OnSettingsRadioFilter(string label, bool active)
    {
        if (_syncingFilter)
            return;

        if (LegacyPresentation || IsAllTab(GetActiveTab()))
            return;

        var tab = GetActiveTab();
        var normalized = ChatUserSettings.NormalizeRadioLabel(label);
        if (string.IsNullOrWhiteSpace(normalized))
            return;

        if (tab.RadioLabels.Count == 0)
        {
            foreach (var target in _radioTargets)
            {
                if (!tab.RadioLabels.Any(existing => string.Equals(existing, target.Label, StringComparison.OrdinalIgnoreCase)))
                    tab.RadioLabels.Add(target.Label);
            }
        }

        if (active)
        {
            if (!tab.RadioLabels.Any(existing => string.Equals(existing, normalized, StringComparison.OrdinalIgnoreCase)))
                tab.RadioLabels.Add(normalized);
        }
        else
        {
            tab.RadioLabels.RemoveAll(existing => string.Equals(existing, normalized, StringComparison.OrdinalIgnoreCase));
        }

        if (tab.RadioLabels.Count == _radioTargets.Count)
            tab.RadioLabels.Clear();

        SaveTabs();
        SyncFilterPopup();
        Repopulate();
    }

    private void OnSettingsStyleChanged(string target, string? color, string? fontSize)
    {
        if (!_styleTargets.Any(styleTarget => string.Equals(styleTarget.Key, target, StringComparison.OrdinalIgnoreCase)))
            return;

        var normalizedColor = ChatUserSettings.NormalizeColor(color);
        var normalizedFontSize = ChatUserSettings.NormalizeFontSize(fontSize);
        var existing = _styles.FirstOrDefault(style => string.Equals(style.Target, target, StringComparison.OrdinalIgnoreCase));

        if (normalizedColor == null && normalizedFontSize == null)
        {
            if (existing != null)
                _styles.Remove(existing);
        }
        else if (existing == null)
        {
            _styles.Add(new ChatStyleSettings
            {
                Target = target,
                Color = normalizedColor,
                Font = ChatUserSettings.FontDefault,
                FontSize = normalizedFontSize
            });
        }
        else
        {
            existing.Color = normalizedColor;
            existing.Font = ChatUserSettings.FontDefault;
            existing.FontSize = normalizedFontSize;
        }

        SaveStyles();
        SyncFilterPopup();
        Repopulate();
    }

    private void OnSettingsStyleReset(string target)
    {
        _styles.RemoveAll(style => string.Equals(style.Target, target, StringComparison.OrdinalIgnoreCase));
        SaveStyles();
        SyncFilterPopup();
        Repopulate();
    }

    private void OnSettingsLegacyModeChanged(bool enabled)
    {
        if (_legacyChatEnabled == enabled)
            return;

        _config.SetCVar(CCVars.ChatLegacyMode, enabled);
        _config.SaveToFile();
    }

    private void OnSettingsColorWholeMessageChanged(bool enabled)
    {
        if (_colorWholeMessage == enabled)
            return;

        _config.SetCVar(CCVars.ChatColorWholeMessage, enabled);
        _config.SaveToFile();
    }

    private void OnLegacyModeCvarChanged(bool enabled)
    {
        var wasLegacy = LegacyPresentation;
        if (_legacyChatEnabled == enabled)
        {
            SyncFilterPopup();
            return;
        }

        _legacyChatEnabled = enabled;
        if (!wasLegacy && LegacyPresentation)
            ResetLegacyChannelMask();

        ApplyChatMode();
        Repopulate();
    }

    private void OnColorWholeMessageCvarChanged(bool enabled)
    {
        if (_colorWholeMessage == enabled)
        {
            SyncFilterPopup();
            return;
        }

        _colorWholeMessage = enabled;
        SyncFilterPopup();
        Repopulate();
    }

    private void ResetLegacyChannelMask()
    {
        _legacyChannelMask = (ChatChannel) ushort.MaxValue;
    }

    private void SaveTabs()
    {
        foreach (var tab in _tabs)
        {
            if (!IsAllTab(tab))
                continue;

            tab.Title = "ALL";
            tab.Channels = ChatUserSettings.AllChannelBits;
            tab.RadioLabels.Clear();
        }

        _config.SetCVar(CCVars.ChatTabs, ChatUserSettings.SaveTabs(_tabs));
        _config.SaveToFile();
    }

    private static bool IsAllTab(ChatTabSettings tab)
    {
        return string.Equals(tab.Id, ChatUserSettings.AllTabId, StringComparison.OrdinalIgnoreCase);
    }

    private static ChatChannel GetTabChannelMask(ChatTabSettings tab)
    {
        return IsAllTab(tab)
            ? (ChatChannel) ChatUserSettings.AllChannelBits
            : tab.ChannelMask;
    }

    private void RefreshVisibleChatLayout(bool forceScrollToBottom = false)
    {
        if (LegacyPresentation)
        {
            if (forceScrollToBottom)
                LegacyContents.ScrollToBottom();

            return;
        }

        Contents.RefreshLayout(forceScrollToBottom);
        if (_splitChatEnabled)
            SecondaryContents.RefreshLayout(forceScrollToBottom);
    }

    private void SaveStyles()
    {
        var serialized = ChatUserSettings.SaveStyles(_styles);
        _styles = ChatUserSettings.LoadStyles(serialized);
        _config.SetCVar(CCVars.ChatChannelStyles, serialized);
        _config.SaveToFile();
    }

    private void SaveSplitSettings()
    {
        _config.SetCVar(CCVars.ChatSplitPane, ChatUserSettings.SaveSplitPane(_splitChatEnabled, _secondaryTabId, _secondaryRatioPercent));
        _config.SaveToFile();
    }

    public void AddLine(ChatMessage msg)
    {
        if (LegacyPresentation)
        {
            AddLegacyLine(msg);
            return;
        }

        AddLine(msg, Contents, _primaryRepeatQueue);
    }

    private void AddLine(ChatMessage msg, ChatLogPanel contents, Queue<RepeatedMessage> repeatQueue)
    {
        var style = ChatUserSettings.ResolveStyle(_styles, msg);
        var styleColor = ChatUserSettings.ResolveColor(style);
        var fontSize = ChatUserSettings.ResolveFontSize(style) ??
                       ChatUserSettings.ResolveMarkupFontSize(msg.WrappedMessage) ??
                       ChatUserSettings.DefaultFontSize;
        var accentColor = styleColor ?? msg.Display?.AccentColor;
        var messageColor = styleColor ?? msg.MessageColorOverride ?? msg.Display?.AccentColor ?? msg.Channel.TextColor();
        var bodyColor = _colorWholeMessage ? messageColor : StructuredMessageTextColor;
        var formatted = CreateFormattedMessage(msg, messageColor, style);

        var cmChat = _entManager.SystemOrNull<CMChatSystem>();
        if (cmChat?.TryRepetition(repeatQueue, msg.SenderEntity, msg.Message, msg.Channel, msg.RepeatCheckSender, msg.LanguageIcon) ?? false)
            return;

        var row = contents.AddMessage(msg, formatted, bodyColor, accentColor, fontSize);
        cmChat?.TrackRepetition(repeatQueue, row, formatted, msg.SenderEntity, msg.Message, msg.Channel, msg.LanguageIcon);
    }

    private void AddLegacyLine(ChatMessage msg)
    {
        var color = msg.MessageColorOverride ?? msg.Channel.TextColor();
        var formatted = CreateLegacyFormattedMessage(msg, color);

        var cmChat = _entManager.SystemOrNull<CMChatSystem>();
        if (cmChat?.TryLegacyRepetition(_legacyRepeatQueue, LegacyContents, formatted, msg.SenderEntity, msg.Message, msg.Channel, msg.RepeatCheckSender, msg.LanguageIcon) ?? false)
            return;

        cmChat?.TrackLegacyRepetition(_legacyRepeatQueue, LegacyContents, formatted, msg.SenderEntity, msg.Message, msg.Channel, msg.LanguageIcon);
        LegacyContents.AddMessage(formatted);
    }

    public void AddLine(string message, Color color, NetEntity sender, string unwrapped, ChatChannel channel, bool repeatCheckSender)
    {
        var msg = new ChatMessage(
            channel,
            unwrapped,
            message,
            sender,
            null,
            colorOverride: color,
            repeatCheckSender: repeatCheckSender,
            display: new ChatDisplayMetadata(ChatDisplayKind.System, channelLabel: "SYS"));

        AddLine(msg);
    }

    private FormattedMessage CreateFormattedMessage(ChatMessage message, Color color, ChatStyleSettings? style = null)
    {
        var markup = StripGhostFollowCommandLink(message.WrappedMessage, message);
        markup = StripDuplicateChannelPrefix(markup, message);
        markup = _colorWholeMessage
            ? ChatUserSettings.ApplyStyleMarkup(markup, style, ChatUserSettings.DefaultFontSize)
            : ChatUserSettings.ApplyFontMarkup(RemoveOuterColorMarkup(markup), style, ChatUserSettings.DefaultFontSize);

        var formatted = new FormattedMessage(3);
        if (_colorWholeMessage)
            formatted.PushColor(color);

        formatted.AddMarkupOrThrow(markup);

        if (_colorWholeMessage)
            formatted.Pop();

        return FilterProblematicTags(formatted, allowCommandLinks: false);
    }

    private static string StripGhostFollowCommandLink(string markup, ChatMessage message)
    {
        if (!message.GhostFollowEntity.Valid ||
            !markup.StartsWith("[cmdlink=", StringComparison.OrdinalIgnoreCase))
        {
            return markup;
        }

        var tagEnd = markup.IndexOf("/]", StringComparison.Ordinal);
        if (tagEnd < 0)
            return markup;

        var afterTag = tagEnd + 2;
        if (afterTag < markup.Length && markup[afterTag] == ' ')
            afterTag++;

        return markup[afterTag..];
    }

    private static string RemoveOuterColorMarkup(string markup)
    {
        if (!markup.StartsWith("[color=", StringComparison.OrdinalIgnoreCase) ||
            !markup.EndsWith("[/color]", StringComparison.OrdinalIgnoreCase))
        {
            return markup;
        }

        var openEnd = markup.IndexOf(']');
        if (openEnd < 0)
            return markup;

        return markup.Substring(openEnd + 1, markup.Length - openEnd - "[/color]".Length - 1);
    }

    private FormattedMessage CreateLegacyFormattedMessage(ChatMessage message, Color color)
    {
        var formatted = new FormattedMessage(3);
        formatted.PushColor(color);

        // RMC14
        if (!string.IsNullOrWhiteSpace(message.LanguageIcon))
            formatted.AddMarkupOrThrow($"[langicon language=\"{FormattedMessage.EscapeText(message.LanguageIcon)}\"][/langicon]");
        // RMC14
        formatted.AddMarkupOrThrow(message.WrappedMessage);

        formatted.Pop();

        return FilterProblematicTags(formatted, allowCommandLinks: true);
    }

    private static string StripDuplicateChannelPrefix(string markup, ChatMessage message)
    {
        if (!string.IsNullOrWhiteSpace(message.Display?.ChannelLabel))
        {
            var label = message.Display.ChannelLabel.ToUpperInvariant();
            markup = StripVisiblePrefix(markup, $"{label}: ");
            markup = StripVisiblePrefix(markup, $"{label} ");

            if (message.Channel == ChatChannel.Radio)
            {
                markup = StripVisiblePrefix(markup, $@"\[{message.Display.ChannelLabel}\] ");
                markup = StripVisiblePrefix(markup, $"[{message.Display.ChannelLabel}] ");
            }
        }

        switch (message.Channel)
        {
            case ChatChannel.OOC:
                return StripVisiblePrefix(markup, "OOC: ");
            case ChatChannel.LOOC:
                return StripVisiblePrefix(markup, "LOOC: ");
            case ChatChannel.Dead:
                return StripVisiblePrefix(markup, "DEAD: ");
            case ChatChannel.Admin:
            case ChatChannel.AdminAlert:
            case ChatChannel.AdminChat:
                markup = StripVisiblePrefix(markup, "ADMIN: ");
                return StripVisiblePrefix(markup, "ASAY: ");
            case ChatChannel.MentorChat:
                return StripVisiblePrefix(markup, "MENTOR: ");
            default:
                return markup;
        }
    }

    private static string StripVisiblePrefix(string markup, string prefix)
    {
        var index = GetVisibleTextStart(markup);
        if (index < 0 || index + prefix.Length > markup.Length)
            return markup;

        if (!markup.Substring(index, prefix.Length).Equals(prefix, StringComparison.OrdinalIgnoreCase))
            return markup;

        return markup.Remove(index, prefix.Length);
    }

    private static int GetVisibleTextStart(string markup)
    {
        var index = 0;
        while (index < markup.Length && markup[index] == '[')
        {
            if (index + 1 < markup.Length && markup[index + 1] == '/')
                break;

            var end = markup.IndexOf(']', index);
            if (end < 0)
                break;

            index = end + 1;
        }

        return index;
    }

    // RMC14
    private FormattedMessage FilterProblematicTags(FormattedMessage message, bool allowCommandLinks)
    {
        var output = new FormattedMessage(message.Count);
        foreach (var tag in message)
        {
            if (tag.Name == "cmdlink" && !allowCommandLinks)
                continue;

            if (tag.Name is not { } name || _whitelist.Contains(name))
                output.PushTag(tag);
        }
        return output;
    }
    // RMC14

    public void Focus(ChatSelectChannel? channel = null)
    {
        var input = ChatInput.Input;
        var selectStart = Index.End;

        if (channel != null)
            ChatInput.ChannelSelector.Select(channel.Value);

        input.IgnoreNext = true;
        input.GrabKeyboardFocus();

        input.CursorPosition = input.Text.Length;
        input.SelectionStart = selectStart.GetOffset(input.Text.Length);
    }

    public void CycleChatChannel(bool forward)
    {
        var idx = Array.IndexOf(ChannelSelectorPopup.ChannelSelectorOrder, SelectedChannel);
        do
        {
            // go over every channel until we find one we can actually select.
            idx += forward ? 1 : -1;
            idx = MathHelper.Mod(idx, ChannelSelectorPopup.ChannelSelectorOrder.Length);
        } while ((_controller.SelectableChannels & ChannelSelectorPopup.ChannelSelectorOrder[idx]) == 0);

        SafelySelectChannel(ChannelSelectorPopup.ChannelSelectorOrder[idx]);
    }

    public void SafelySelectChannel(ChatSelectChannel toSelect)
    {
        toSelect = _controller.MapLocalIfGhost(toSelect);
        if ((_controller.SelectableChannels & toSelect) == 0)
            return;

        ChatInput.ChannelSelector.Select(toSelect);
    }

    private void OnInputKeyBindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.TextReleaseFocus)
        {
            ChatInput.Input.ReleaseKeyboardFocus();
            ChatInput.Input.Clear();
            args.Handle();
            return;
        }

        if (args.Function == ContentKeyFunctions.CycleChatChannelForward)
        {
            CycleChatChannel(true);
            args.Handle();
            return;
        }

        if (args.Function == ContentKeyFunctions.CycleChatChannelBackward)
        {
            CycleChatChannel(false);
            args.Handle();
        }
    }

    private void OnTextChanged(LineEditEventArgs args)
    {
        // Update channel select button to correct channel if we have a prefix.
        _controller.UpdateSelectedChannel(this);

        // Warn typing indicator about change
        _controller.NotifyChatTextChange();
    }

    private void OnFocusEnter(LineEditEventArgs args)
    {
        // Warn typing indicator about focus
        _controller.NotifyChatFocus(true);
    }

    private void OnFocusExit(LineEditEventArgs args)
    {
        // Warn typing indicator about focus
        _controller.NotifyChatFocus(false);
    }

    [System.Obsolete]
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!disposing) return;
        _controller.UnregisterChat(this);
        _controller.MessageAdded -= OnMessageAdded;
        _controller.HighlightsUpdated -= OnHighlightsUpdated;
        _controller.FilterableChannelsChanged -= OnFilterableChannelsChanged;
        _config.UnsubValueChanged(CCVars.ChatLegacyMode, OnLegacyModeCvarChanged);
        _config.UnsubValueChanged(CCVars.ChatColorWholeMessage, OnColorWholeMessageCvarChanged);
        ChatInput.Input.OnTextEntered -= OnTextEntered;
        ChatInput.Input.OnKeyBindDown -= OnInputKeyBindDown;
        ChatInput.Input.OnTextChanged -= OnTextChanged;
        ChatInput.Input.OnFocusEnter -= OnFocusEnter;
        ChatInput.Input.OnFocusExit -= OnFocusExit;
        ChatInput.ChannelSelector.OnChannelSelect -= OnChannelSelect;
        ChatInput.FilterButton.Popup.OnChannelFilter -= OnChannelFilter;
        ChatInput.FilterButton.Popup.OnNewHighlights -= OnNewHighlights;
        ChatInput.FilterButton.Popup.OnTabSelected -= OnSettingsTabSelected;
        ChatInput.FilterButton.Popup.OnTabAdded -= OnSettingsTabAdded;
        ChatInput.FilterButton.Popup.OnTabRemoved -= OnSettingsTabRemoved;
        ChatInput.FilterButton.Popup.OnTabRenamed -= OnSettingsTabRenamed;
        ChatInput.FilterButton.Popup.OnTabMoved -= OnSettingsTabMoved;
        ChatInput.FilterButton.Popup.OnRadioFilter -= OnSettingsRadioFilter;
        ChatInput.FilterButton.Popup.OnStyleChanged -= OnSettingsStyleChanged;
        ChatInput.FilterButton.Popup.OnStyleReset -= OnSettingsStyleReset;
        ChatInput.FilterButton.Popup.OnColorWholeMessageChanged -= OnSettingsColorWholeMessageChanged;
        ChatInput.FilterButton.Popup.OnLegacyModeChanged -= OnSettingsLegacyModeChanged;
        SplitButton.Popup.OnTabSelected -= OnSplitTabSelected;
        TabOverflowButton.Popup.OnTabSelected -= OnOverflowTabSelected;
        SecondaryResizeHandle.OnDragged -= OnSplitResizeDragged;
        SecondaryResizeHandle.OnDragEnded -= OnSplitResizeEnded;
    }
}
