- type: job
  abstract: true
  parent: CMJobBase
  id: AU14Jobk9handlerBase
  roundSide: ThirdParty
  roundForce: K9
  roundRole: K9Handler
  roundComponents:
  - type: Skills
    preset: AU14SkillPresetThirdPartyK9Handler
  - type: JobPrefix
    prefix: au14-job-prefix-3rdpartyk9handler
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth

  name: au14-job-name-3rdparty9handler
  description: au14-job-description-3rdpartyk9handler
  icon: "AU14JobIconGovK9Handler"
  startingGear: AU14GearThirdPartyK9Handler
  playTimeTracker: AU14JobThirdPartyK9Handler
  basePlaytimeTracker: true
  supervisors: au14-job-supervisors-loner-k9
  spawnMenuRoleName: au14-job-name-3rdparty9handler
  overwatchRoleName: au14-job-prefix-3rdpartyk9handler
  overwatchSortPriority: -2
  accessGroups:
    - Colonist
    - aumed
  setPreference: false
  hidden: true

- type: job
  parent: AU14Jobk9handlerBase
  id: AU14JobThirdPartyK9Handler
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMCRankStaffSergeant:
      entity: AU14ChevronUSCMStaffSergeant
      requirements: []
- type: playTimeTracker
  id: AU14JobThirdPartyK9Handler
  isHumanoid: true

- type: startingGear
  id: AU14GearThirdPartyK9Handler
  equipment:
    jumpsuit: AU14UniversalBlackFatigues
    id: AU14IDCardSquadK9Handler
    ears: AU14ColonyAdminHeadset
    eyes: RMCGlassesMedicalHUDGlasses
    outerClothing: AU14WYPPOArmor
    shoes: CMBootsBlack
    ears2: RMCM5CameraGear
    head: ArmorHelmetPMCFieldOfficer
    neck: RMCWhistle
    gloves: AU14PVEHandsInsulatedBlackMarine
    belt: RMCM1984BeltFilled
    pocket1: RMCPouchMedkitPMCFilled
    pocket2: AU14PouchAutoinjectorFilledMilitaryDoctor
    back: CMBackpackMedical
    mask: CMTarbackCigar
  storage:
    back:
    - CMBurnKit10
    - CMBurnKit10
    - CMTraumaKit10
    - CMTraumaKit10
    - CMPillCanisterBicaridine
    - CMPillCanisterKelotane
    - CMPillCanisterDexalin
    - CMPillCanisterDylovene
    - CMPillCanisterInaprovaline
    - CMPillCanisterTricordrazine
    - RMCPillCanisterIron
    - AU14IVFoldableFolded
    - CMDefibrillator
    - RMCRadioHandheldColonyOff
  inhand:
  - RMCZippo

- type: entity
  id: AU14SkillPresetThirdPartyK9Handler
  name: Hospital Corpsman
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillJtac: 1
      RMCSkillFirearms: 1
      RMCSkillCqc: 2
      RMCSkillMeleeWeapons: 1
      RMCSkillEndurance: 1
      RMCSkillMedical: 3
      RMCSkillSurgery: 3
      RMCSkillEngineer: 2
      RMCSkillConstruction: 3
      RMCSkillVehicles: 1
      RMCSkillPilot: 1
      RMCSkillNavigations: 1
      RMCSkillFireman: 4

- type: jobIcon
  parent: CMJobIconBase
  id: AU14JobIconGovK9Handler
  icon:
    sprite: _AU14/Interface/au14govforjobicons.rsi
    state: govfor_k9handler

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORK9Handler
  name: (DO NOT MAP) Spawn Point GOVFOR K9 Handler
  components:
  - type: SpawnPoint
    job_id: AU14JobThirdPartyK9Handler
  - type: Sprite
    state: syn_spawn

- type: job
  parent: AU14JobThirdPartyK9Handler
  id: AU14JobOPFORk9handler # Deprecated (K9 is neutral 3rd party)
  icon: "AU14JobIconOPFORK9Handler"
  spawnMenuRoleName: K9 Handler (OPFOR)
- type: jobIcon
  parent: CMJobIconBase
  id: AU14JobIconOPFORK9Handler
  icon:
    sprite: _AU14/Interface/au14opforjobicons.rsi
    state: k9handler

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointOPFORK9Handler
  name: (DO NOT MAP) Spawn Point OPFOR K9 Handler
  components:
  - type: SpawnPoint
    job_id: AU14JobOPFORk9handler
  - type: Sprite
    state: syn_spawn
