using System.Numerics;
using Content.Client._CMU14.Medical.UI;
using Content.Client.Message;
using Content.Shared._CMU14.Medical.Wounds;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client._CMU14.Medical.Examine;

[GenerateTypedNameReferences]
public sealed partial class CMUInspectInjuriesWindow : DefaultWindow
{
    private const string RememberedSizeKey = "cmu-inspect-injuries";
    private static readonly Vector2 PreferredWindowSize = new(400f, 340f);
    private static readonly Vector2 MinimumWindowSize = new(320f, 240f);

    public CMUInspectInjuriesWindow()
    {
        RobustXamlLoader.Load(this);

        SetSize = CMUMedicalWindowSizing.GetInitialSize(RememberedSizeKey, PreferredWindowSize);
        CMUMedicalWindowSizing.FitToScreen(this, PreferredWindowSize, MinimumWindowSize);
    }

    public void SetReport(string targetName, string markup, ExternalBleedTier bleeding)
    {
        Title = Loc.GetString("cmu-medical-detailed-examine-window-title", ("target", targetName));
        PatientLabel.Text = targetName;
        BleedingBox.Visible = bleeding != ExternalBleedTier.None;
        BleedingLabel.Text = Loc.GetString(
            "cmu-medical-detailed-examine-window-bleeding",
            ("tier", DescribeBleeding(bleeding)));
        BleedingLabel.ModulateSelfOverride = BleedingColor(bleeding);
        InjuryText.SetMarkupPermissive(markup);
        InjuryScroll.SetScrollValue(Vector2.Zero);
    }

    private static string DescribeBleeding(ExternalBleedTier bleeding) => bleeding switch
    {
        ExternalBleedTier.Minor => "Minor",
        ExternalBleedTier.Moderate => "Moderate",
        ExternalBleedTier.Severe => "Severe",
        ExternalBleedTier.Arterial => "Arterial",
        _ => "None",
    };

    private static Color BleedingColor(ExternalBleedTier bleeding) => bleeding switch
    {
        ExternalBleedTier.Minor => Color.FromHex("#FFB3B3"),
        ExternalBleedTier.Moderate => Color.FromHex("#FF8E8E"),
        ExternalBleedTier.Severe => Color.FromHex("#FF6868"),
        ExternalBleedTier.Arterial => Color.FromHex("#FF4D4D"),
        _ => Color.FromHex("#B7B0A5"),
    };

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        CMUMedicalWindowSizing.FitToScreen(this, PreferredWindowSize, MinimumWindowSize);
        CMUMedicalWindowSizing.RememberSize(RememberedSizeKey, this);
    }
}
