using Content.Client.Administration.Managers;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Options.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class OptionsMenu : DefaultWindow
    {
        [Dependency] private IClientAdminManager _adminManager = default!;
        [Dependency] private IConfigurationManager _cfg = default!;
        [Dependency] private IStylesheetManager _stylesheetManager = default!;

        public OptionsMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            ApplyCrtPalette();

            Tabs.SetTabTitle(0, Loc.GetString("ui-options-tab-misc"));
            Tabs.SetTabTitle(1, Loc.GetString("ui-options-tab-graphics"));
            Tabs.SetTabTitle(2, Loc.GetString("ui-options-tab-controls"));
            Tabs.SetTabTitle(3, Loc.GetString("ui-options-tab-audio"));
            Tabs.SetTabTitle(4, Loc.GetString("rmc-ui-options-tab-voicelines")); // RMC14
            Tabs.SetTabTitle(5, Loc.GetString("ui-options-tab-accessibility"));
            Tabs.SetTabTitle(6, Loc.GetString("ui-options-tab-cmu"));
            Tabs.SetTabTitle(7, Loc.GetString("ui-options-tab-admin"));

            CmuTab.CrtUiPreviewChanged += OnCrtUiPreviewChanged;
            OnClose += ResetCrtUiPreview;
            UpdateTabs();
            _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
        }

        [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
            CmuTab.CrtUiPreviewChanged -= OnCrtUiPreviewChanged;
            OnClose -= ResetCrtUiPreview;
            ResetCrtUiPreview();
        }

        private void OnCrtUiEnabledChanged(bool _)
        {
            ApplyCrtPalette();
        }

        private void OnCrtUiColorChanged(string _)
        {
            ApplyCrtPalette();
        }

        private void OnCrtUiPreviewChanged(bool enabled, string color)
        {
            _stylesheetManager.PreviewCrtUi(enabled, color);
            ApplyCrtPalette();
        }

        private void ResetCrtUiPreview()
        {
            _stylesheetManager.ResetCrtUiPreview();
        }

        private void ApplyCrtPalette()
        {
            Stylesheet = _stylesheetManager.SheetNano;
            CrtLobbyTheme.ApplyWindow(this, useCrtTypography: false);
        }

        public void UpdateTabs()
        {
            var isAdmin = _adminManager.IsAdmin(true);
            Tabs.SetTabVisible(7, isAdmin);

            GraphicsTab.Control.ReloadValues();
            MiscTab.Control.ReloadValues();
            CmuTab.Control.ReloadValues();
            AccessibilityTab.Control.ReloadValues();
            AudioTab.Control.ReloadValues();
            VoicelinesTab.Control.ReloadValues();
            AdminOptionsTab.Control.ReloadValues();
        }
    }
}
