- type: job
  parent: CMJobBase
  id: AU14IASFPilotBase
  roundSide: ThirdParty
  roundForce: TWE
  roundRole: AU14IASFPilotBase
  roundComponents:
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: rmc_marksman
  - type: AssignSquad
    whitelist:
      tags:
      - AU14SquadIASF
  - type: Skills
    preset: AU14SkillPresetPlatoonDP
  - type: JobPrefix
    prefix: au14-job-prefix-tweiasf-pl
  - type: Language
    spokenLanguages:
    - English
    - Japanese
    - Indonesian
    understoodLanguages:
    - English
    - Japanese
    - Indonesian
    currentLanguage: Indonesian
    defaultLanguage: Indonesian

  name: au14-job-name-tweiasf-pl
  playTimeTracker: AU14IASFPilot
  description: au14-job-description-twepara
  ranks:
    RMCRankCivilian: []
  chevrons:
    IASF_SecondWarrantOfficer:
      entity: AU14ChevronIASFSecondWarrantOfficer
      requirements: []
  spawnMenuRoleName: IASF Pilot (Base)
  joinNotifyCrew: false
  icon: RMCJobIconParaPilot
  supervisors: au14-job-name-tweiasf-co
  hidden: true

- type: startingGear
  id: AU14RMCGearIASFPilot
  equipment:
    head: RMCHeadRoyalFlightHelmet
    jumpsuit: AU14JumpsuitIASFL90A2
    gloves: RMCHandsVeteranRoyalMarine
    outerClothing: RMCArmorParaVest
    suitstorage: AU14WeaponSMGL90A2oldnoattachments
    shoes: RMCBootsRoyalFilled
    ears: RMCHeadsetPara
    belt: RMCBeltHolsterPistolFilledL54
    pocket1: AU14PouchIFAKFill 
    pocket2: AU14IASFPouchMagazineL90A2
    back: RMCSatchelLightpackFilledPara
    id: AU14IDCardIASFPilot
  storage:
    outerClothing:
    - RMCFlashlight

- type: playTimeTracker
  id: AU14IASFPilot
