- type: job
  parent: CMJobBase
  abstract: true
  id: AU14JobWYGuardBase
  name: au14-job-name-wyguard
  description: au14-job-description-wyguard
  playTimeTracker: AU14JobWYGuard
  basePlaytimeTracker: true

- type: job
  parent: AU14JobWYGuardBase
  id: AU14JobWYGuard
  roundSide: Civilian
  roundForce: WY
  roundRole: WYGuard
  roundComponents:
  - type: Skills
    skills:
      RMCSkillOverwatch: 1
      RMCSkillFirearms: 2
      RMCSkillCqc: 2
      RMCSkillEndurance: 2
      RMCSkillFireman: 2
      RMCSkillEngineer: 1
      RMCSkillIntel: 1
      RMCSkillVehicles: 1
      RMCSkillPolice: 2
  - type: JobPrefix
    prefix: au14-job-prefix-wyguard
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/cm_job_icons.rsi
      state: weya_goon_standard
  - type: AssignSquad
    whitelist:
      tags:
      - SquadPMC

  name: au14-job-name-wyguard
  description: au14-job-description-wyguard
  setPreference: true
  ranks:
    AU14RankWYSecurityOfficerChief:
    - !type:RoleTimeRequirement
      role: AU14JobWYGuard
      time: 360000 # 100 hours
    AU14RankWYSecurityOfficerMaster:
    - !type:RoleTimeRequirement
      role: AU14JobWYGuard
      time: 180000 # 50 hours
    AU14RankWYSecurityOfficerSenior:
    - !type:RoleTimeRequirement
      role: AU14JobWYGuard
      time: 86400 # 24 hours
    AU14RankWYSecurityOfficer:
    - !type:RoleTimeRequirement
      role: AU14JobWYGuard
      time: 36000 # 10 hours
    AU14RankWYSecurityOfficerJunior: []
  startingGear: AU14GearWYGuard
  icon: "RMCJobIconPMCGoonStandard"
  requireAdminNotify: false
  requirements:
  - !type:AgeRequirement
    requiredAge: 21
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-wy
  spawnMenuRoleName: WY Corporate Goon (CMU)
  accessGroups:
  - auwy
  - AUPrisonStaff
  roleWeight: 0.25

- type: startingGear
  id: AU14GearWYGuard
  equipment:
    id: AU14IDCardColonyCorporateLiaison
    outerClothing: CMUArmorM4PMCCorporate
    jumpsuit: AU14WYSecurityUniformRig
    shoes: RMCBootsPMCFilled
    head: AU14CivBallCapBlack
    belt: RMCBeltSecurityWeYaFilled
    back: RMCSatchelLightpackBlack
    ears: AU14ColonyWeylandHeadset
    ears2: RMCM5CameraGear
    suitstorage: RMCM77BeltPMCFilled

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointWYGuard
  name: Spawn Point WY guard
  components:
  - type: SpawnPoint
    job_id: AU14JobWYGuard
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobWYGuard
  isHumanoid: true

- type: roleLoadout
  id: JobAU14JobWYGuard
  points: 7
  groups:
  - PaperworkRMC
  - WYGuardJumpsuitAU14
  - WYGuardLeftPouchAU14
  - WYGuardRightPouchAU14
  - WYGuardHeadwearAU14
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
