- type: job
  parent: CMJobBase
  id: AU14JobCivilianPrisoner
  roundSide: Civilian
  roundForce: COLONY
  roundRole: CivilianPrisoner
  roundComponents:
  - type: Skills
    skills:
      RMCSkillFireman: 1
      RMCSkillVehicles: 1
      RMCSkillDomestics: 1
      RMCSkillFirearms: 2
  - type: JobPrefix
    prefix: au14-job-prefix-civilianprisoner
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14colonyjobicons.rsi
      state: prisoner

  name: au14-job-name-civilianprisoner
  description: au14-job-description-civilianprisoner
  setPreference: true
  playTimeTracker: AU14JobCivilianPrisoner
  startingGear: AU14GearCivilianPrisoner
  ranks:
    RMCRankCivilian: []
  icon: "AU14JobIconColonyPrisoner"
  hasIcon: false
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-loner
  spawnMenuRoleName: Colony Prisoner (CMU)
  roleWeight: 0.6

- type: startingGear
  id: AU14GearCivilianPrisoner
  equipment:
    jumpsuit: AU14CivilianPrisonJumpsuit
    shoes: RMCShoesBlack

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianPrisoner
  name: Spawn Point Civilian Prisoner
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianPrisoner
  - type: Sprite
    state: syn_spawn

- type: entity
  parent: MarkerBase
  id: auprisonerghost
  name: Prisoner colonist ghost role
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: aughostprisoner

- type: randomHumanoidSettings
  parent: RMCSettingsGhostRole
  id: aughostprisoner
  components:
  - type: RMCJobSpawner
    job: AU14JobCivilianPrisoner

- type: playTimeTracker
  id: AU14JobCivilianPrisoner
  isHumanoid: true
