- type: job
  parent: CMJobBase
  id: AU14JobCivilianFreightSystemsSpecialist
  roundSide: Civilian
  roundForce: COLONY
  roundRole: CivilianFreightSystemsSpecialist
  roundComponents:
  - type: Skills
    skills:
      RMCSkillFireman: 1
      RMCSkillVehicles: 1
      RMCSkillFirearms: 2
      RMCSkillDomestics: 1
      RMCSkillEngineer: 2
      RMCSkillConstruction: 2
      RMCSkillPowerLoader: 2
  - type: JobPrefix
    prefix: au14-job-prefix-freightsystemsspecialist
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14colonyjobicons.rsi
      state: fss

  name: au14-job-name-civilianfreightsystemsspecialist
  description: au14-job-description-civilianfreightsystemsspecialist
  setPreference: true
  canBeAntag: false
  playTimeTracker: AU14JobCivilianFreightSystemsSpecialist
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCivilianFreightSystemsSpecialist
  icon: "AU14JobIconCivilianFreightSystemsSpecialist"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonyadministrator
  accessGroups:
  - Colonist
  - auengi
  - CMCargoTech
  - AUPrisonStaff
  roleWeight: 0.25

- type: startingGear
  id: AU14GearCivilianFreightSystemsSpecialist
  equipment:
    head: RMCHardhatOrange
    jumpsuit: AU14CivilianBoilerSuitCyan
    outerClothing: RMCHazardVest
    shoes: RMCBootsCorporate
    id: AU14IDCardColonyFreightSystemsSpecialist
  inhand:
  - CMStampApproved

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianFreightSystemsSpecialist
  name: Spawn Point Freight Systems Specialist
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianFreightSystemsSpecialist
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianFreightSystemsSpecialist
  isHumanoid: true

- type: roleLoadout
  id: JobAU14JobCivilianFreightSystemsSpecialist
  points: 7
  groups:
  - EngiSatchelAU14
  - EngiJacketAU14
  - EngiGlovesAU14
  - EngiBeltAU14
  - EngiPouchAU14
  - EngiPouchRightAU14
  - ForceStampApprovedAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
