- type: job
  parent: CMJobBase
  id: AU14JobCivilianUSASFRecruiter
  roundSide: Civilian
  roundForce: COLONY
  roundRole: CivilianUSASFRecruiter
  roundComponents:
  - type: Skills
    skills:
      RMCSkillCqc: 1
      RMCSkillEndurance: 1
      RMCSkillVehicles: 1
      RMCSkillPowerLoader: 1
      RMCSkillFirearms: 2
      RMCSkillFireman: 1
      RMCSkillJtac: 3
  - type: JobPrefix
    prefix: au14-job-prefix-usasfrecruiter
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14colonyjobicons.rsi
      state: advisor
  name: au14-job-name-usasfrecruiter
  description: au14-job-description-usasfrecruiter
  setPreference: true
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
  playTimeTracker: AU14JobCivilianUSASFRecruiter
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCivilianUSASFRecruiter
  icon: "AU14JobIconColonyAdvisor"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  accessGroups:
  - Colonist
  roleWeight: 0.25

- type: startingGear
  id: AU14GearCivilianUSASFRecruiter
  equipment:
    shoes: RMCBootsCorporate
    pocket1: AU14StampRecruiter

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianUSASFRecruiter
  name: Spawn Point USASF Recruiter LV624 SPECIFIC
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianUSASFRecruiter
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianUSASFRecruiter
  isHumanoid: true

- type: roleLoadout
  id: JobAU14JobCivilianUSASFRecruiter
  points: 7
  groups:
  - CivSatchelAU14
  - RecruiterSpecializationAU14
  - RecruiterHatsAU14
  - RecruiterJumpsuitAU14
  - RecruiterPatchesAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

# ├──[ corporate ]───────────────────────────────────────────────────┤
