- type: job
  parent: AU14JobWYGuardBase
  id: AU14JobWYHTGoon
  roundSide: ThirdParty
  roundForce: WY
  roundRole: WYHTGoon
  roundComponents:
  - type: NpcFactionMember
    factions:
    - AUWeYu
  - type: Skills
    skills:
      RMCSkillCqc: 2
      RMCSkillEndurance: 2
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillIntel: 1
      RMCSkillOverwatch: 1
      RMCSkillPolice: 2
      RMCSkillVehicles: 1
  - type: JobPrefix
    prefix: au14-job-prefix-wyguard
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth
  - type: AssignSquad
    whitelist:
      tags:
      - SquadPMC

  name: au14-job-name-wyguard
  description: au14-wyht-description
  ranks:
    AU14RankWYSecurityOfficer: []
  spawnMenuRoleName: WY HT Goon (3rd party)
  startingGear: AU14GearWYHTGoon
  greeting: au14-wyht-greeting
  icon: "RMCJobIconPMCGoonStandard"
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-wy
  accessGroups:
  - auwy
  - AUPrisonStaff
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicWeYu
  id: AU14JobWYHTGoon
  name: WY Hazard Transport Goon (3rd party)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: SquadPMC
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: au14-job-name-wyguard
    description: au14-wyht-description
    reregister: false
    job: AU14JobWYHTGoon
    raffle:
      settings: short
    rules: au14-wyht-description

- type: startingGear
  id: AU14GearWYHTGoon
  equipment:
    id: AU14IDCardColonyCorporateLiaison
    outerClothing: CMArmorM4PMCCorporateLead
    jumpsuit: AU14JumpsuitVeteranPMCCorporate
    shoes: RMCBootsPMCFilled
    head: RMCArmorHelmetPMCBlack
    gloves: AU14PVEHandsInsulatedBlackMarine
    belt: RMCM77BeltPMCFilled
    pocket1: RMCPouchMagazineLargePMC
    pocket2: AU14PouchIFAKFill
    back: RMCSatchelLightpackWeYa
    eyes: CMGlassesSecurity
    ears: RMCHeadsetDistressWeYa
    suitstorage: AU14WeaponRifleF44AALock
  storage:
    pocket1:
    - AU14MagazineRifleF44AA
    - AU14MagazineRifleF44AA
    - AU14MagazineRifleF44AA
    - AU14MagazineRifleF44AA
    back:
    - AU14CBRNKitWeYu
    - RMCMREWeYa
    - CMCanteen
    - RMCHandcuffs
    - RMCHandcuffs
    - RMCHandcuffs
    - AU14TeleBaton
    - CMFlash
