- type: job
  parent: AU14JobCivilianCorporateLiaisonBase
  id: AU14JobWYHTCorporateLiaison
  roundSide: ThirdParty
  roundForce: WY
  roundRole: WYHTCorporateLiaison
  roundComponents:
  - type: NpcFactionMember
    factions:
    - AUWeYu
  - type: Skills
    skills:
      RMCSkillFireman: 1
      RMCSkillVehicles: 1
      RMCSkillDomestics: 1
      RMCSkillFirearms: 1
      RMCSkillIntel: 1
      RMCSkillOverwatch: 1
  - type: CMVendorUser
    id: AU14JobCivilianCorporateLiaison
    points: 70
  - type: JobPrefix
    prefix: au14-job-prefix-corporateliaison
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth
  - type: AssignSquad
    whitelist:
      tags:
      - SquadPMC

  name: au14-job-name-civiliancorporateliaison
  description: au14-wyht-description
  ranks:
    RMCRankWeYaAssistantManager:
    - !type:RoleTimeRequirement
      role: AU14JobCivilianCorporateLiaison
      time: 360000 # 100 hours
    RMCRankWeYaExecutiveSupervisor:
    - !type:RoleTimeRequirement
      role: AU14JobCivilianCorporateLiaison
      time: 270000 # 75 hours
    RMCRankWeYaExecutiveSpecialist:
    - !type:RoleTimeRequirement
      role: AU14JobCivilianCorporateLiaison
      time: 180000 # 50 hours
    RMCRankWeYaSeniorExecutive: []
  spawnMenuRoleName: WY HT Liaison (3rd party)
  startingGear: AU14GearWYHTLiaison
  greeting: au14-wyht-greeting
  icon: "CMJobIconLiaison"
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-wy
  accessGroups:
  - Colonist
  - auadmin
  - AUPrisonStaff
  - auwy
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicWeYu
  id: AU14JobWYHTLiaison
  name: WY Hazard Transport Liaison (3rd party)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: SquadPMC
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: au14-job-name-civiliancorporateliaison
    description: au14-wyht-description
    reregister: false
    job: AU14JobWYHTCorporateLiaison
    raffle:
      settings: short
    rules: au14-wyht-description

- type: startingGear
  id: AU14GearWYHTLiaison
  equipment:
    id: AU14IDCardColonyCorporateLiaison
    outerClothing: RMCFancySuitJacketBrown
    jumpsuit: CMJumpsuitLiaison
    shoes: RMCShoesFancyLeather
    back: CMSatchel
    eyes: CMGlassesSecurity
    ears: RMCHeadsetDistressWeYa
  inhand:
  - RMCPortableVendorCorporate
  storage:
    back:
    - AU14CBRNKitWeYu
