- type: department
  parent: CMDepartmentBase
  id: AU14DepartmentOpfor
  name: au14-department-opfor
  description: au14-department-opfor-description
  color: "#9e1a0b"
  faction: opfor
  roles:
  - AU14JobOPFORPlatCo
  - AU14JobOPFORPlatOp
  - AU14JobOPFORadvisor
  - AU14JobOPFORSectionSergeant
  - AU14JobOPFORSquadSergeant
# - AU14JobOPFORWeaponsSpecialist
  - AU14JobOPFORRadioTelephoneOperator
  - AU14JobOPFORSquadRifleman
  - AU14JobOPFORSquadAutomaticRifleman
  - AU14JobOPFORSquadCombatTech
  - AU14JobOPFORVehicleCrewman
  - AU14JobOPFORPlatoonCorpsman
  - AU14JobOPFORAuxTech
  - AU14JobOPFORDSPilot
  - AU14JobOPFORDCC
  - AU14JobOPFORAuxSupportSynth
  - AU14JobOPFORWorkingJoe
  - AU14JobOPFORMilitaryDoctor
  - AU14JobOPFORMilitaryPoliceMan
  departmentRadio: null
  headOfDepartment: null
