- type: job
  parent: CMJobBase
  id: AU14JobTDRiflemanBase
  name: au-14-job-name-upptd-rifleman
  description: au14-upptd-description
  playTimeTracker: AU14JobUPPTerritorialDefenseRifleman
  basePlaytimeTracker: true
  hidden: true

- type: job
  parent: AU14JobTDRiflemanBase
  id: AU14UPPTerritorialDefenseRifleman
  roundSide: ThirdParty
  roundForce: UPP_TD
  roundRole: AU14UPPTerritorialDefenseRifleman
  roundComponents:
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: spp_pvt
  - type: Skills
    skills:
      RMCSkillEndurance: 1
      RMCSkillFirearms: 1
      RMCSkillFireman: 1
      RMCSkillMedical: 1
      RMCSkillVehicles: 1
  - type: JobPrefix
    prefix: au-14-job-prefix-upptd-rifleman
  - type: Language
    spokenLanguages:
    - Polish
    - Czech
    - Slovak
    - Ukrainian
    - Romanian
    - Hungarian
    - Lithuanian
    understoodLanguages:
    - Polish
    - Czech
    - Slovak
    - Ukrainian
    - Romanian
    - Hungarian
    - Lithuanian
    currentLanguage: Ukrainian
    defaultLanguage: Ukrainian

  name: au-14-job-name-upptd-rifleman
  description: au14-upptd-description
  ranks:
    RMCRankCivilian: []
  chevrons:
    UPP_Private:
      entity: AU14ChevronUPPNIPrivate 
      requirements: []
  spawnMenuRoleName: UPP TD Rifleman (3rd party)
  startingGear: AU14GearUPPTerritorialDefenseRifleman
  greeting: au14-upptd-greeting
  icon: "CMJobIconEmpty"
  joinNotifyCrew: false
  supervisors: au-14-job-name-upptd-squadleader
  accessGroups:
  - AU14GovforSquad
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicTDThirdparty
  id: AU14JobUPPTerritorialDefenseRifleman
  name: UPP TD Rifleman
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: AU14SquadTD
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: au-14-job-name-upptd-rifleman
    description: au14-upptd-description
    reregister: false
    job: AU14UPPTerritorialDefenseRifleman
    raffle:
      settings: short
    rules: au14-upptd-description

- type: startingGear
  id: AU14GearUPPTerritorialDefenseRifleman
  equipment:
    id: AU14IDCardUPPTDRifleman
    outerClothing: AU14ArmorArmyUPP
    jumpsuit: AU14JumpsuitArmyUPP
    shoes: RMCBootsSPPBlackFilled
    head: AU14ArmorHelmetArmyUPP
    belt: AU14BeltMarineArmyUPPTDFilled
    pocket1: RMCPouchFlareFilled
    pocket2: AU14PouchIFAKFill
    back: RMCSatchelSPP
    suitstorage: RMCWeaponRifleAK4047
  storage:
    back:
    - RMCMaskGasSPP
    - RMCMRESPP
    - CMCanteen

- type: playTimeTracker
  id: AU14JobUPPTerritorialDefenseRifleman
