- type: job
  parent: AU14JobLEOBase
  id: AU14JobCivilianNSPAConstable
  roundSide: Civilian
  roundForce: NSPA
  roundRole: CivilianNSPAConstable
  roundComponents:
  - type: Skills
    skills:
      RMCSkillCqc: 2
      RMCSkillEndurance: 2
      RMCSkillFirearms: 2
      RMCSkillFireman: 2
      RMCSkillIntel: 1
      RMCSkillMedical: 1
      RMCSkillMeleeWeapons: 1
      RMCSkillOverwatch: 1
      RMCSkillPolice: 2
      RMCSkillEngineer: 1
      RMCSkillConstruction: 1
      RMCSkillVehicles: 1
  - type: JobPrefix
    prefix: au14-job-prefix-civiliannspaConstable
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/cm_job_icons.rsi
      state: tse_paconstable
  - type: Language
    preset: AU14LanguagePresetTWE

  name: au14-job-name-civiliannspaConstable
  description: au14-job-description-civiliannspaConstable
  setPreference: true
  requirements:
  - !type:AgeRequirement
    requiredAge: 21
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
    - NoEnglish
  canBeAntag: false
  ranks:
    RMCRankCivilian: []
  chevrons:
    Inspector:
      entity: AU14ChevronNSPAInspector
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobCivilianCMBDeputy
        time: 90000 # 25 hours
    SeniorConstable:
      entity: AU14ChevronNSPASeniorConstable
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobCivilianCMBDeputy
        time: 36000 # 10 hours
    Constable:
      entity: AU14ChevronNSPAConstable
      requirements: []
  startingGear: AU14GearCivilianNSPAConstable
  icon: "RMCJobIconTSEPAConstable"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  spawnMenuRoleName: NSPA Constable (CMU)
  accessGroups:
  - aucmb
  - Colonist
  roleWeight: 0.25

- type: startingGear
  id: AU14GearCivilianNSPAConstable
  equipment:
    head: RMCHeadCapTSEPAPeaked
    back: RMCSatchelTSEPA
    jumpsuit: RMCJumpsuitTSEPA
    belt: CMBeltSecurityMarshalFilled
    shoes: RMCBootsPMCFilled
    id: AU14IDCardCivilianNSPAConstable
    ears: AU14CMBHeadset
    outerClothing: RMCArmorVestTSEPA
    suitstorage: AU14BeltHolsterPistolBlack
    pocket1: AU14PouchIFAKFill
    pocket2: AU14PouchGeneralLargeLEOFilled
  inhand:
  - AU14GunCasePistolL45
  storage:
    back:
    - AU14GuidebookLawColonial

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCiviliannspaConstable
  name: Spawn Point Civilian nspa Constable
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianNSPAConstable
  - type: Sprite
    state: syn_spawn
