- type: job
  parent: AU14JobLEOBase
  id: AU14JobCivilianCMBDeputy
  roundSide: Civilian
  roundForce: CMB
  roundRole: CivilianCMBDeputy
  roundComponents:
  - type: Skills
    skills:
      RMCSkillCqc: 3
      RMCSkillEndurance: 3
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillIntel: 1
      RMCSkillMedical: 1
      RMCSkillMeleeWeapons: 1
      RMCSkillOverwatch: 1
      RMCSkillPolice: 2
      RMCSkillVehicles: 1
  - type: JobPrefix
    prefix: au14-job-prefix-cmbdeputy
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/cm_job_icons.rsi
      state: cmb_dep

  name: au14-job-name-civiliancmbdeputy
  description: au14-job-description-civiliancmbdeputy
  setPreference: false
  canBeAntag: false
  requirements:
  - !type:AgeRequirement
    requiredAge: 21
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
    - NoEnglish
  ranks:
    RMCRankCivilian: []
  chevrons:
    SrDeputy:
      entity: AU14ChevronCMBSrDeputy
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobCivilianCMBDeputy
        time: 72000 # 20 hours
    Deputy:
      entity: AU14ChevronCMBDeputy
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobCivilianCMBDeputy
        time: 7200 # 2 hours
    ProbDeputy:
      entity: AU14ChevronCMBProbDeputy
      requirements: []
  startingGear: AU14GearCivilianCMBDeputy
  icon: "RMCJobIconBureauDeputy"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  spawnMenuRoleName: CMB Deputy (CMU)
  accessGroups:
  - aucmb
  - Colonist
  - AUPrisonStaff
  roleWeight: 0.25

- type: startingGear
  id: AU14GearCivilianCMBDeputy
  equipment:
    head: RMCHeadCapBureau
    jumpsuit: AU14CMBUniform
    back: CMSatchelSecurity
    belt: CMBeltSecurityMarshalFilled
    shoes: RMCBootsPMCFilled
    id: AU14IDCardColonyCMBDeputy
    ears: AU14CMBHeadset
    outerClothing: RMCCoatSnowSurvivorCMBDeputy
    suitstorage: AU14BeltHolsterPistolBlack
    pocket1: AU14PouchIFAKFill
    pocket2: AU14PouchGeneralLargeLEOFilled
  inhand:
  - RMCGunCasePistolM1984
  storage:
    back:
    - AU14GuidebookLawColonial

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianCMBDeputy
  name: Spawn Point Civilian CMB Deputy
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianCMBDeputy
  - type: Sprite
    state: syn_spawn
