- type: job
  parent: AU14JobLEOBase
  id: AU14JobCivilianColonySecurityOfficer
  roundSide: Civilian
  roundForce: COLONY_SECURITY
  roundRole: CivilianColonySecurityOfficer
  roundComponents:
  - type: Skills
    skills:
      RMCSkillCqc: 3
      RMCSkillEndurance: 3
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillIntel: 1
      RMCSkillMedical: 1
      RMCSkillMeleeWeapons: 1
      RMCSkillOverwatch: 1
      RMCSkillPolice: 2
      RMCSkillVehicles: 1
  - type: AssignSquad
    whitelist:
      tags:
      - SquadPMC
  - type: JobPrefix
    prefix: au14-job-prefix-colonysecurityofficer
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/cm_job_icons.rsi
      state: weya_goon_standard

  name: au14-job-name-colonysecurityofficer
  description: au14-job-description-colonysecurityofficer
  setPreference: false
  canBeAntag: false
  startingGear: AU14GearColonySecurityOfficer
  icon: "RMCJobIconPMCGoonStandard"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  spawnMenuRoleName: Colony Security Officer (CMU)
  accessGroups:
  - aucmb
  - auwy
  - Colonist
  - AUPrisonStaff
  access:
  - AU14AccessColonyMarshall
  roleWeight: 0.25

- type: startingGear
  id: AU14GearColonySecurityOfficer
  equipment:
    head: RMCHeadCapBureau
    back: CMSatchelSecurity
    jumpsuit: AU14CMBUniform
    belt: CMBeltSecurityMarshalFilled
    shoes: RMCBootsPMCFilled
    id: AU14IDCardColonyCMBDeputy
    ears: AU14ColonySecurityHeadset
    outerClothing: RMCCoatSnowSurvivorCMBDeputy
    suitstorage: AU14BeltHolsterPistolBlack
    pocket1: AU14PouchIFAKFill
    pocket2: AU14PouchGeneralLargeLEOFilled
  inhand:
  - RMCGunCasePistolM1984
  storage:
    back:
    - AU14GuidebookLawColonial

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointColonySecurityOfficer
  name: Spawn Point Colony Security Officer
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianColonySecurityOfficer
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianColonySecurityOfficer
  isHumanoid: true

# ── Colony Security Leader ──────────────────────────────────────────────────
