- type: job
  parent: AU14JobLEOBase
  id: AU14JobCivilianColonySecurityLeader
  roundSide: Civilian
  roundForce: COLONY_SECURITY
  roundRole: CivilianColonySecurityLeader
  roundComponents:
  - type: Skills
    skills:
      RMCSkillCqc: 3
      RMCSkillEndurance: 3
      RMCSkillFirearms: 2
      RMCSkillFireman: 5
      RMCSkillIntel: 1
      RMCSkillMedical: 2
      RMCSkillMeleeWeapons: 1
      RMCSkillOverwatch: 1
      RMCSkillPolice: 2
      RMCSkillLeadership: 3
      RMCSkillJtac: 3
      RMCSkillEngineer: 2
      RMCSkillConstruction: 2
      RMCSkillVehicles: 1
  - type: JobPrefix
    prefix: au14-job-prefix-colonysecurityleader
  - type: AssignSquad
    whitelist:
      tags:
      - SquadPMC
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth
  name: au14-job-name-colonysecurityleader
  description: au14-job-description-colonysecurityleader
  setPreference: false
  canBeAntag: false
  startingGear: AU14GearColonySecurityLeader
  icon: "RMCJobIconPMCGoonStandard"
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  spawnMenuRoleName: Colony Security Leader (CMU)
  accessGroups:
  - aucmb
  - auwy
  - Colonist
  - AUPrisonStaff
  - auadmin
  access:
  - AU14AccessColonyMarshall
  - AU14AccessColonyAdministrator
  roleWeight: 0.25

- type: startingGear
  id: AU14GearColonySecurityLeader
  equipment:
    head: RMCHeadCapBureau
    jumpsuit: AU14CMBUniform
    back: CMSatchelSecurity
    belt: CMBeltSecurityMarshalFilled
    shoes: RMCBootsPMCFilled
    id: AU14IDCardColonyCMBMarshal
    ears: AU14ColonySecurityHeadset
    outerClothing: RMCCoatSnowSurvivorCMBDeputy
    suitstorage: AU14BeltHolsterPistolBlack
    pocket1: AU14PouchIFAKFill
    pocket2: AU14PouchGeneralLargeLEOFilled
  inhand:
  - RMCGunCasePistolM1984
  storage:
    back:
    - AU14GuidebookLawColonial

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointColonySecurityLeader
  name: Spawn Point Colony Security Leader
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianColonySecurityLeader
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianColonySecurityLeader
  isHumanoid: true
