using System;
using System.Numerics;
using Content.Client._CMU14.Medical.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RMC14.Medical.Scanner;

[GenerateTypedNameReferences]
public sealed partial class HealthScannerWindow : DefaultWindow
{
    private const string RememberedSizeKey = "cmu-health-scanner";
    private static readonly Vector2 PreferredWindowSize = new(860f, 820f);
    private static readonly Vector2 MinimumWindowSize = new(520f, 420f);
    private static readonly TimeSpan ServerLoadingPulse = TimeSpan.FromSeconds(0.4);

    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IResourceCache _resourceCache = default!;
    private readonly CMUMedicalUniformScaler _uniformScaler = new();

    private TimeSpan _loadingStart;
    private TimeSpan _loadingEnd;
    public float LayoutScale { get; private set; } = 1f;

    public HealthScannerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        SetSize = CMUMedicalWindowSizing.GetInitialSize(RememberedSizeKey, PreferredWindowSize);
        CMUMedicalWindowSizing.FitToScreen(this, PreferredWindowSize, MinimumWindowSize);
        ApplyUniformScale(true);
    }

    public void ShowServerLoadingPulse()
    {
        _loadingStart = _timing.CurTime;
        _loadingEnd = _loadingStart + ServerLoadingPulse;
        LoadingPanel.Visible = true;
        LoadingSpinner.Visible = true;
        LoadingSpinner.Progress = 1f;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        CMUMedicalWindowSizing.FitToScreen(this, PreferredWindowSize, MinimumWindowSize);
        ApplyUniformScale();
        CMUMedicalWindowSizing.RememberSize(RememberedSizeKey, this);

        if (!LoadingPanel.Visible)
            return;

        LoadingSpinner.FromTime(_loadingStart, _loadingEnd);

        if (_timing.CurTime >= _loadingEnd)
            LoadingPanel.Visible = false;
    }

    public void ApplyUniformScale(bool force = false)
    {
        var size = Size.X > 0f && Size.Y > 0f ? Size : SetSize;
        var scale = Math.Clamp(
            Math.Min(size.X / PreferredWindowSize.X, size.Y / PreferredWindowSize.Y),
            CMUMedicalUniformScaler.MinimumScale,
            1f);

        if (!force && Math.Abs(LayoutScale - scale) < 0.001f)
            return;

        LayoutScale = scale;
        _uniformScaler.Apply(ScaleRoot, LayoutScale, _resourceCache);
    }
}
