- type: job
  parent: CMJobBase
  id: AU14JobCivilianTimesSharesSalesman
  roundSide: ThirdParty
  roundForce: MISC
  roundRole: CivilianTimesSharesSalesman
  roundComponents:
  - type: NpcFactionMember
    factions:
    - AUBureau
  - type: Skills
    skills:
      RMCSkillFireman: 1
      RMCSkillVehicles: 1
      RMCSkillDomestics: 1
      RMCSkillFirearms: 2
  - type: JobPrefix
    prefix: au14-job-prefix-civiliancolonist
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth

  name: Timeshares Salesperson
  description: You are a timeshares salesperson sent to the frontier to sell vacation packages. You travel from colony to colony trying to convince people to buy into shared properties.
  setPreference: true
  playTimeTracker: AU14JobCivilianDeliveryPizzaBoy
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearTimeSharesSalesman
  icon: "CMJobIconEmpty"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-loner
  accessGroups:
  - Colonist
  roleWeight: 0.25
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicMisc
  id: AU14PartyJobTimeSharesSalesman
  name: Timeshares Salesperson
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: Timeshares Salesperson
    description: You are a timeshares salesperson sent to the frontier to sell vacation packages. You travel from colony to colony trying to convince people to buy into shared properties.
    job: AU14JobCivilianTimesSharesSalesman
    raffle:
      settings: short
    rules: You are a timeshares salesperson sent to the frontier to sell vacation packages. You travel from colony to colony trying to convince people to buy into shared properties.

- type: partySpawn
  id: TimeSharesSalesmanSpawn
  leadersToSpawn:
    AU14PartyJobTimeSharesSalesman: 1
  scalewithpop: false
  spawnTogether: true

- type: thirdParty
  id: TimeSharesSalesman
  partyspawn: TimeSharesSalesmanSpawn
  entrymethod: shuttle
  weight: 5
  minplayers: 30
  maxplayers: 400
  GhostsNeeded: 2
  roundstart: false

- type: startingGear
  id: AU14GearTimeSharesSalesman
  equipment:
    id: AU14IDCardTimeSharesSalesman
    outerClothing: RMCFancySuitJacketLightBrown
    jumpsuit: RMCJumpsuitWornSuit
    shoes: RMCShoesLaceupBrown
    pocket1: RMCFlashlight
    back: AU14SlingSatchelBlueTimeSharesSalesman
    head: RMCHeadFedoraBrown

- type: entity
  parent: AU14SlingSatchelBlack
  id: AU14SlingSatchelBlueTimeSharesSalesman
  suffix: Filled, Time Shares Salesman
  components:
  - type: StorageFill
    contents:
    - id: CMPen
    - id: CMPaper
    - id: CMPaper
    - id: CMPaper
    - id: CMPaper
    - id: CMPaper
    - id: CMPaper
    - id: CMPaper
    - id: CMPaper
    - id: AU14CigarettePackBalajj
    - id: RMCLighter

- type: playTimeTracker
  id: AU14JobCivilianTimesSharesSalesman
  isHumanoid: true
