- type: job
  parent: CMJobBase
  id: AU14JobRedCrossDoctor
  roundSide: ThirdParty
  roundForce: ICRC
  roundRole: RedCrossDoctor
  roundComponents:
  - type: NpcFactionMember
    factions:
    - AUBureau
  - type: Skills
    skills:
      RMCSkillFireman: 3
      RMCSkillVehicles: 1
      RMCSkillDomestics: 1
      RMCSkillMedical: 3
      RMCSkillResearch: 1
      RMCSkillSurgery: 2
      RMCSkillFirearms: 2
  - type: JobPrefix
    prefix: au14-job-prefix-physician
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth

  name: ICRC Medical Staff Doctor
  description: You are a member of the medical staff assigned to an International Committee of the Red Cross relief mission, traveling from colony to colony to provide vaccines, medical aid and humanitarian assistance. Provide care to those you encounter and help the people of the Neroid Sector.
  setPreference: true
  canBeAntag: false
  playTimeTracker: AU14JobRedCrossDoctor
  ranks:
    RMCRankCivilianDoctor: []
  startingGear: AU14GearICRCDoctorAlt
  icon: "AU14JobIconColonyICRCDoctor"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonyadministrator
  accessGroups:
  - Colonist
  - aumed
  roleWeight: 0.25
  hidden: false

- type: startingGear
  id: AU14GearICRCDoctorAlt
  equipment:
    id: AU14IDCardRedCrossDoctor
    outerClothing: RMCLabcoat
    jumpsuit: CMScrubsBlue
    shoes: RMCShoesBlack
    belt: CMUBeltMedicBagICRCDoctor
    head: CMHeadCapSurgBlue
    pocket1: AU14PouchIFAKFill
    pocket2: RMCPouchGeneralLargeBureauObserverFill
    back: RMCSatchelICBLiaisonFill
    ears: CMHeadsetColony
    ears2: RMCFlashlightPen
    neck: ClothingNeckStethoscope
    eyes: RMCGlassesMedicalHUDGlasses

- type: entity
  parent: AU14BaseMobSpeciesOrganicRedCross
  id: AU14PartyJobICRCDoctor
  name: ICRC Medical Staff Doctor
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: ICRC Medical Staff Doctor
    description: You are a member of the medical staff assigned to an International Committee of the Red Cross relief mission, traveling from colony to colony to provide vaccines, medical aid and humanitarian assistance. Provide care to those you encounter and help the people of the Neroid Sector.
    reregister: false
    job: AU14JobRedCrossDoctor
    raffle:
      settings: short
    rules: You are a member of the medical staff assigned to an International Committee of the Red Cross relief mission, traveling from colony to colony to provide vaccines, medical aid and humanitarian assistance. Provide care to those you encounter and help the people of the Neroid Sector.

- type: playTimeTracker
  id: AU14JobRedCrossDoctor
  isHumanoid: true
