- type: job
  parent: AU14JobLEOBase
  id: AU14JobInvestigationCMBDeputy
  roundSide: ThirdParty
  roundForce: CMB
  roundRole: InvestigationCMBDeputy
  roundComponents:
  - type: NpcFactionMember
    factions:
    - AUBureau
  - type: Skills
    skills:
      RMCSkillCqc: 3
      RMCSkillEndurance: 3
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillIntel: 1
      RMCSkillMedical: 1
      RMCSkillMeleeWeapons: 1
      RMCSkillOverwatch: 1
      RMCSkillPolice: 2
      RMCSkillVehicles: 1
  - type: JobPrefix
    prefix: au14-job-prefix-cmbdeputy
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth

  name: au14-job-name-civiliancmbdeputy
  description: You have been sent by the Colonial Administration to investigate unspecified occurrences on this planet. Investigate the area under the orders of your marshal and ensure that the laws of Sol extend far beyond the Solar System.
  setPreference: false
  canBeAntag: false
  requirements:
  ranks:
    RMCRankCivilian: []
  chevrons:
    Deputy:
      entity: AU14ChevronCMBDeputy
      requirements: []
  startingGear: AU14GearCMBDeputyInvestigation
  icon: "RMCJobIconBureauDeputy"
  spawnMenuRoleName: CMB Deputy (3rd party)
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  accessGroups:
  - aucmb
  - Colonist
  - AUPrisonStaff
  roleWeight: 0.25
  hidden: false

- type: startingGear
  id: AU14GearCMBDeputyInvestigation
  equipment:
    id: AU14IDCardColonyCMBDeputy
    outerClothing: AU14CMBDeputyWindbreaker
    jumpsuit: AU14CMBUniform
    shoes: RMCBootsPMCFilled
    head: RMCHeadCapBureau
    belt: AU14BeltHolsterPistolCMBHG45
    pocket1: AU14PouchPoliceEquipmentSupportSynth
    pocket2: AU14PouchIFAKFill
    back: RMCSatchelTSEPA
    ears: AU14CMBHeadsetOnlyCMB

- type: entity
  parent: AU14BaseMobSpeciesOrganicCMB
  id: CMBInvestigationPartyJobDeputy
  name: CMB Deputy
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: au14-job-name-civiliancmbdeputy
    description: You have been sent by the Colonial Administration to investigate unspecified occurrences on this planet. Investigate the area under the orders of your marshal and ensure that the laws of Sol extend far beyond the Solar System.
    reregister: false
    job: AU14JobInvestigationCMBDeputy
    raffle:
      settings: short
    rules: You have been sent by the Colonial Administration to investigate unspecified occurrences on this planet. Investigate the area under the orders of your marshal and ensure that the laws of Sol extend far beyond the Solar System.
