- type: job
  parent: AU14JobLEOLeaderBase
  id: AU14JobInvestigationCMBMarshal
  roundSide: ThirdParty
  roundForce: CMB
  roundRole: InvestigationCMBMarshal
  roundComponents:
  - type: NpcFactionMember
    factions:
    - AUBureau
  - type: Skills
    skills:
      RMCSkillCqc: 3
      RMCSkillEndurance: 3
      RMCSkillFirearms: 2
      RMCSkillFireman: 5
      RMCSkillIntel: 1
      RMCSkillMedical: 2
      RMCSkillMeleeWeapons: 1
      RMCSkillOverwatch: 1
      RMCSkillPolice: 2
      RMCSkillLeadership: 3
      RMCSkillJtac: 3
      RMCSkillEngineer: 2
      RMCSkillConstruction: 2
      RMCSkillVehicles: 1
  - type: JobPrefix
    prefix: au14-job-prefix-cmbmarshal
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth

  name: au14-job-name-civiliancmbmarshal
  description: au14-job-description-civiliancmbmarshal
  setPreference: false
  canBeAntag: false
  ranks:
    RMCRankCivilian: []
  chevrons:
    Marshal:
      entity: AU14ChevronCMBMarshal
      requirements: []
  startingGear: AU14GearCMBMarshalInvestigation
  icon: "RMCJobIconBureauMarshal"
  spawnMenuRoleName: CMB Marshal (3rd party)
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  accessGroups:
  - auadmin
  - aucmb
  - Colonist
  - AUPrisonStaff
  roleWeight: 0.25
  hidden: false

- type: startingGear
  id: AU14GearCMBMarshalInvestigation
  equipment:
    id: AU14IDCardColonyCMBMarshal
    outerClothing: AU14CMBMarshalWindbreaker
    jumpsuit: AU14CMBUniform
    shoes: RMCBootsPMCFilled
    head: RMCHeadCapBureau
    belt: RMCBeltHolsterRevolverSpearheadFill
    pocket1: AU14PouchPoliceEquipmentSupportSynth
    pocket2: AU14PouchIFAKFill
    back: RMCSatchelTSEPA
    ears: AU14CMBHeadsetOnlyCMB

- type: entity
  parent: AU14BaseMobSpeciesOrganicCMB
  id: CMBInvestigationPartyJobMarshal
  name: CMB Marshal
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: au14-job-name-civiliancmbdeputy
    description: You have been sent by the Colonial Administration to investigate unspecified occurrences on this planet. Investigate the area under the orders of your marshal and ensure that the laws of Sol extend far beyond the Solar System.
    reregister: false
    job: AU14JobInvestigationCMBMarshal
    raffle:
      settings: short
    rules: You have been sent by the Colonial Administration to investigate unspecified occurrences on this planet. Investigate the area under the orders of your marshal and ensure that the laws of Sol extend far beyond the Solar System.
