- type: job
  parent: AU14JobLEOBase
  id: AU14JobInvestigationCMBDeputyShotgun
  roundSide: ThirdParty
  roundForce: CMB
  roundRole: InvestigationCMBDeputyShotgun
  roundComponents:
  - type: NpcFactionMember
    factions:
    - AUBureau
  - type: Skills
    skills:
      RMCSkillCqc: 3
      RMCSkillEndurance: 3
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillIntel: 1
      RMCSkillMedical: 1
      RMCSkillMeleeWeapons: 1
      RMCSkillOverwatch: 1
      RMCSkillPolice: 2
      RMCSkillVehicles: 1
  - type: JobPrefix
    prefix: au14-job-prefix-cmbdeputy
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth

  name: au14-job-name-civiliancmbdeputy
  description: You have been sent by the Colonial Administration to investigate unspecified occurrences on this planet. Investigate the area under the orders of your marshal and ensure that the laws of Sol extend far beyond the Solar System.
  setPreference: false
  canBeAntag: false
  requirements:
  ranks:
    RMCRankCivilian: []
  chevrons:
    Deputy:
      entity: AU14ChevronCMBDeputy
      requirements: []
  startingGear: AU14GearCMBDeputyInvestigationShotgun
  icon: "RMCJobIconBureauDeputy"
  requireAdminNotify: false
  spawnMenuRoleName: CMB Deputy (Shotgun, 3rd party)
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  accessGroups:
  - aucmb
  - Colonist
  - AUPrisonStaff
  roleWeight: 0.25
  hidden: false

- type: startingGear
  parent: AU14GearCMBDeputyInvestigation
  id: AU14GearCMBDeputyInvestigationShotgun
  equipment:
    back: AU14SatchelCMBShotgun
    ears: AU14CMBHeadsetOnlyCMB
  inhand:
  - RMCWeaponShotgunHG3712

- type: entity
  parent: AU14BaseMobSpeciesOrganicCMB
  id: CMBInvestigationPartyJobDeputyShotgun
  name: CMB Deputy Shotgunner
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: au14-job-name-civiliancmbdeputy
    description: You have been sent by the Colonial Administration to investigate unspecified occurrences on this planet. Investigate the area under the orders of your marshal and ensure that the laws of Sol extend far beyond the Solar System.
    reregister: false
    job: AU14JobInvestigationCMBDeputyShotgun
    raffle:
      settings: short
    rules: You have been sent by the Colonial Administration to investigate unspecified occurrences on this planet. Investigate the area under the orders of your marshal and ensure that the laws of Sol extend far beyond the Solar System.
