- type: entity
  parent: SquadBase
  id: SquadOpfor
  name: Sierra
  components:
  - type: SquadTeam
    roundStart: true
    color: "#bb91d8"
    radio: radioOpforAlpha
    group: OPFOR
    minimapBackground:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_sierra

- type: entity
  parent: SquadOpfor
  id: SquadOpforBravo
  name: Tango
  components:
  - type: SquadTeam
    roundStart: true
    color: "#c6c1a8"
    group: OPFOR
    radio: radioOpforBravo
    minimapBackground:
     sprite: /Textures/_RMC14/Interface/map_blips.rsi
     state: background_tango

- type: entity
  parent: SquadOpfor
  id: SquadOpforCharlie
  name:  Uniform
  components:
  - type: SquadTeam
    roundStart: true
    color: "#7A967E"
    radio: radioOpforCharlie
    group: OPFOR
    minimapBackground:
     sprite: /Textures/_RMC14/Interface/map_blips.rsi
     state: background_uniform

- type: entity
  parent: SquadOpfor
  id: SquadOpforIntel
  name: Intel # this will cause confusion, but better than x2 Auxiliary
  components:
  - type: SquadTeam
    roundStart: true
    color: "#1E90FF"
    group: OPFOR
    radio: radioOpforIntel
    minimapBackground:
     sprite: /Textures/_RMC14/Interface/map_blips.rsi
     state: background_intel
