- type: job
  parent: CMJobBase
  id: AU14VAIEngiBase
  roundSide: ThirdParty
  roundForce: VAI
  roundRole: AU14VAIEngiBase
  roundComponents:
  - type: AssignSquad
    whitelist:
      tags:
      - AU14SquadVAIPO
  - type: Skills
    skills:
      RMCSkillCqc: 1
      RMCSkillEngineer: 4
      RMCSkillConstruction: 3
      RMCSkillFirearms: 2
      RMCSkillMedical: 1
      RMCSkillMeleeWeapons: 1
      RMCSkillPolice: 2
      RMCSkillFireman: 2
      RMCSkillPowerLoader: 1
      RMCSkillVehicles: 2
      RMCSkillJtac: 3
      RMCSkillEndurance: 2
  - type: EquipEntityPreset
    preset: AU14VAIBasePreset
  - type: JobPrefix
    prefix: au14-job-prefix-vai-engi

  name: au14-job-name-vai-engi
  description: au14-vai-mercenary-description
  ranks:
    RMCRankCivilian: []
  chevrons:
    VAI_Engineer:
      entity: AU14ChevronVASCEngineer
      requirements: []
  icon: "CMJobIconEmpty"
  playTimeTracker: AU14VAIEngi
  spawnMenuRoleName: VAI Engineer (Base)
  joinNotifyCrew: false
  hasIcon: false
  supervisors: au14-job-name-vai-teamleader
  hidden: true

- type: startingGear
  parent: AU14GearVAIBase
  id: AU14GearVAIEngi
  equipment:
    jumpsuit: AU14JumpsuitTShirtWhiteVAIToolWebbing
    pocket2: AU14PouchMagazineLargeFilledMAR40
    suitstorage: AU14WeaponRifleMAR30Tactical
    eyes: RMCWeldingGogglesSuperior
  storage:
    outerClothing:
    - RMCLaserDesignator
    back:
    - CMMRE
    - RMCExplosiveBreachingCharge
    - RMCExplosiveBreachingCharge
    - RMCExplosiveBreachingCharge
    - CMGrenadeFragOld
    - RMCSentryMini
    - CMSheetPlasteel50
    - CMSheetMetal50
