- type: job
  parent: CMJobBase
  id: AU14USArmyTankCommander
  roundSide: ThirdParty
  roundForce: USARMY
  roundRole: AU14USArmyTankCommander
  roundComponents:
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: vc
    background:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_ua
  - type: AssignSquad
    whitelist:
      tags:
      - AU14SquadUSArmy
  - type: Skills
    preset: AU14SkillPresetPlatoonCombatTechnician
  - type: SpotterWhitelist
  - type: JobPrefix
    prefix: au14-job-prefix-usarmy-tankcommander
  - type: MarineOrders
    moveOrderSoundMale:
      collection: AU14MaleMoveOrder
    moveOrderSoundFemale:
      collection: AU14FemaleMoveOrder
    focusOrderSoundMale:
      collection: AU14MaleFocusOrder
    focusOrderSoundFemale:
      collection: AU14FemaleFocusOrder
    holdOrderSoundMale:
      collection: AU14MaleHoldOrder
    holdOrderSoundFemale:
      collection: AU14FemaleHoldOrder
  - type: RMCTrackable
  - type: RMCPointing

  name: au14-job-name-usarmy-tankcommander
  description: au14-job-description-usarmy-tankccrew
  playTimeTracker: AU14JobUSArmyTankCommander
  ranks:
    RMCRankCivilian: []
  chevrons:
    USArmy_SergeantFirstClass:
      entity: AU14ChevronUSArmySergeantFirstClass
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobUSArmyTankCommander
        time: 18000 #5 hours
    USArmy_StaffSergeant:
      entity: AU14ChevronUSArmyStaffSergeant
      requirements: []
  spawnMenuRoleName: US Army Tank Commander (AU14, 3rd Party)
  startingGear: AU14GearUSArmyTankCommander
  greeting: au14-usarmy-tank-greeting
  icon: "AU14JobIconTankCrewman"
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforSquad
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicUSArmy
  id: AU14JobUSArmyTankCommander
  name: US Army Tank Commander
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: AU14SquadUSArmy32nd
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: au14-job-name-usarmy-tankcommander
    description: au14-job-description-usarmy-tankcrew
    reregister: false
    job: AU14USArmyTankCommander
    raffle:
      settings: short
    rules: au14-usarmy-rules

- type: startingGear
  id: AU14GearUSArmyTankCommander
  equipment:
    id: AU14IDCardUSArmyTankCommander
    outerClothing: RMCOuterClothingExternalWebbing
    jumpsuit: AU14ArmyJumpsuitTanker
    gloves: AU14PVEHandsInsulatedBlackMarine
    shoes: AU14BootsUSArmyFilled
    eyes: RMCWeldingGoggles
    mask: RMCMaskKeffiyeh
    head: AU14HelmetUSArmy
    belt: AU14BeltUtilityCombatFilled
    pocket1: AU14PouchIFAKFill
    pocket2: AU14PouchIFAKFill
    back: AU14MolleSatchel
    ears: AU14HeadsetUSArmy
    suitstorage: RMCFlashlight
  storage:
    belt:
    - RMCMK80
    - CMMagazinePistolMK80
    - CMMagazinePistolMK80
    head:
    - RMCGogglesBallisticPolarizedOrange

- type: jobIcon
  parent: CMJobIconBase
  id: AU14JobIconTankCrewman
  icon:
    sprite: _RMC14/Interface/cm_job_icons.rsi
    state: hudsquad_tc

- type: playTimeTracker
  id: AU14JobUSArmyTankCommander
