- type: job
  parent: AU14VAIMachinegunnerBase
  id: AU14VAIMachinegunner
  spawnMenuRoleName: VAIPO Machinegunner
  playTimeTracker: AU14VAIMachinegunner
  icon: "CMJobIconEmpty"
  greeting: au14-vaipo-greeting
  startingGear: AU14GearVAIPOMachinegunner
  basePlaytimeTracker: true
  accessGroups:
  - auadmin
  - Colonist
  - CMCargoTech
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicVAI
  id: AU14VAIMachinegunner
  name: VAIPO Machinegunner
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: AU14SquadVAIPO
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: VAIPO Machinegunner
    description: You have been dispatched to the colony by Vanguard's Arrow because of contract with local UA Ambassador. Assist the Ambassador with what you can.
    job: AU14VAIMachinegunner
    raffle:
      settings: short

- type: startingGear
  parent: AU14GearVAIMG
  id: AU14GearVAIPOMachinegunner
  equipment:
    id: AU14IDCardVAIMercenary
    ears: AU14HeadsetVAI

- type: playTimeTracker
  id: AU14VAIMachinegunner