- type: job
  parent: CMJobBase
  id: AU14JobCivilianHeadOfService
  roundSide: Civilian
  roundForce: COLONY
  roundRole: CivilianHeadOfService
  roundComponents:
  - type: Skills
    skills:
      RMCSkillFireman: 1
      RMCSkillVehicles: 1
      RMCSkillDomestics: 3
      RMCSkillConstruction: 1
      RMCSkillFirearms: 2
  - type: JobPrefix
    prefix: au14-job-prefix-headofservice
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14colonyjobicons.rsi
      state: head_of_service

  name: au14-job-name-civilianheadofservice
  description: au14-job-description-civilianheadofservice
  setPreference: true
  canBeAntag: false
  playTimeTracker: AU14JobCivilianHeadOfService
  requirements:
  - !type:DepartmentTimeRequirement
    department: AU14DepartmentServices
    time: 36000 # 10 hours
  - !type:OverallPlaytimeRequirement
    time: 86400 # 24 hours
  - !type:AgeRequirement
    requiredAge: 23
  - !type:TraitsRequirement
    inverted: true
    traits:
    - NonResuscitable
    - NoEnglish
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCivilianHeadOfService
  icon: "AU14JobIconCivilianHeadOfService"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonyadministrator
  accessGroups:
  - Colonist
  - auheadsofcolony
  access:
# - AU14AccessColonyHeadOfService # implicit
  - AU14AccessColonyAdministrator
  roleWeight: 0.25

- type: startingGear
  id: AU14GearCivilianHeadOfService
  equipment:
    jumpsuit: AU14CivilianWorkwearYellow
    shoes: RMCShoesBlack
    id: AU14IDCardColonyHeadOfService
    outerClothing: RMCMedicalApron
    pocket1: AU14StampHOS

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianHeadOfService
  name: Spawn Point Head of Service
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianHeadOfService
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianHeadOfService
  isHumanoid: true
