using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Requisitions;

[GenerateTypedNameReferences]
public sealed partial class RequisitionsOrderButton : BoxContainer
{
    public int Cost { get; private set; }
    public int Category { get; private set; }
    public int Order { get; private set; }

    public RequisitionsOrderButton()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetEntry(int category, int order, string name, string description, int cost)
    {
        Category = category;
        Order = order;
        Cost = cost;
        NameLabel.Text = name;
        DescriptionLabel.Text = description;
        CostLabel.Text = $"${cost}";
    }

    public void SetStock(string stock)
    {
        StockLabel.Text = stock;
    }

    public void SetCrtMode(bool enabled)
    {
        SetClass(RowPanel, StyleNano.StyleClassCrtInsetPanel, enabled);
        SetClass(NameLabel, StyleNano.StyleClassCrtText, enabled);
        SetClass(DescriptionLabel, StyleNano.StyleClassCrtDimText, enabled);
        SetClass(CostLabel, StyleNano.StyleClassCrtText, enabled);
        SetClass(StockLabel, StyleNano.StyleClassCrtDimText, enabled);
        SetButtonClass(DetailsButton, enabled);
        SetButtonClass(OrderButton, enabled);
    }

    private static void SetButtonClass(Button button, bool enabled)
    {
        SetClass(button, StyleNano.StyleClassCrtButton, enabled);
        SetClass(button.Label, StyleNano.StyleClassCrtButtonLabel, enabled);
    }

    private static void SetClass(Control control, string styleClass, bool enabled)
    {
        if (enabled)
        {
            if (!control.HasStyleClass(styleClass))
                control.AddStyleClass(styleClass);
            return;
        }

        control.RemoveStyleClass(styleClass);
    }
}
