using System.Linq;
using Content.Shared._CMU14.Threats.Mobs.WorkingJoe;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CMU14.Threats.Mobs.WorkingJoe;

[GenerateTypedNameReferences]
public sealed partial class WorkingJoeVoiceWindow : DefaultWindow
{
    private static readonly string[] QuestionCategories =
    {
        "Curious", "Interrogation", "Identification", "Concern"
    };

    private const int MaxRecent = 5;
    private readonly WorkingJoeVoiceFavorites _favorites;
    private readonly List<string> _recentIds = new();

    private List<WorkingJoeVoiceLine> _allLines = new();
    private string? _selectedCategory;
    private bool _showFavorites;

    public WorkingJoeVoiceWindow(WorkingJoeVoiceFavorites favorites)
    {
        _favorites = favorites;
        RobustXamlLoader.Load(this);
        SearchBar.OnTextChanged += _ => RebuildList();
    }

    public event Action<string>? OnLineSelected;

    public void SetLines(List<WorkingJoeVoiceLine> lines)
    {
        _allLines = lines.OrderBy(l => l.Category).ThenBy(l => l.DisplayName).ToList();
        RebuildCategories();
        RebuildList();
    }

    private void RebuildCategories()
    {
        CategoryList.RemoveAllChildren();

        var allButton = new Button
        {
            Text = "All",
            HorizontalExpand = true,
            ToggleMode = true,
            Pressed = _selectedCategory == null && !_showFavorites
        };
        allButton.OnPressed += _ =>
        {
            _selectedCategory = null;
            _showFavorites = false;
            RebuildList();
            UpdateCategoryButtonStates();
        };
        CategoryList.AddChild(allButton);

        var favButton = new Button
        {
            Text = "★ Favorites",
            HorizontalExpand = true,
            ToggleMode = true,
            Pressed = _showFavorites
        };
        favButton.OnPressed += _ =>
        {
            _showFavorites = true;
            _selectedCategory = null;
            RebuildList();
            UpdateCategoryButtonStates();
        };
        CategoryList.AddChild(favButton);

        var recentButton = new Button
        {
            Text = "⏲ Recent",
            HorizontalExpand = true,
            ToggleMode = true,
            Pressed = _selectedCategory == "__recent"
        };
        recentButton.OnPressed += _ =>
        {
            _selectedCategory = "__recent";
            _showFavorites = false;
            RebuildList();
            UpdateCategoryButtonStates();
        };
        CategoryList.AddChild(recentButton);

        List<string> nonQuestionCategories = _allLines
            .Select(l => l.Category)
            .Distinct()
            .Where(c => !QuestionCategories.Contains(c))
            .OrderBy(c => c)
            .ToList();

        List<string> questionCategories = _allLines
            .Select(l => l.Category)
            .Distinct()
            .Where(c => QuestionCategories.Contains(c))
            .OrderBy(c => Array.IndexOf(QuestionCategories, c))
            .ToList();

        foreach (string category in nonQuestionCategories)
        {
            AddCategoryButton(category);
        }

        if (questionCategories.Count > 0)
        {
            var separator = new PanelContainer
            {
                MinHeight = 2,
                HorizontalExpand = true,
                Margin = new(0, 6)
            };
            CategoryList.AddChild(separator);

            var label = new Label
            {
                Text = "Questions",
                FontColorOverride = Color.FromHex("#AAAAAA"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new(0, 2)
            };
            CategoryList.AddChild(label);

            foreach (string category in questionCategories)
            {
                AddCategoryButton(category);
            }
        }
    }

    private void AddCategoryButton(string category)
    {
        var button = new Button
        {
            Text = category,
            HorizontalExpand = true,
            ToggleMode = true,
            Pressed = _selectedCategory == category
        };
        button.OnPressed += _ =>
        {
            _selectedCategory = category;
            _showFavorites = false;
            RebuildList();
            UpdateCategoryButtonStates();
        };
        CategoryList.AddChild(button);
    }

    private void UpdateCategoryButtonStates()
    {
        foreach (Control child in CategoryList.Children)
        {
            if (child is not Button btn)
                continue;

            if (btn.Text == "All")
                btn.Pressed = _selectedCategory == null && !_showFavorites;
            else if (btn.Text == "★ Favorites")
                btn.Pressed = _showFavorites;
            else if (btn.Text == "⏲ Recent")
                btn.Pressed = _selectedCategory == "__recent";
            else
                btn.Pressed = btn.Text == _selectedCategory;
        }
    }

    private void RebuildList()
    {
        LineList.RemoveAllChildren();

        string search = SearchBar.Text.Trim().ToLowerInvariant();

        List<WorkingJoeVoiceLine> filtered;

        if (_selectedCategory == "__recent")
        {
            filtered = _recentIds
                .Select(id => _allLines.FirstOrDefault(l => l.EmoteId == id))
                .Where(l => l != null)
                .Where(l => string.IsNullOrEmpty(search) || l!.DisplayName.ToLowerInvariant().Contains(search))
                .ToList()!;
        }
        else if (_showFavorites)
        {
            filtered = _allLines
                .Where(l => _favorites.Contains(l.EmoteId))
                .Where(l => string.IsNullOrEmpty(search) || l.DisplayName.ToLowerInvariant().Contains((string)search))
                .ToList();
        }
        else
        {
            filtered = _allLines
                .Where(l => _selectedCategory == null || l.Category == _selectedCategory)
                .Where(l => string.IsNullOrEmpty(search) || l.DisplayName.ToLowerInvariant().Contains((string)search))
                .ToList();
        }

        foreach (WorkingJoeVoiceLine line in filtered)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 4
            };

            bool isFav = _favorites.Contains(line.EmoteId);
            var favButton = new Button
            {
                Text = isFav ? "★" : "☆",
                MinWidth = 30,
                MaxWidth = 30,
                ToolTip = isFav ? "Remove from favorites" : "Add to favorites"
            };
            string emoteId = line.EmoteId;
            favButton.OnPressed += _ =>
            {
                _favorites.Toggle(emoteId);
                RebuildList();
            };
            row.AddChild(favButton);

            var lineButton = new Button
            {
                Text = line.DisplayName,
                HorizontalExpand = true,
                StyleClasses = { "OpenRight" }
            };
            lineButton.OnPressed += _ =>
            {
                OnLineSelected?.Invoke(emoteId);
                AddRecent(emoteId);
            };
            row.AddChild(lineButton);

            LineList.AddChild(row);
        }

        if (!filtered.Any())
        {
            LineList.AddChild(new Label
            {
                Text = "No results.",
                FontColorOverride = Color.FromHex("#888888"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new(0, 12)
            });
        }
    }

    private void AddRecent(string emoteId)
    {
        _recentIds.Remove(emoteId);
        _recentIds.Insert(0, emoteId);
        if (_recentIds.Count > MaxRecent)
            _recentIds.RemoveAt(_recentIds.Count - 1);
    }
}
