- type: antagJobBlacklist
  id: AllGovforJobs
  jobs:
    - AU14JobGOVFORPlatCo
    - AU14JobGOVFORPlatoonCorpsman
    - AU14JobGOVFORDCC
    - AU14JobGOVFORPlatOp
    - AU14JobGOVFORDSPilot
    - AU14JobGOVFORRadioTelephoneOperator
    - AU14JobGOVFORSquadSergeant
    - AU14JobGOVFORSquadAutomaticRifleman
    - AU14JobGOVFORSquadCombatTech
    - AU14JobGOVFORSquadRifleman
    - AU14JobGOVFORAuxSupportSynth
    - AU14JobGOVFORadvisor
    - AU14JobGOVFORMilitaryDoctor
    - AU14JobGOVFORMilitaryPoliceMan
    - AU14JobGOVFORSectionSergeant
    - AU14JobGOVFORAuxTech
    - AU14JobGOVFORWorkingJoe
    - AU14JobGOVFORWeaponsSpecialist
    - AU14JobGOVFORVehicleCrewman
    - CMUJobGOVFORDroneOperator

- type: antagJobBlacklist
  id: AllOpforJobs
  jobs:
    - AU14JobOPFORPlatCo
    - AU14JobOPFORPlatoonCorpsman
    - AU14JobOPFORDCC
    - AU14JobOPFORPlatOp
    - AU14JobOPFORDSPilot
    - AU14JobOPFORRadioTelephoneOperator
    - AU14JobOPFORSquadSergeant
    - AU14JobOPFORSquadAutomaticRifleman
    - AU14JobOPFORSquadCombatTech
    - AU14JobOPFORSquadRifleman
    - AU14JobOPFORAuxSupportSynth
    - AU14JobOPFORadvisor
    - AU14JobOPFORMilitaryDoctor
    - AU14JobOPFORMilitaryPoliceMan
    - AU14JobOPFORSectionSergeant
    - AU14JobOPFORAuxTech
    - AU14JobOPFORWorkingJoe
    - AU14JobOPFORVehicleCrewman
#   - CMUJobOPFORDroneOperator
#   - AU14JobOPFORWeaponsSpecialist

- type: entity
  id: RunawaySynth
  parent: BaseGameRule
  components:
  - type: GameRule
  - type: RunawaySynthRule
  - type: AntagSelection
    selectionTime: IntraPlayerSpawn
    definitions:
    - prefRoles: [ RunawaySynthRole ]
      max: 1
      playerRatio: 15
      jobBlacklistGroup:
      - AllGovforJobs
      - AllOpforJobs
      briefing:
        text: runawaysynth-role-greeting
        color: CornflowerBlue
        sound: "/Audio/Ambience/Antag/headrev_start.ogg"
      components:
      - type: RunawaySynth
      - type: Synth
        changeBrain: false
        canUseGuns: true
        hideGeneration: true
        useHumanHealthIcons: true
      - type: Skills
        skills:
          RMCSkillCqc: 4
          RMCSkillEngineer: 4
          RMCSkillConstruction: 3
          RMCSkillOverwatch: 1
          RMCSkillMedical: 4
          RMCSkillSurgery: 3
          RMCSkillResearch: 1
          RMCSkillMeleeWeapons: 2
          RMCSkillPilot: 2
          RMCSkillPolice: 2
          RMCSkillFireman: 5
          RMCSkillFirearms: 2
          RMCSkillPowerLoader: 2
          RMCSkillVehicles: 2
          RMCSkillJtac: 3
          RMCSkillIntel: 2
          RMCSkillDomestics: 2
          RMCSkillNavigations: 1
#     mindRoles:
#     - MindRoleRunawaySynth

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleRunawaySynth
  name: Runaway Synth  Role
  components:
  - type: MindRole
    antagPrototype: RunawaySynthRole
    exclusiveAntag: true
    roleType: TeamAntagonist

- type: antag
  id: RunawaySynthRole
  name: roles-antag-runaway-synth-name
  antagonist: true
  category: roles-antag-category-colony
  setPreference: true
  objective: roles-antag-synth-objective
  isCM: true

## CLF subverted synth
- type: entity
  id: SubvertedSynth
  parent: BaseGameRule
  components:
  - type: SubvertedSynthRule
  - type: AntagSelection
    selectionTime: PostPlayerSpawn
    definitions:
    - prefRoles: [ CLFSubvertedSynthRole ]

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleCLFSubvertedSynth
  name: CLF Subverted Synth Role
  components:
  - type: MindRole
    antagPrototype: CLFSubvertedSynthRole
    exclusiveAntag: true
    roleType: TeamAntagonist

- type: antag
  id: CLFSubvertedSynthRole
  name: roles-antag-clf-subverted-synth-name
  antagonist: true
  setPreference: false
  objective: roles-antag-clf-subverted-synth-objective
  isCM: true

## CLF Recruit (tattooed into the CLF)
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleCLFRecruit
  name: CLF Recruit Role
  components:
  - type: MindRole
    antagPrototype: CLFRecruitRole
    exclusiveAntag: true
    roleType: TeamAntagonist

- type: antag
  id: CLFRecruitRole
  name: roles-antag-clf-recruit-name
  antagonist: true
  setPreference: false
  objective: roles-antag-clf-recruit-objective
  isCM: true

## CLF guerrilla
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleCLFGuerrilla
  name: CLF Guerrilla Role
  components:
  - type: MindRole
    antagPrototype: CLFGuerrillaRole
    exclusiveAntag: true
    roleType: TeamAntagonist

- type: antag
  id: CLFGuerrillaRole
  name: roles-antag-clf-guerrilla-name
  setPreference: false #already done by the job thing
  objective: roles-antag-clf-guerrilla-objective
  isCM: true

## CLF Physician
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleCLFPhysician
  components:
  - type: MindRole
    antagPrototype: CLFPhysicianRole
    exclusiveAntag: true
    roleType: TeamAntagonist

- type: antag
  id: CLFPhysicianRole
  name: roles-antag-clf-physician-name
  setPreference: false #already done by the job thing
  objective: roles-antag-clf-doctor-objective
  isCM: true

## CLF Surgeon
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleCLFSurgeon
  components:
  - type: MindRole
    antagPrototype: CLFSurgeonRole
    exclusiveAntag: true
    roleType: TeamAntagonist

- type: antag
  id: CLFSurgeonRole
  name: roles-antag-clf-surgeon-name
  setPreference: false #yada yada job thing
  objective: roles-antag-clf-doctor-objective
  isCM: true

## CLF Leader
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleCLFLeader
  components:
  - type: MindRole
    antagPrototype: CLFLeaderRole
    exclusiveAntag: true
    roleType: TeamAntagonist

- type: antag
  id: CLFLeaderRole
  name: roles-antag-clf-leader-name
  setPreference: false #job thing
  objective: roles-antag-clf-leader-objective
  isCM: true

## cultist
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleCultist
  components:
  - type: MindRole
    antagPrototype: CultistRole
    exclusiveAntag: true
    roleType: TeamAntagonist

- type: antag
  id: CultistRole
  name: roles-antag-cultist-name
  setPreference: false
  objective: roles-antag-cultist-objective
  isCM: true

## fugitive
- type: entity
  id: Fugitive
  parent: BaseGameRule
  components:
  - type: GameRule
  - type: FugitiveRule
  - type: AntagSelection
    selectionTime: IntraPlayerSpawn
    definitions:
    - prefRoles: [ FugitiveRole ]
      max: 1
      playerRatio: 15
      jobBlacklistGroup:
      - AllGovforJobs
      - AllOpforJobs
      briefing:
        text: fugitive-role-greeting
        color: CornflowerBlue
        sound: "/Audio/Ambience/Antag/headrev_start.ogg"
      components:
      - type: Fugitive
      mindRoles:
      - MindRoleFugitive
      startingGear: AU14GearFugitive

- type: startingGear
  id: AU14GearFugitive
  equipment:
    pocket1: AU14ObjectiveItemWYLaptop

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleFugitive
  name: Fugitive  Role
  components:
  - type: MindRole
    antagPrototype: FugitiveRole
    exclusiveAntag: true
    roleType: TeamAntagonist

- type: antag
  id: FugitiveRole
  name: roles-antag-fugitive-name
  antagonist: true
  category: roles-antag-category-colony
  setPreference: true
  objective: roles-antag-fugitive-objective
  isCM: true

- type: antag
  id: ExpedTrailerRole
  name: roles-antag-exped-traitor-name
  antagonist: true
  category: roles-antag-category-prometheus
  setPreference: false
  objective: roles-antag-exped-traitor-objective
  isCM: true

- type: antag
  id: MonsterRole
  name: monster-traitor-name
  antagonist: true
  category: roles-antag-category-prometheus
  setPreference: false
  objective: monster-traitor-objective
  isCM: true

## Druggo
- type: entity
  id: DrugDealer
  parent: BaseGameRule
  components:
  - type: GameRule
  - type: DrugDealerRule
  - type: AntagSelection
    selectionTime: IntraPlayerSpawn
    definitions:
    - prefRoles: [ DrugDealerRole ]
      max: 1
      playerRatio: 15
      jobBlacklistGroup:
      - AllGovforJobs
      - AllOpforJobs
      briefing:
        text: dealer-role-greeting
        color: MediumVioletRed
        sound: "/Audio/Ambience/Antag/headrev_start.ogg"
      startingGear: AU14GearDrugDealer
      components:
      - type: DrugDealer
      mindRoles:
      - MindRoleDrugDealer

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleDrugDealer
  name: Drug Dealer Role
  components:
  - type: MindRole
    antagPrototype: DrugDealerRole
    exclusiveAntag: true
    roleType: TeamAntagonist

- type: antag
  id: DrugDealerRole
  name: roles-antag-dealer-name
  antagonist: true
  category: roles-antag-category-colony
  setPreference: true
  objective: roles-antag-dealer-objective
  isCM: true

- type: startingGear
  id: AU14GearDrugDealer
  equipment:
    back: AU14DrugDealerDrugBackpack

- type: entity
  parent: RMCSatchelBlack
  id: AU14DrugDealerDrugBackpack
  name: drug dealer's satchel
  description: A black satchel filled with illicit substances.
  components:
  - type: StorageFill
    contents:
    - id: Joint
      amount: 3
    - id: AU14DrugDealerDrugBottle
      amount: 4
    - id: AU14PillBottleSpaceDrugs
      amount: 3
    - id: RMCSyringeDrugs
      amount: 2
    - id: AU14PillBottleRMCPsilocybin
      amount: 2

## Spy
- type: entity
  id: CorporateSpy
  parent: BaseGameRule
  components:
  - type: GameRule
  - type: AntagSelection
    selectionTime: IntraPlayerSpawn
    definitions:
    - prefRoles: [ CorporateSpyRole ]
      max: 1
      playerRatio: 15
      jobBlacklistGroup:
      - AllGovforJobs
      - AllOpforJobs
      briefing:
        text: spy-role-greeting
        color: DarkSlateGray
        sound: "/Audio/Ambience/Antag/headrev_start.ogg"
      startingGear: AU14GearCorporateSpy
      components:
      - type: CorporateSpy
      mindRoles:
      - MindRoleCorporateSpy

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleCorporateSpy
  name: Corporate Spy Role
  components:
  - type: MindRole
    antagPrototype: CorporateSpyRole
    exclusiveAntag: true
    roleType: TeamAntagonist

- type: antag
  id: CorporateSpyRole
  name: roles-antag-spy-name
  antagonist: true
  category: roles-antag-category-colony
  setPreference: true
  objective: roles-antag-spy-objective
  isCM: True

- type: startingGear
  id: AU14GearCorporateSpy
  equipment:
    pocket1: AU14IDCardCorporateSpy

## CLF Veteran
- type: entity
  id: CLFVeteran
  parent: BaseGameRule
  components:
  - type: GameRule
  - type: CLFVeteranRule
  - type: AntagSelection
    selectionTime: IntraPlayerSpawn
    definitions:
    - prefRoles: [ CLFVeteranRole ]
      max: 1
      playerRatio: 15
      jobBlacklistGroup:
      - AllGovforJobs
      - AllOpforJobs
      jobBlacklist:
      - AU14JobCLFGuerilla
      - AU14JobCLFCellLeader
      - AU14JobCLFPhysician
      - AU14JobCLFSurgeon
      briefing:
        text: clfveteran-role-greeting
        color: OliveDrab
        sound: "/Audio/Ambience/Antag/headrev_start.ogg"
      startingGear: AU14GearCLFVeteran
      components:
      - type: CLFVeteran
      - type: Skills
        skills:
          RMCSkillFirearms: 3
          RMCSkillMeleeWeapons: 3
          RMCSkillCqc: 3
          RMCSkillEndurance: 3
          RMCSkillFireman: 3
          RMCSkillConstruction: 3
          RMCSkillLeadership: 3
          RMCSkillMedical: 3
          RMCSkillPolice: 1
          RMCSkillSurgery: 3
      mindRoles:
      - MindRoleCLFVeteran

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleCLFVeteran
  name: CLF Veteran Role
  components:
  - type: MindRole
    antagPrototype: CLFVeteranRole
    exclusiveAntag: true
    roleType: TeamAntagonist

- type: antag
  id: CLFVeteranRole
  name: roles-antag-clfveteran-name
  antagonist: true
  category: roles-antag-category-colony
  setPreference: true
  objective: roles-antag-clfveteran-objective
  isCM: true

- type: startingGear
  id: AU14GearCLFVeteran
  equipment:
    suitstorage: AU14WeaponRevolverM44Inscribed

## Strike Organizer
- type: entity
  id: StrikeOrganizer
  parent: BaseGameRule
  components:
  - type: GameRule
  - type: StrikeOrganizerRule
  - type: AntagSelection
    selectionTime: IntraPlayerSpawn
    definitions:
    - prefRoles: [ StrikeOrganizerRole ]
      max: 1
      playerRatio: 15
      jobBlacklistGroup:
      - AllGovforJobs
      - AllOpforJobs
      briefing:
        text: strikeorganizer-role-greeting
        color: DarkRed
        sound: "/Audio/Ambience/Antag/headrev_start.ogg"
      startingGear: AU14GearStrikeOrganizer
      components:
      - type: StrikeOrganizer
      mindRoles:
      - MindRoleStrikeOrganizer

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleStrikeOrganizer
  name: Strike Organizer Role
  components:
  - type: MindRole
    antagPrototype: StrikeOrganizerRole
    exclusiveAntag: true
    roleType: TeamAntagonist

- type: antag
  id: StrikeOrganizerRole
  name: roles-antag-strikeorganizer-name
  antagonist: true
  category: roles-antag-category-colony
  setPreference: true
  objective: roles-antag-strikeorganizer-objective
  isCM: true

- type: startingGear
  id: AU14GearStrikeOrganizer
  equipment:
    back: AU14StrikeOrganizerBackpack

- type: entity
  parent: RMCBackpackRTO
  id: AU14StrikeOrganizerBackpack
  name: organizer's radio pack
  description: A radio telephone pack carried by a labor organize.
  components:
  - type: StorageFill
    contents:
    - id: RMCMegaphone
    - id: RMCSpaceCash1000
      amount: 2

## Cannibal
- type: entity
  id: Cannibal
  parent: BaseGameRule
  components:
  - type: GameRule
  - type: CannibalRule
  - type: AntagSelection
    selectionTime: PostPlayerSpawn
    definitions:
    - prefRoles: [ CannibalRole ]
      max: 1
      playerRatio: 15
      jobWhitelist:
      - AU14JobCivilianFoodServiceWorker
      briefing:
        text: cannibal-role-greeting
        color: DarkRed
        sound: "/Audio/Ambience/Antag/headrev_start.ogg"
      components:
      - type: Cannibal
      mindRoles:
      - MindRoleCannibal

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleCannibal
  name: Cannibal Role
  components:
  - type: MindRole
    antagPrototype: CannibalRole
    exclusiveAntag: true
    roleType: TeamAntagonist

- type: antag
  id: CannibalRole
  name: roles-antag-cannibal-name
  antagonist: true
  category: roles-antag-category-colony
  setPreference: true
  objective: roles-antag-cannibal-objective
  isCM: true

## Serial Killer
- type: entity
  id: SerialKiller
  parent: BaseGameRule
  components:
  - type: GameRule
  - type: SerialKillerRule
  - type: AntagSelection
    selectionTime: IntraPlayerSpawn
    definitions:
    - prefRoles: [ SerialKillerRole ]
      max: 1
      playerRatio: 15
      jobBlacklistGroup:
      - AllGovforJobs
      - AllOpforJobs
      briefing:
        text: serialkiller-role-greeting
        color: DarkRed
        sound: "/Audio/Ambience/Antag/headrev_start.ogg"
      components:
      - type: SerialKiller
      mindRoles:
      - MindRoleSerialKiller

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleSerialKiller
  name: Serial Killer Role
  components:
  - type: MindRole
    antagPrototype: SerialKillerRole
    exclusiveAntag: true
    roleType: TeamAntagonist

- type: antag
  id: SerialKillerRole
  name: roles-antag-serialkiller-name
  antagonist: true
  category: roles-antag-category-colony
  setPreference: true
  objective: roles-antag-serialkiller-objective
  isCM: true

## CLF Sleeper Agent
- type: entity
  id: CLFSleeperAgent
  parent: BaseGameRule
  components:
  - type: GameRule
  - type: CLFSleeperAgentRule
  - type: AntagSelection
    selectionTime: PostPlayerSpawn
    definitions:
    - prefRoles: [ CLFSleeperAgentRole ]
      max: 1
      playerRatio: 20
      jobWhitelist:
      - AU14JobGOVFORSquadSergeant
      - AU14JobGOVFORSectionSergeant
      - AU14JobGOVFORPlatOp
      - AU14JobGOVFORMilitaryPoliceMan
      briefing:
        text: clf-sleeper-agent-role-greeting
        color: OliveDrab
        sound: "/Audio/Ambience/Antag/headrev_start.ogg"
      components:
      - type: CLFSleeperAgent
      mindRoles:
      - MindRoleCLFSleeperAgent

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleCLFSleeperAgent
  name: CLF Sleeper Agent Role
  components:
  - type: MindRole
    antagPrototype: CLFSleeperAgentRole
    exclusiveAntag: true
    roleType: TeamAntagonist

- type: antag
  id: CLFSleeperAgentRole
  name: roles-antag-clf-sleeper-agent-name
  antagonist: true
  category: roles-antag-category-colony
  setPreference: true
  objective: roles-antag-clf-sleeper-agent-objective
  isCM: true
