- type: job
  parent: AU14JobWYGuardBase
  id: AU14JobWYSurvGoon
  roundSide: ThirdParty
  roundForce: WY
  roundRole: WYSurvGoon
  roundComponents:
  - type: NpcFactionMember
    factions:
    - AUWeYu
  - type: Skills
    skills:
      RMCSkillConstruction: 1
      RMCSkillCqc: 2
      RMCSkillEndurance: 2
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillIntel: 1
      RMCSkillOverwatch: 1
      RMCSkillPolice: 2
      RMCSkillVehicles: 1
  - type: EquipEntityPreset
    preset: AU14WYSurvRiflePreset
  - type: JobPrefix
    prefix: au14-job-prefix-wyguard
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth
  - type: AssignSquad
    whitelist:
      tags:
      - SquadPMC

  name: au14-job-name-wyguard
  description: au14-wysurv-greeting
  ranks:
    AU14RankWYSecurityOfficer: []
  spawnMenuRoleName: WY Corporate Goon (Survivor)
  startingGear: AU14GearWYSurvGoon
  greeting: au14-wysurv-greeting
  icon: "RMCJobIconPMCGoonStandard"
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-wy
  accessGroups:
  - auwy
  - AUPrisonStaff
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicWeYu
  id: AU14JobWYSurvGoon
  name: WY Corporate Goon (Survivor)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: SquadPMC
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: au14-job-name-wyguard
    description: au14-wysurv-description
    reregister: false
    job: AU14JobWYSurvGoon
    raffle:
      settings: short
    rules: au14-wysurv-description

- type: startingGear
  id: AU14GearWYSurvGoon
  equipment:
    id: AU14IDCardColonyCorporateLiaison
    outerClothing: CMArmorM4PMCCorporateLead
    jumpsuit: AU14JumpsuitVeteranPMCCorporate
    shoes: RMCBootsPMCFilled
    head: RMCArmorHelmetPMCCorporateHybrisa
    gloves: AU14PVEHandsInsulatedBlackMarine
    belt: RMCM77BeltPMCFilled
    pocket2: AU14PouchIFAKFill
    back: RMCSatchelLightpackWeYa
    eyes: CMGlassesSecurity
    ears: RMCHeadsetDistressWeYa
    inhand: RMCFlashlight
  storage:
    back:
    - AU14CBRNKitWeYu
    - RMCMREWeYa
    - CMCanteen
    - CMSheetMetal30
    - RMCFlashlight 
    - CMCrowbar
    - RMCRadioHandheldColonyOff
