- type: job
  parent: AU14JobCivilianScientistBase
  id: AU14JobWYSurvScientist
  roundSide: ThirdParty
  roundForce: WY
  roundRole: WYSurvScientist
  roundComponents:
  - type: NpcFactionMember
    factions:
    - AUWeYu
  - type: Skills
    skills:
      RMCSkillMedical: 3
      RMCSkillFireman: 1
      RMCSkillVehicles: 1
      RMCSkillDomestics: 1
      RMCSkillFirearms: 2
      RMCSkillSurgery: 4
  - type: EquipEntityPreset
    preset: AU14WeYuSurvPistolPreset
  - type: JobPrefix
    prefix: au14-job-prefix-civilianscientist
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth
  - type: AssignSquad
    whitelist:
      tags:
      - SquadPMC

  name: au14-job-name-civilianscientist
  description: au14-wysurv-description
  ranks:
    AU14RankScientistProfessor:
    - !type:RoleTimeRequirement
      role: AU14JobCivilianScientist
      time: 36000 # 10 hours
    AU14RankScientistAssociate: []
  spawnMenuRoleName: WY Scientist (Survivor)
  startingGear: AU14GearWYSurvScientist
  greeting: au14-wysurv-greeting
  icon: "RMCJobIconPMCScientist"
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-wy
  accessGroups:
  - Colonist
  - auwy
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicWeYu
  id: AU14JobWYSurvScientist
  name: WY Scientist (Survivor)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: SquadPMC
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: au14-job-name-civilianscientist
    description: au14-wysurv-description
    reregister: false
    job: AU14JobWYSurvScientist
    raffle:
      settings: short
    rules: au14-wysurv-description

- type: startingGear
  id: AU14GearWYSurvScientist
  equipment:
    id: AU14IDCardCivilianScientist
    jumpsuit: AU14CivilianWorkwearBlue
    shoes: RMCShoesBlack
    ears: AU14ColonyWeylandHeadset
    outerClothing: RMCLabcoatOpened
    eyes: RMCGlassesMedicalHUDGlasses
    belt: AU14BeltMedicBagSupportSynth
    back: RMCSatchelChemistry
    pocket1: CMSurgicalCaseFilled
    pocket2: AU14PouchIFAKFill
  storage:
    back:
    - AU14CBRNKitWeYu
    - RMCSyringeCaseFilled
    - RMCSyringeCaseFilledToxin
    - CMHandsLatex
    - CMHealthAnalyzer
    - AU14CMDefibrillator
    - RMCRadioHandheldColonyOff
    outerClothing:
    - CMCrowbar
    - RMCFlashlight
