- type: job
  parent: AU14JobFORECONSpotterBase
  id: AU14FORECONKillTeamSpotter
  roundSide: ThirdParty
  roundForce: FORECON
  roundRole: AU14FORECONKillTeamSpotter
  roundComponents:
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: spotter
  - type: Skills
    preset: AU14SkillPresetPlatoonRifleman
  - type: SpotterWhitelist
  - type: JobPrefix
    prefix: au14-job-prefix-forecon-spotter
  - type: LanguagePreset
    spokenLanguages:
    - English
    - TacticalSignLanguage
    understoodLanguages:
    - English
    - TacticalSignLanguage
    currentLanguage: English
    defaultLanguage: English

  name: au14-job-name-forecon-spotter
  description: au14-job-description-forecon-killteam
  playTimeTracker: AU14FORECONSpotterDetachment
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMCRankChiefWarrantOfficer:
      entity: AU14ChevronUSCMChiefWarrantOfficer2
      requirements: []
  spawnMenuRoleName: FORECON Spotter (AU14, KillTeam)
  startingGear: AU14GearFORECONKillTeamSpotter
  greeting: au14-job-description-forecon-killteam-greeting
  icon: "CMJobIconEmpty"
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-loner
  hidden: true

- type: entity
  parent: AU14BaseMobSpeciesOrganicFORECON
  suffix: AU14, FORECON, KillTeam
  id: AU14JobFORECONKillTeamSpotter
  name: FORECON Spotter (Kill Team)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: SquadFORECON
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: au14-job-name-forecon-spotter
    description: au14-job-description-forecon-killteam
    reregister: false
    job: AU14FORECONKillTeamSpotter
    raffle:
      settings: short
    rules: au14-forecon-killteam-rules

- type: startingGear
  id: AU14GearFORECONKillTeamSpotter
  equipment:
    id: AU14IDCardFORECONKillTeamSpotter
    outerClothing: AU14ArmorGhillie
    jumpsuit: AU14JumpsuitFORECON
    shoes: RMCScoutShoes
    head: AU14HelmetGhillie
    mask: RMCMaskBalaclava
    belt: CMBeltMarine
    pocket1: AU14PouchSlingBinocs
    pocket2: AU14PouchIFAKFill
    back: CMBackpackSniper
    ears: AU14HeadsetFORECONERT
    suitstorage: AU14WeaponRifleM41AMK1ReconSuppressed
  storage:
    belt:
    - CMMagazineRifleM54CMK1
    - CMMagazineRifleM54CMK1
    - CMMagazineRifleM54CMK1
    back:
    - RMCExplosiveBreachingCharge
    - RMCExplosivePlastic
