using System.IO;
using System.Linq;
using System.Numerics;
using Content.Client._RMC14.NamedItems;
using Content.Client.Humanoid;
using Content.Client.Lobby.UI.Loadouts;
using Content.Client.Lobby.UI.Roles;
using Content.Client.Message;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.Sprite;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared._RMC14.CCVar;
using Content.Shared._RMC14.LinkAccount;
using Content.Shared._RMC14.Marines.Squads;
using Content.Shared._RMC14.NamedItems;
using Content.Shared._RMC14.Prototypes;
using Content.Shared.AU14.Allegiance;
using Content.Shared.AU14.Origin;
using Content.Shared._CMU14.Threats;
using Content.Shared.CCVar;
using Content.Shared.Clothing;
using Content.Shared.GameTicking;
using Content.Shared.Guidebook;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.ContentPack;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Direction = Robust.Shared.Maths.Direction;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HumanoidProfileEditor : BoxContainer
    {
        private readonly IClientPreferencesManager _preferencesManager;
        private readonly IConfigurationManager _cfgManager;
        private readonly IEntityManager _entManager;
        private readonly IFileDialogManager _dialogManager;
        private readonly IComponentFactory _componentFactory;
        private readonly IPlayerManager _playerManager;
        private readonly IPrototypeManager _prototypeManager;
        private readonly IResourceManager _resManager;
        private readonly MarkingManager _markingManager;
        private readonly JobRequirementsManager _requirements;
        private readonly LobbyUIController _controller;

        private readonly SpriteSystem _sprite;

        // CCvar.
        private int _maxNameLength;
        private bool _allowFlavorText;

        private FlavorText.FlavorText? _flavorText;
        private TextEdit? _flavorTextEdit;

        // One at a time.
        private LoadoutWindow? _loadoutWindow;

        private bool _exporting;
        private bool _imaging;

        /// <summary>
        /// If we're attempting to save.
        /// </summary>
        public event Action? Save;

        /// <summary>
        /// Entity used for the profile editor preview
        /// </summary>
        public EntityUid PreviewDummy;

        /// <summary>
        /// Temporary override of their selected job, used to preview roles.
        /// </summary>
        public JobPrototype? JobOverride;

        /// <summary>
        /// The character slot for the current profile.
        /// </summary>
        public int? CharacterSlot;

        /// <summary>
        /// The work in progress profile being edited.
        /// </summary>
        public HumanoidCharacterProfile? Profile;

        private List<SpeciesPrototype> _species = new();

        private List<AllegiancePrototype> _allegiances = new();

        private List<OriginPrototype> _origins = new();

        private List<(string Gamemode, string JobId, RequirementsSelector Selector)> _jobPriorities = new();
        private readonly List<(string Gamemode, string Id, RequirementsSelector Selector)> _antagPreferences = new();
        private readonly List<(string Gamemode, string Id, Button Yes, Button No)> _threatPreferenceButtons = new();

        private readonly Dictionary<string, BoxContainer> _jobCategories;
        private const float HighJobPreviewScrollDelay = 2.75f;
        private const string InsurgencyDepartmentId = "AU14DepartmentColonialLiberationFront";
        private const string GamemodeInsurgency = "Insurgency";
        private const string GamemodeColonyFall = "ColonyFall";
        private const string GamemodeDistressSignal = "DistressSignal";

        private Direction _previewRotation = Direction.North;
        private int _previewJobIndex;
        private float _previewJobTimer;
        private string _previewJobSignature = string.Empty;
        private readonly List<LobbyHighJobPreviewEntry> _previewJobs = new();
        private bool _previewJobsDirty = true;

        private ColorSelectorSliders _rgbSkinColorSelector;

        private bool _isDirty;

        private static readonly ProtoId<GuideEntryPrototype> DefaultSpeciesGuidebook = "Species";
        // RMC14
        private static readonly ProtoId<TraitCategoryPrototype> SpeechTraitsCategory = "SpeechTraits";
        // RMC14

        public event Action<List<ProtoId<GuideEntryPrototype>>>? OnOpenGuidebook;

        private ISawmill _sawmill;

        public HumanoidProfileEditor(
            IClientPreferencesManager preferencesManager,
            IConfigurationManager configurationManager,
            IEntityManager entManager,
            IFileDialogManager dialogManager,
            ILogManager logManager,
            IPlayerManager playerManager,
            IPrototypeManager prototypeManager,
            IResourceManager resManager,
            JobRequirementsManager requirements,
            MarkingManager markings)
        {
            RobustXamlLoader.Load(this);
            CrtLobbyTheme.Apply(this);
            _sawmill = logManager.GetSawmill("profile.editor");
            _cfgManager = configurationManager;
            _componentFactory = IoCManager.Resolve<IComponentFactory>();
            _entManager = entManager;
            _dialogManager = dialogManager;
            _playerManager = playerManager;
            _prototypeManager = prototypeManager;
            _markingManager = markings;
            _preferencesManager = preferencesManager;
            _resManager = resManager;
            _requirements = requirements;
            _controller = UserInterfaceManager.GetUIController<LobbyUIController>();
            _sprite = _entManager.System<SpriteSystem>();

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _allowFlavorText = _cfgManager.GetCVar(CCVars.FlavorText);

            ImportButton.OnPressed += args =>
            {
                ImportProfile();
            };

            ExportButton.OnPressed += args =>
            {
                ExportProfile();
            };

            ExportImageButton.OnPressed += args =>
            {
                ExportImage();
            };

            OpenImagesButton.OnPressed += args =>
            {
                _resManager.UserData.OpenOsWindow(ContentSpriteSystem.Exports);
            };

            ResetButton.OnPressed += args =>
            {
                SetProfile((HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, _preferencesManager.Preferences?.SelectedCharacterIndex);
            };

            SaveButton.OnPressed += args =>
            {
                Save?.Invoke();
            };

            #region Left

            #region Name

            NameEdit.OnTextChanged += args => { SetName(args.Text); };
            NameEdit.IsValid = args => args.Length <= _maxNameLength;
            NameRandomize.OnPressed += args => RandomizeName();
            RandomizeEverythingButton.OnPressed += args => { RandomizeEverything(); };
            WarningLabel.SetMarkup($"[color=red]{Loc.GetString("humanoid-profile-editor-naming-rules-warning")}[/color]");

            #endregion Name

            #region Appearance

            TabContainer.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-appearance-tab"));

            #region Sex

            SexButton.OnItemSelected += args =>
            {
                SexButton.SelectId(args.Id);
                SetSex((Sex)args.Id);
            };

            #endregion Sex

            #region Age

            AgeEdit.OnTextChanged += args =>
            {
                if (!int.TryParse(args.Text, out var newAge))
                    return;

                SetAge(newAge);
            };

            #endregion Age

            #region Gender

            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int)Gender.Male);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int)Gender.Female);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int)Gender.Epicene);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int)Gender.Neuter);

            PronounsButton.OnItemSelected += args =>
            {
                PronounsButton.SelectId(args.Id);
                SetGender((Gender)args.Id);
            };

            #endregion Gender

            RefreshSpecies();

            SpeciesButton.OnItemSelected += args =>
            {
                SpeciesButton.SelectId(args.Id);
                SetSpecies(_species[args.Id].ID);
                UpdateHairPickers();
                OnSkinColorOnValueChanged();
            };

            #region Allegiance

            RefreshAllegiances();

            AllegianceButton.OnItemSelected += args =>
            {
                AllegianceButton.SelectId(args.Id);
                if (args.Id == 0)
                    SetAllegiance(null);
                else
                    SetAllegiance(_allegiances[args.Id - 1].ID);
            };

            #endregion Allegiance

            #region Origin

            RefreshOrigins();

            OriginButton.OnItemSelected += args =>
            {
                OriginButton.SelectId(args.Id);
                if (args.Id == 0)
                    SetOrigin(null);
                else
                    SetOrigin(_origins[args.Id - 1].ID);
            };

            #endregion Origin

            #region Skin

            Skin.OnValueChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            RgbSkinColorContainer.AddChild(_rgbSkinColorSelector = new ColorSelectorSliders());
            _rgbSkinColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv; // defaults color selector to HSV
            _rgbSkinColorSelector.OnColorChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            #endregion

            #region Hair

            HairStylePicker.OnMarkingSelect += newStyle =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithHairStyleName(newStyle.id));
                ReloadPreview();
            };

            HairStylePicker.OnColorChanged += newColor =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithHairColor(newColor.marking.MarkingColors[0]));
                UpdateCMarkingsHair();
                ReloadPreview();
            };

            FacialHairPicker.OnMarkingSelect += newStyle =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithFacialHairStyleName(newStyle.id));
                ReloadPreview();
            };

            FacialHairPicker.OnColorChanged += newColor =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithFacialHairColor(newColor.marking.MarkingColors[0]));
                UpdateCMarkingsFacialHair();
                ReloadPreview();
            };

            HairStylePicker.OnSlotRemove += _ =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithHairStyleName(HairStyles.DefaultHairStyle)
                );
                UpdateHairPickers();
                UpdateCMarkingsHair();
                ReloadPreview();
            };

            FacialHairPicker.OnSlotRemove += _ =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithFacialHairStyleName(HairStyles.DefaultFacialHairStyle)
                );
                UpdateHairPickers();
                UpdateCMarkingsFacialHair();
                ReloadPreview();
            };

            HairStylePicker.OnSlotAdd += delegate ()
            {
                if (Profile is null)
                    return;

                var hair = _markingManager.MarkingsByCategoryAndSpecies(MarkingCategories.Hair, Profile.Species).Keys
                    .FirstOrDefault();

                if (string.IsNullOrEmpty(hair))
                    return;

                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithHairStyleName(hair)
                );

                UpdateHairPickers();
                UpdateCMarkingsHair();
                ReloadPreview();
            };

            FacialHairPicker.OnSlotAdd += delegate ()
            {
                if (Profile is null)
                    return;

                var hair = _markingManager.MarkingsByCategoryAndSpecies(MarkingCategories.FacialHair, Profile.Species).Keys
                    .FirstOrDefault();

                if (string.IsNullOrEmpty(hair))
                    return;

                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithFacialHairStyleName(hair)
                );

                UpdateHairPickers();
                UpdateCMarkingsFacialHair();
                ReloadPreview();
            };

            #endregion Hair

            #region SpawnPriority

            foreach (var value in Enum.GetValues<SpawnPriorityPreference>())
            {
                SpawnPriorityButton.AddItem(Loc.GetString($"humanoid-profile-editor-preference-spawn-priority-{value.ToString().ToLower()}"), (int)value);
            }

            SpawnPriorityButton.OnItemSelected += args =>
            {
                SpawnPriorityButton.SelectId(args.Id);
                SetSpawnPriority((SpawnPriorityPreference)args.Id);
            };

            #endregion SpawnPriority

            #region ArmorPreference

            foreach (var value in Enum.GetValues<ArmorPreference>())
            {
                ArmorPreferenceButton.AddItem(value.ToString(), (int)value);
            }

            ArmorPreferenceButton.OnItemSelected += args =>
            {
                ArmorPreferenceButton.SelectId(args.Id);
                SetArmorPreference((ArmorPreference)args.Id);
            };

            #endregion ArmorPreference

            #region SquadPreference

            SquadPreferenceButton.AddItem(Loc.GetString("loadout-none"), 0);
            var squad = _entManager.System<SquadSystem>();
            for (var i = 0; i < squad.SquadPrototypes.Length; i++)
            {
                var squadProto = squad.SquadPrototypes[i];
                if (!squadProto.TryComp(out SquadTeamComponent? team, _componentFactory) ||
                    !team.RoundStart)
                {
                    continue;
                }

                SquadPreferenceButton.AddItem(squadProto.Name, i + 1);
            }

            SquadPreferenceButton.OnItemSelected += args =>
            {
                SquadPreferenceButton.SelectId(args.Id);

                if (args.Id == 0)
                {
                    SetSquadPreference(null);
                    return;
                }

                if (squad.SquadPrototypes.TryGetValue(args.Id - 1, out var proto))
                    SetSquadPreference(proto.ID);
            };

            #endregion SquadPreference

            #region PlaytimePerks

            PlaytimePerksButton.OnPressed += args =>
            {
                SetPlaytimePerks(args.Button.Pressed);
            };

            #endregion

            #region Xeno Prefix

            XenoPrefix.OnTextChanged += args =>
            {
                SetXenoPrefix(args.Text);
            };

            #endregion

            #region Xeno Postfix

            XenoPostfix.OnTextChanged += args =>
            {
                SetXenoPostfix(args.Text);
            };

            #endregion

            #region Eyes

            EyeColorPicker.OnEyeColorPicked += newColor =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithEyeColor(newColor));
                Markings.CurrentEyeColor = Profile.Appearance.EyeColor;
                ReloadProfilePreview();
            };

            #endregion Eyes

            #endregion Appearance

            #region Jobs

            TabContainer.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-insurgency-tab"));
            TabContainer.SetTabTitle(2, Loc.GetString("humanoid-profile-editor-colony-fall-tab"));
            TabContainer.SetTabTitle(3, Loc.GetString("humanoid-profile-editor-distress-signal-tab"));
            SetupGamemodeTabTitles();

            PreferenceUnavailableButton.AddItem(
                Loc.GetString("humanoid-profile-editor-preference-unavailable-stay-in-lobby-button"),
                (int)PreferenceUnavailableMode.StayInLobby);
            PreferenceUnavailableButton.AddItem(
                Loc.GetString("humanoid-profile-editor-preference-unavailable-spawn-as-overflow-button",
                              ("overflowJob", Loc.GetString(SharedGameTicker.FallbackOverflowJobName))),
                (int)PreferenceUnavailableMode.SpawnAsOverflow);

            PreferenceUnavailableButton.OnItemSelected += args =>
            {
                PreferenceUnavailableButton.SelectId(args.Id);
                Profile = Profile?.WithPreferenceUnavailable((PreferenceUnavailableMode)args.Id);
                SetDirty();
            };

            _jobCategories = new Dictionary<string, BoxContainer>();

            RefreshThreatPreferences();
            RefreshAntags();
            RefreshJobs();

            #endregion Jobs

            RefreshTraits();

            #region Markings

            TabContainer.SetTabTitle(5, Loc.GetString("humanoid-profile-editor-markings-tab"));

            Markings.OnMarkingAdded += OnMarkingChange;
            Markings.OnMarkingRemoved += OnMarkingChange;
            Markings.OnMarkingColorChange += OnMarkingChange;
            Markings.OnMarkingRankChange += OnMarkingChange;

            #endregion Markings

            RefreshFlavorText();

            #region Dummy

            SpriteRotateLeft.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCw();
                SetPreviewRotation(_previewRotation);
            };
            SpriteRotateRight.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCcw();
                SetPreviewRotation(_previewRotation);
            };

            #endregion Dummy

            #endregion Left

            ShowClothes.OnToggled += args =>
            {
                ReloadPreview();
            };

            SpeciesInfoButton.OnPressed += OnSpeciesInfoButtonPressed;

            // RMC14
            void SetItemName(RMCNamedItemType type, string itemName)
            {
                Profile = Profile?.WithNamedItems(new SharedRMCNamedItems
                {
                    PrimaryGunName = type == RMCNamedItemType.PrimaryGun ? itemName : Profile.NamedItems.PrimaryGunName,
                    SidearmName = type == RMCNamedItemType.Sidearm ? itemName : Profile.NamedItems.SidearmName,
                    HelmetName = type == RMCNamedItemType.Helmet ? itemName : Profile.NamedItems.HelmetName,
                    ArmorName = type == RMCNamedItemType.Armor ? itemName : Profile.NamedItems.ArmorName,
                    SentryName = type == RMCNamedItemType.Sentry ? itemName : Profile.NamedItems.SentryName,
                });
                SetDirty();
            }

            var namedItems = UserInterfaceManager.GetUIController<NamedItemsUIController>();
            TabContainer.SetTabTitle(6, Loc.GetString("rmc-ui-named-items"));
            TabContainer.SetTabVisible(6, namedItems.Available);
            NamedItems.PrimaryGun.OnTextChanged += args => SetItemName(RMCNamedItemType.PrimaryGun, args.Text);
            NamedItems.Sidearm.OnTextChanged += args => SetItemName(RMCNamedItemType.Sidearm, args.Text);
            NamedItems.Helmet.OnTextChanged += args => SetItemName(RMCNamedItemType.Helmet, args.Text);
            NamedItems.Armor.OnTextChanged += args => SetItemName(RMCNamedItemType.Armor, args.Text);
            NamedItems.Sentry.OnTextChanged += args => SetItemName(RMCNamedItemType.Sentry, args.Text);

            UpdateSpeciesGuidebookIcon();
            CrtLobbyTheme.Apply(this);
            IsDirty = false;
        }

        /// <summary>
        /// Refreshes the flavor text editor status.
        /// </summary>
        public void RefreshFlavorText()
        {
            if (_allowFlavorText)
            {
                if (_flavorText != null)
                    return;

                _flavorText = new FlavorText.FlavorText();
                TabContainer.AddChild(_flavorText);
                TabContainer.SetTabTitle(TabContainer.ChildCount - 1, Loc.GetString("humanoid-profile-editor-flavortext-tab"));
                _flavorTextEdit = _flavorText.CFlavorTextInput;

                _flavorText.OnFlavorTextChanged += OnFlavorTextChange;
            }
            else
            {
                if (_flavorText == null)
                    return;

                TabContainer.RemoveChild(_flavorText);
                _flavorText.OnFlavorTextChanged -= OnFlavorTextChange;
                _flavorText.Orphan();
                _flavorTextEdit?.Orphan();
                _flavorTextEdit = null;
                _flavorText = null;
            }
        }

        private void SetupGamemodeTabTitles()
        {
            InsurgencyTabs.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-government-jobs-tab"));
            InsurgencyTabs.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-insurgency-jobs-tab"));
            InsurgencyTabs.SetTabTitle(2, Loc.GetString("humanoid-profile-editor-civilian-jobs-tab"));
            InsurgencyTabs.SetTabTitle(3, Loc.GetString("humanoid-profile-editor-antags-tab"));

            ColonyFallTabs.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-civilian-jobs-tab"));
            ColonyFallTabs.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-threat-roles-tab"));
            ColonyFallTabs.SetTabTitle(2, Loc.GetString("humanoid-profile-editor-antags-tab"));

            DistressSignalTabs.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-government-jobs-tab"));
            DistressSignalTabs.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-threat-roles-tab"));
            DistressSignalTabs.SetTabTitle(2, Loc.GetString("humanoid-profile-editor-antags-tab"));
        }

        /// <summary>
        /// Refreshes traits selector
        /// </summary>
        public void RefreshTraits()
        {
            TraitsList.DisposeAllChildren();

            var traits = _prototypeManager.EnumeratePrototypes<TraitPrototype>().OrderBy(t => Loc.GetString(t.Name)).ToList();
            TabContainer.SetTabTitle(4, Loc.GetString("humanoid-profile-editor-traits-tab"));

            if (traits.Count < 1)
            {
                TraitsList.AddChild(new Label
                {
                    Text = Loc.GetString("humanoid-profile-editor-no-traits"),
                    FontColorOverride = Color.Gray,
                });
                return;
            }

            // Setup model
            Dictionary<string, List<string>> traitGroups = new();
            List<string> defaultTraits = new();
            traitGroups.Add(TraitCategoryPrototype.Default, defaultTraits);

            foreach (var trait in traits)
            {
                if (trait.Category == null)
                {
                    defaultTraits.Add(trait.ID);
                    continue;
                }

                if (!_prototypeManager.HasIndex(trait.Category))
                    continue;

                var group = traitGroups.GetOrNew(trait.Category);
                group.Add(trait.ID);
            }

            // Create UI view from model
            foreach (var (categoryId, categoryTraits) in traitGroups)
            {
                TraitCategoryPrototype? category = null;

                if (categoryId != TraitCategoryPrototype.Default)
                {
                    category = _prototypeManager.Index<TraitCategoryPrototype>(categoryId);
                    // Label
                    TraitsList.AddChild(new Label
                    {
                        Text = Loc.GetString(category.Name),
                        Margin = new Thickness(0, 10, 0, 0),
                        StyleClasses = { StyleBase.StyleClassLabelHeading },
                    });
                }

                // RMC14
                var selectors = new List<(TraitPreferenceSelector Selector, bool IsLanguageTrait)>();
                // RMC14
                var selectionCount = 0;

                foreach (var traitProto in categoryTraits)
                {
                    var trait = _prototypeManager.Index<TraitPrototype>(traitProto);
                    var selector = new TraitPreferenceSelector(trait);

                    selector.Preference = Profile?.TraitPreferences.Contains(trait.ID) == true;
                    if (selector.Preference)
                        selectionCount += trait.Cost;

                    selector.PreferenceChanged += preference =>
                    {
                        if (preference)
                        {
                            Profile = Profile?.WithTraitPreference(trait.ID, _prototypeManager);
                        }
                        else
                        {
                            Profile = Profile?.WithoutTraitPreference(trait.ID, _prototypeManager);
                        }

                        SetDirty();
                        RefreshTraits(); // If too many traits are selected, they will be reset to the real value.
                    };
                    // RMC14
                    selectors.Add((selector, trait.Language != null));
                    // RMC14
                }

                // Selection counter
                if (category is { MaxTraitPoints: >= 0 })
                {
                    TraitsList.AddChild(new Label
                    {
                        Text = Loc.GetString("humanoid-profile-editor-trait-count-hint", ("current", selectionCount), ("max", category.MaxTraitPoints)),
                        FontColorOverride = Color.Gray
                    });
                }

                // RMC14
                if (categoryId == SpeechTraitsCategory)
                {
                    var languageSelectors = selectors
                        .Where(selector => selector.IsLanguageTrait)
                        .Select(selector => selector.Selector)
                        .ToList();
                    var otherSelectors = selectors
                        .Where(selector => !selector.IsLanguageTrait)
                        .Select(selector => selector.Selector)
                        .ToList();

                    AddTraitSelectors(languageSelectors, selectionCount, category, "rmc-trait-group-languages");
                    AddTraitSelectors(otherSelectors, selectionCount, category, "rmc-trait-group-other-speech");
                }
                else
                {
                    AddTraitSelectors(selectors.Select(selector => selector.Selector).ToList(), selectionCount, category);
                }
                // RMC14
            }

            // RMC14
            void AddTraitSelectors(
                List<TraitPreferenceSelector> selectorsToAdd,
                int currentSelectionCount,
                TraitCategoryPrototype? currentCategory,
                string? groupLabel = null)
            {
                if (selectorsToAdd.Count == 0)
                    return;

                if (groupLabel != null)
                {
                    TraitsList.AddChild(new Label
                    {
                        Text = Loc.GetString(groupLabel),
                        Margin = new Thickness(8, 6, 0, 0),
                        FontColorOverride = Color.LightGray
                    });
                }

                foreach (var selector in selectorsToAdd)
                {
                    if (currentCategory is { MaxTraitPoints: >= 0 } &&
                        selector.Cost + currentSelectionCount > currentCategory.MaxTraitPoints)
                    {
                        selector.Checkbox.Label.FontColorOverride = Color.Red;
                    }

                    TraitsList.AddChild(selector);
                }
            }
            // RMC14
        }

        /// <summary>
        /// Refreshes the species selector.
        /// </summary>
        public void RefreshSpecies()
        {
            SpeciesButton.Clear();
            _species.Clear();

            _species.AddRange(_prototypeManager.EnumeratePrototypes<SpeciesPrototype>().Where(o => o.RoundStart));
            var speciesIds = _species.Select(o => o.ID).ToList();

            for (var i = 0; i < _species.Count; i++)
            {
                var name = Loc.GetString(_species[i].Name);
                SpeciesButton.AddItem(name, i);

                if (Profile?.Species.Equals(_species[i].ID) == true)
                {
                    SpeciesButton.SelectId(i);
                }
            }

            // If our species isn't available then reset it to default.
            if (Profile != null)
            {
                if (!speciesIds.Contains(Profile.Species))
                {
                    SetSpecies(SharedHumanoidAppearanceSystem.DefaultSpecies);
                }
            }
        }

        public void RefreshAntags()
        {
            InsurgencyAntagList.DisposeAllChildren();
            ColonyAntagList.DisposeAllChildren();
            DistressAntagList.DisposeAllChildren();
            _antagPreferences.Clear();

            PopulateAntagList(InsurgencyAntagList, GamemodeInsurgency);
            PopulateAntagList(ColonyAntagList, GamemodeColonyFall);
            PopulateAntagList(DistressAntagList, GamemodeDistressSignal);
        }

        private void PopulateAntagList(BoxContainer targetList, string gamemode)
        {
            var items = new[]
            {
                ("humanoid-profile-editor-antag-preference-yes-button", 0),
                ("humanoid-profile-editor-antag-preference-no-button", 1)
            };

            // Group antags by category
            var antagsByCategory = _prototypeManager.EnumerateCM<AntagPrototype>()
                .Where(a => a.SetPreference)
                .GroupBy(a => string.IsNullOrEmpty(a.Category) ? Loc.GetString("humanoid-profile-editor-antag-category-uncategorized") : Loc.GetString(a.Category))
                .OrderBy(g => g.Key);

            foreach (var categoryGroup in antagsByCategory)
            {
                // Create a container for the category
                var categoryContainer = new BoxContainer
                {
                    Orientation = LayoutOrientation.Vertical
                };
                categoryContainer.AddChild(new Label
                {
                    Text = categoryGroup.Key,
                    StyleClasses = { StyleNano.StyleClassLabelHeadingBigger }
                });

                foreach (var antag in categoryGroup.OrderBy(a => Loc.GetString(a.Name)))
                {
                    var antagContainer = new BoxContainer()
                    {
                        Orientation = LayoutOrientation.Horizontal,
                    };

                    var selector = new RequirementsSelector()
                    {
                        Margin = new Thickness(3f, 3f, 3f, 0f),
                    };
                    selector.OnOpenGuidebook += OnOpenGuidebook;

                    var title = Loc.GetString(antag.Name);
                    var description = Loc.GetString(antag.Objective);
                    selector.Setup(items, title, 250, description, guides: antag.Guides);
                    selector.Select(Profile?.GetAntagPreferencesForGamemode(gamemode).Contains(antag.ID) == true ? 0 : 1);

                    var requirements = _entManager.System<SharedRoleSystem>().GetAntagRequirement(antag);
                    if (!_requirements.CheckRoleRequirements(requirements, (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, out var reason))
                    {
                        selector.LockRequirements(reason);
                        Profile = Profile?.WithGamemodeAntagPreference(gamemode, antag.ID, false);
                        SetDirty();
                    }
                    else
                    {
                        selector.UnlockRequirements();
                    }

                    selector.OnSelected += preference =>
                    {
                        Profile = Profile?.WithGamemodeAntagPreference(gamemode, antag.ID, preference == 0);
                        foreach (var (otherGamemode, antagId, other) in _antagPreferences)
                        {
                            if (otherGamemode == gamemode && antagId == antag.ID)
                                other.Select(preference);
                        }

                        SetDirty();
                    };

                    _antagPreferences.Add((gamemode, antag.ID, selector));
                    antagContainer.AddChild(selector);

                    antagContainer.AddChild(new Button()
                    {
                        Disabled = true,
                        Text = Loc.GetString("loadout-window"),
                        HorizontalAlignment = HAlignment.Right,
                        Margin = new Thickness(3f, 0f, 0f, 0f),
                    });

                    categoryContainer.AddChild(antagContainer);
                }

                targetList.AddChild(categoryContainer);
            }

            CrtLobbyTheme.Apply(targetList);
        }

        private void SetDirty()
        {
            MarkPreviewJobsDirty();

            // If it equals default then reset the button.
            if (Profile == null || _preferencesManager.Preferences?.SelectedCharacter.MemberwiseEquals(Profile) == true)
            {
                IsDirty = false;
                return;
            }

            // TODO: Check if profile matches default.
            IsDirty = true;
        }

        /// <summary>
        /// Refresh all loadouts.
        /// </summary>
        public void RefreshLoadouts()
        {
            _loadoutWindow?.Close();
        }

        public void RefreshRMC(SharedRMCPatronTier? tier)
        {
            TabContainer.SetTabVisible(6, tier is { NamedItems: true });
        }

        /// <summary>
        /// Reloads the entire dummy entity for preview.
        /// </summary>
        /// <remarks>
        /// This is expensive so not recommended to run if you have a slider.
        /// </remarks>
        private void ReloadPreview(bool updateDirty = true)
        {
            _entManager.DeleteEntity(PreviewDummy);
            PreviewDummy = EntityUid.Invalid;

            if (Profile == null || !_prototypeManager.HasIndex(Profile.Species))
            {
                UpdatePreviewJobLabel(null);
                return;
            }

            var previewEntry = GetCurrentPreviewJob();
            var previewJob = JobOverride ?? previewEntry?.Job;
            PreviewDummy = _controller.LoadProfileEntity(Profile, previewJob, ShowClothes.Pressed);
            SpriteView.SetEntity(PreviewDummy);
            _entManager.System<MetaDataSystem>().SetEntityName(PreviewDummy, Profile.Name);
            UpdatePreviewJobLabel(previewEntry);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            if (updateDirty)
                SetDirty();
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            UpdatePreviewJobRotation(args.DeltaSeconds);
        }

        private void UpdatePreviewJobRotation(float deltaSeconds)
        {
            if (Profile == null ||
                JobOverride != null ||
                !ShowClothes.Pressed)
            {
                ResetPreviewJobRotation();
                UpdatePreviewJobLabel(null);
                return;
            }

            if (_previewJobsDirty && RefreshPreviewJobs())
            {
                ReloadPreview(false);
                return;
            }

            var entries = _previewJobs;
            if (entries.Count <= 1)
            {
                if (entries.Count == 1)
                    UpdatePreviewJobLabel(entries[0]);

                return;
            }

            _previewJobTimer += deltaSeconds;
            if (_previewJobTimer < HighJobPreviewScrollDelay)
                return;

            _previewJobTimer -= HighJobPreviewScrollDelay;
            _previewJobIndex = (_previewJobIndex + 1) % entries.Count;
            ReloadPreview(false);
        }

        private LobbyHighJobPreviewEntry? GetCurrentPreviewJob()
        {
            if (Profile == null ||
                JobOverride != null ||
                !ShowClothes.Pressed)
            {
                return null;
            }

            var entries = GetPreviewJobs();

            if (entries.Count == 0)
            {
                _previewJobIndex = 0;
                return null;
            }

            _previewJobIndex %= entries.Count;
            return entries[_previewJobIndex];
        }

        private void ResetPreviewJobRotation()
        {
            _previewJobIndex = 0;
            _previewJobTimer = 0;
            _previewJobSignature = string.Empty;
            _previewJobs.Clear();
            _previewJobsDirty = true;
        }

        private IReadOnlyList<LobbyHighJobPreviewEntry> GetPreviewJobs()
        {
            if (_previewJobsDirty)
                RefreshPreviewJobs();

            return _previewJobs;
        }

        private bool RefreshPreviewJobs()
        {
            var previousSignature = _previewJobSignature;

            _previewJobs.Clear();
            if (Profile != null)
                _previewJobs.AddRange(LobbyHighJobPreview.GetHighPriorityJobs(Profile, _prototypeManager));

            _previewJobSignature = LobbyHighJobPreview.GetSignature(_previewJobs);
            _previewJobsDirty = false;

            var changed = previousSignature != _previewJobSignature;
            if (changed)
            {
                _previewJobIndex = 0;
                _previewJobTimer = 0;
            }

            return changed;
        }

        private void MarkPreviewJobsDirty()
        {
            _previewJobsDirty = true;
        }

        private void UpdatePreviewJobLabel(LobbyHighJobPreviewEntry? entry)
        {
            if (!ShowClothes.Pressed)
            {
                PreviewJobLabel.Visible = false;
                PreviewJobLabel.Text = string.Empty;
                return;
            }

            if (JobOverride != null)
            {
                PreviewJobLabel.Text = GetJobDisplayName(JobOverride);
                PreviewJobLabel.Visible = true;
                return;
            }

            PreviewJobLabel.Text = entry?.DisplayName ?? string.Empty;
            PreviewJobLabel.Visible = entry != null;
        }

        /// <summary>
        /// Resets the profile to the defaults.
        /// </summary>
        public void ResetToDefault()
        {
            SetProfile(
                (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter,
                _preferencesManager.Preferences?.SelectedCharacterIndex);
        }

        /// <summary>
        /// Sets the editor to the specified profile with the specified slot.
        /// </summary>
        public void SetProfile(HumanoidCharacterProfile? profile, int? slot)
        {
            Profile = profile?.Clone();
            CharacterSlot = slot;
            IsDirty = false;
            JobOverride = null;
            ResetPreviewJobRotation();

            UpdateNameEdit();
            UpdateFlavorTextEdit();
            UpdateSexControls();
            UpdateGenderControls();
            UpdateSkinColor();
            UpdateSpawnPriorityControls();
            UpdateArmorPreferenceControls();
            UpdateSquadPreferenceControls();
            UpdateAgeEdit();
            UpdateEyePickers();
            UpdateSaveButton();
            UpdateMarkings();
            UpdateHairPickers();
            UpdateCMarkingsHair();
            UpdateCMarkingsFacialHair();
            UpdateNamedItems();
            UpdatePlaytimePerks();
            UpdateXenoPrefix();
            UpdateXenoPostfix();
            UpdateAllegianceControls();
            UpdateOriginControls();
            RefreshThreatPreferences();

            RefreshAntags();
            RefreshJobs();
            RefreshLoadouts();
            RefreshSpecies();
            RefreshAllegiances();
            RefreshOrigins();
            RefreshTraits();
            RefreshFlavorText();
            ReloadPreview();

            if (Profile != null)
            {
                PreferenceUnavailableButton.SelectId((int)Profile.PreferenceUnavailable);
            }
        }


        /// <summary>
        /// A slim reload that only updates the entity itself and not any of the job entities, etc.
        /// </summary>
        private void ReloadProfilePreview()
        {
            if (Profile == null || !_entManager.EntityExists(PreviewDummy))
                return;

            _entManager.System<HumanoidAppearanceSystem>().LoadProfile(PreviewDummy, Profile);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        private void OnSpeciesInfoButtonPressed(BaseButton.ButtonEventArgs args)
        {
            // TODO GUIDEBOOK
            // make the species guide book a field on the species prototype.
            // I.e., do what jobs/antags do.

            var guidebookController = UserInterfaceManager.GetUIController<GuidebookUIController>();
            var species = Profile?.Species ?? SharedHumanoidAppearanceSystem.DefaultSpecies;
            var page = DefaultSpeciesGuidebook;
            if (_prototypeManager.HasIndex<GuideEntryPrototype>(species))
                page = new ProtoId<GuideEntryPrototype>(species.Id); // Gross. See above todo comment.

            if (_prototypeManager.TryIndex(DefaultSpeciesGuidebook, out var guideRoot))
            {
                var dict = new Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry>();
                dict.Add(DefaultSpeciesGuidebook, guideRoot);
                //TODO: Don't close the guidebook if its already open, just go to the correct page
                guidebookController.OpenGuidebook(dict, includeChildren: true, selected: page);
            }
        }

        /// <summary>
        /// Refreshes all job selectors.
        /// </summary>
        public void RefreshJobs()
        {
            InsurgencyGovernmentJobList.DisposeAllChildren();
            InsurgencyInsurgentJobList.DisposeAllChildren();
            InsurgencyCivilianJobList.DisposeAllChildren();
            ColonyCivilianJobList.DisposeAllChildren();
            ColonyThreatJobList.DisposeAllChildren();
            DistressGovernmentJobList.DisposeAllChildren();
            DistressThreatJobList.DisposeAllChildren();
            _jobCategories.Clear();
            _jobPriorities.Clear();

            // Get all displayed departments
            var departments = new List<DepartmentPrototype>();
            foreach (var department in _prototypeManager.EnumeratePrototypes<DepartmentPrototype>())
            {
                if (department.EditorHidden)
                    continue;

                departments.Add(department);
            }

            departments.Sort(CompareDepartmentsForCharacterSetup);

            var items = new[]
            {
                ("humanoid-profile-editor-job-priority-never-button", (int) JobPriority.Never),
                ("humanoid-profile-editor-job-priority-low-button", (int) JobPriority.Low),
                ("humanoid-profile-editor-job-priority-medium-button", (int) JobPriority.Medium),
                ("humanoid-profile-editor-job-priority-high-button", (int) JobPriority.High),
            };

            foreach (var department in departments)
            {
                var departmentName = Loc.GetString(department.Name);

                var jobs = department.Roles.Select(jobId => _prototypeManager.Index(jobId))
                    .Where(job => job.SetPreference)
                    .Where(job => !job.Hidden)
                    .ToArray();

                Array.Sort(jobs, (a, b) =>
                {
                    var group = GetJobSortGroup(department, a).CompareTo(GetJobSortGroup(department, b));
                    return group != 0 ? group : JobUIComparer.Instance.Compare(a, b);
                });

                foreach (var job in jobs)
                {
                    foreach (var (targetList, gamemode, sectionKey, sectionTitle) in GetJobSections(department, job, departmentName))
                    {
                        AddJobSelector(
                            targetList,
                            gamemode,
                            sectionKey,
                            sectionTitle,
                            department.IsCM && !department.Hidden,
                            departmentName,
                            items,
                            job);
                    }
                }
            }

            foreach (var list in GetGamemodeJobLists())
            {
                CrtLobbyTheme.Apply(list);
            }

            UpdateJobPriorities();
        }

        private void AddJobSelector(
            BoxContainer targetList,
            string gamemode,
            string sectionKey,
            string sectionTitle,
            bool visible,
            string departmentName,
            (string, int)[] items,
            JobPrototype job)
        {
            var category = GetOrCreateJobCategory(
                sectionKey,
                targetList,
                sectionTitle,
                visible,
                departmentName);

            var jobContainer = new BoxContainer()
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            var selector = new RequirementsSelector()
            {
                Margin = new Thickness(3f, 3f, 3f, 0f),
                HorizontalExpand = true,
            };
            selector.OnOpenGuidebook += OnOpenGuidebook;

            var icon = new TextureRect
            {
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center
            };
            var jobIcon = _prototypeManager.Index(job.Icon);
            icon.Texture = _sprite.Frame0(jobIcon.Icon);
            selector.Setup(items, GetJobDisplayName(job), 220, job.LocalizedDescription, icon, job.Guides);

            if (!_requirements.IsAllowed(job, (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, out var reason))
            {
                selector.LockRequirements(reason);
            }
            else
            {
                selector.UnlockRequirements();
            }

            selector.OnSelected += selectedPrio =>
            {
                var selectedJobPrio = (JobPriority)selectedPrio;
                Profile = Profile?.WithGamemodeJobPriority(gamemode, job.ID, selectedJobPrio);

                foreach (var (otherGamemode, jobId, other) in _jobPriorities)
                {
                    if (otherGamemode != gamemode)
                        continue;

                    // Sync other selectors with the same job in case of multiple department jobs
                    if (jobId == job.ID)
                    {
                        other.Select(selectedPrio);
                        continue;
                    }

                    if (selectedJobPrio != JobPriority.High || (JobPriority)other.Selected != JobPriority.High)
                        continue;

                    // Lower any other high priorities to medium.
                    other.Select((int)JobPriority.Medium);
                    Profile = Profile?.WithGamemodeJobPriority(gamemode, jobId, JobPriority.Medium);
                }

                // TODO: Only reload on high change (either to or from).
                ReloadPreview();

                UpdateJobPriorities();
                SetDirty();
            };

            var loadoutWindowBtn = new Button()
            {
                Text = Loc.GetString("loadout-window"),
                HorizontalAlignment = HAlignment.Right,
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(3f, 3f, 0f, 0f),
                MinWidth = 110,
                StyleClasses = { StyleNano.StyleClassCrtButton }
            };

            var collection = IoCManager.Instance!;
            var protoManager = collection.Resolve<IPrototypeManager>();

            // If no loadout found then disabled button
            var (key, proto) = LoadoutSystem.GetJobLoadoutInfo(job.ID, protoManager);
            if (proto == null)
            {
                loadoutWindowBtn.Disabled = true;
            }
            else
            {
                loadoutWindowBtn.OnPressed += args =>
               {
                   RoleLoadout? loadout = null;
                   // Clone so we don't modify the underlying loadout.
                   if (Profile?.Loadouts.TryGetValue(key, out var existing) == true)
                       loadout = existing.Clone();

                   if (loadout == null)
                   {
                       loadout = new RoleLoadout(proto.ID);
                       loadout.SetDefault(Profile, _playerManager.LocalSession, _prototypeManager);
                   }
                   OpenLoadout(job, loadout, proto);
               };
            }

            _jobPriorities.Add((gamemode, job.ID, selector));
            jobContainer.AddChild(selector);
            jobContainer.AddChild(loadoutWindowBtn);
            CrtLobbyTheme.Apply(jobContainer);
            category.AddChild(jobContainer);
        }

        private IEnumerable<BoxContainer> GetGamemodeJobLists()
        {
            yield return InsurgencyGovernmentJobList;
            yield return InsurgencyInsurgentJobList;
            yield return InsurgencyCivilianJobList;
            yield return ColonyCivilianJobList;
            yield return ColonyThreatJobList;
            yield return DistressGovernmentJobList;
            yield return DistressThreatJobList;
        }

        private BoxContainer GetOrCreateJobCategory(
            string key,
            BoxContainer targetList,
            string title,
            bool visible,
            string departmentName)
        {
            if (_jobCategories.TryGetValue(key, out var category))
                return category;

            category = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                Name = key,
                ToolTip = Loc.GetString("humanoid-profile-editor-jobs-amount-in-department-tooltip",
                    ("departmentName", departmentName)),
                Visible = visible,
            };

            if (targetList.Children.Any(child => child.Visible) && visible)
            {
                category.AddChild(new Control
                {
                    MinSize = new Vector2(0, 14),
                });
            }

            category.AddChild(new PanelContainer
            {
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = StyleNano.CrtPanelBackgroundAlt,
                    BorderColor = StyleNano.CrtGreenDim,
                    BorderThickness = new Thickness(0, 0, 0, 1),
                    ContentMarginTopOverride = 3,
                    ContentMarginBottomOverride = 3
                },
                Children =
                {
                    new Label
                    {
                        Text = title,
                        Margin = new Thickness(6f, 0, 0, 0),
                        StyleClasses = { StyleNano.StyleClassCrtHeading }
                    }
                }
            });

            _jobCategories[key] = category;
            targetList.AddChild(category);
            return category;
        }

        private IEnumerable<(BoxContainer Target, string Gamemode, string Key, string Title)> GetJobSections(
            DepartmentPrototype department,
            JobPrototype job,
            string departmentName)
        {
            if (department.Faction == "govfor")
            {
                var (segmentKey, segmentTitle) = GetMilitaryJobSegment(job);
                yield return (InsurgencyGovernmentJobList,
                    GamemodeInsurgency,
                    $"insurgency-govfor-{segmentKey}",
                    Loc.GetString("humanoid-profile-editor-government-forces-label", ("segmentTitle", segmentTitle)));
                yield return (DistressGovernmentJobList,
                    GamemodeDistressSignal,
                    $"distress-govfor-{segmentKey}",
                    Loc.GetString("humanoid-profile-editor-government-forces-label", ("segmentTitle", segmentTitle)));
                yield break;
            }

            if (department.Faction == "opfor")
            {
                yield break;
            }

            if (IsInsurgencyDepartment(department))
            {
                yield return (InsurgencyInsurgentJobList,
                    GamemodeInsurgency,
                    $"insurgency-jobs-{department.ID}",
                    department.CustomName ?? Loc.GetString("humanoid-profile-editor-department-jobs-label", ("departmentName", departmentName)));
                yield break;
            }

            if (department.Faction == "colonist")
            {
                var title = department.CustomName ?? Loc.GetString("humanoid-profile-editor-department-jobs-label", ("departmentName", departmentName));
                yield return (InsurgencyCivilianJobList,
                    GamemodeInsurgency,
                    $"insurgency-civilian-{department.ID}",
                    title);
                yield return (ColonyCivilianJobList,
                    GamemodeColonyFall,
                    $"colony-civilian-{department.ID}",
                    title);
                yield break;
            }

            if (!IsRoundStartThreatAssignmentJob(job))
                yield break;

            yield return (ColonyThreatJobList,
                GamemodeColonyFall,
                "colony-threat",
                "Threat Jobs");
            yield return (DistressThreatJobList,
                GamemodeDistressSignal,
                "distress-threat",
                "Threat Jobs");
        }

        private static int CompareDepartmentsForCharacterSetup(DepartmentPrototype? x, DepartmentPrototype? y)
        {
            if (ReferenceEquals(x, y))
                return 0;

            if (ReferenceEquals(null, y))
                return 1;

            if (ReferenceEquals(null, x))
                return -1;

            var colonyGroup = GetColonyDepartmentSortGroup(x).CompareTo(GetColonyDepartmentSortGroup(y));
            return colonyGroup != 0 ? colonyGroup : DepartmentUIComparer.Instance.Compare(x, y);
        }

        private static int GetColonyDepartmentSortGroup(DepartmentPrototype department)
        {
            return department.ID switch
            {
                "AU14DepartmentColonyCommand" => 0,
                "AU14DepartmentColonySecurity" => 1,
                "AU14DepartmentColonyMedical" => 2,
                "AU14DepartmentEngineering" => 3,
                "AU14DepartmentCivilian" => 4,
                "AU14DepartmentCriminal" => 5,
                "AU14DepartmentCorporate" => 6,
                "AU14DepartmentAmbassadors" => 7,
                "AU14DepartmentOrbital" => 8,
                _ => 100,
            };
        }

        private static bool IsInsurgencyDepartment(DepartmentPrototype department)
        {
            return department.ID == InsurgencyDepartmentId;
        }

        private static bool IsRoundStartThreatAssignmentJob(JobPrototype job)
        {
            return job.ID is
                "AU14JobThreatLeader" or
                "AU14JobThreatMember" or
                "AU14JobThirdPartyLeader" or
                "AU14JobThirdPartyMember";
        }

        private static (string Key, string Title) GetMilitaryJobSegment(JobPrototype job)
        {
            var id = job.ID;
            var name = job.LocalizedName;

            if (job.MarineAuthorityLevel > 0
                    || ContainsAny(id, name, "PlatCo", "Adjutant", "PlatOp", "Commander", "Command", "Advisor"))
                return ("command", Loc.GetString("humanoid-profile-editor-segment-command"));

            if (ContainsAny(id, name, "Pilot", "Dropship", "Crew Chief", "DCC"))
                return ("flight", Loc.GetString("humanoid-profile-editor-segment-flight"));

            if (ContainsAny(id, name, "Officer", "Chief")) // after Crew Chief
                return ("officer", Loc.GetString("humanoid-profile-editor-segment-officer"));

            if (ContainsAny(id, name, "Doctor", "AuxTech", "Police", "VehicleCrewman", "Synth", "Working Joe", "Auxiliary"))
                return ("support", Loc.GetString("humanoid-profile-editor-segment-support"));

            if (ContainsAny(id, name, "Leader", "Sergeant", "RadioTelephone"))
                return ("leader", Loc.GetString("humanoid-profile-editor-segment-leader"));

            return ("line", Loc.GetString("humanoid-profile-editor-segment-line"));
        }

        private static int GetJobSortGroup(DepartmentPrototype department, JobPrototype job)
        {
            if (department.Faction != "govfor" && department.Faction != "opfor")
                return 0;

            return GetMilitaryJobSegment(job).Key switch
            {
                "command" => 0,
                "officer" => 1,
                "flight" => 2,
                "support" => 3,
                "leader" => 4,
                _ => 5,
            };
        }

        private static string GetJobDisplayName(JobPrototype job)
        {
            return LobbyHighJobPreview.GetDisplayJobName(job);
        }

        private static bool ContainsAny(string id, string name, params string[] needles)
        {
            foreach (var needle in needles)
            {
                if (id.Contains(needle, StringComparison.OrdinalIgnoreCase) ||
                    name.Contains(needle, StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }

            return false;
        }

        private void OpenLoadout(JobPrototype? jobProto, RoleLoadout roleLoadout, RoleLoadoutPrototype roleLoadoutProto)
        {
            _loadoutWindow?.Close();
            _loadoutWindow = null;
            var collection = IoCManager.Instance;

            if (collection == null || _playerManager.LocalSession == null || Profile == null || jobProto == null)
                return;

            JobOverride = jobProto;
            var session = _playerManager.LocalSession;

            _loadoutWindow = new LoadoutWindow(Profile, roleLoadout, roleLoadoutProto, _playerManager.LocalSession, collection)
            {
                Title = jobProto.ID + "-loadout",
            };

            // Refresh the buttons etc.
            _loadoutWindow.RefreshLoadouts(roleLoadout, session, collection);
            _loadoutWindow.OpenCenteredLeft();

            var concreteKey = LoadoutSystem.GetJobPrototype(jobProto.ID);
            _loadoutWindow.OnNameChanged += name =>
            {
                roleLoadout.EntityName = name;
                Profile = Profile.WithLoadout(concreteKey, roleLoadout);
                SetDirty();
            };

            _loadoutWindow.OnLoadoutPressed += (loadoutGroup, loadoutProto) =>
            {
                roleLoadout.AddLoadout(loadoutGroup, loadoutProto, _prototypeManager);
                _loadoutWindow.RefreshLoadouts(roleLoadout, session, collection);
                Profile = Profile?.WithLoadout(concreteKey, roleLoadout);
                ReloadPreview();
            };

            _loadoutWindow.OnLoadoutUnpressed += (loadoutGroup, loadoutProto) =>
            {
                roleLoadout.RemoveLoadout(loadoutGroup, loadoutProto, _prototypeManager);
                _loadoutWindow.RefreshLoadouts(roleLoadout, session, collection);
                Profile = Profile?.WithLoadout(concreteKey, roleLoadout);
                ReloadPreview();
            };

            JobOverride = jobProto;
            ReloadPreview();

            _loadoutWindow.OnClose += () =>
            {
                JobOverride = null;
                ReloadPreview();
            };

            if (Profile is null)
                return;

            UpdateJobPriorities();
        }

        private void OnFlavorTextChange(string content)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithFlavorText(content);
            SetDirty();
        }

        private void OnMarkingChange(MarkingSet markings)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithMarkings(markings.GetForwardEnumerator().ToList()));
            ReloadProfilePreview();
        }

        private void OnSkinColorOnValueChanged()
        {
            if (Profile is null) return;

            var skin = _prototypeManager.Index<SpeciesPrototype>(Profile.Species).SkinColoration;

            switch (skin)
            {
                case HumanoidSkinColor.HumanToned:
                    {
                        if (!Skin.Visible)
                        {
                            Skin.Visible = true;
                            RgbSkinColorContainer.Visible = false;
                        }

                        var color = SkinColor.HumanSkinTone((int)Skin.Value);

                        Markings.CurrentSkinColor = color;
                        Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(color));//
                        break;
                    }
                case HumanoidSkinColor.Hues:
                    {
                        if (!RgbSkinColorContainer.Visible)
                        {
                            Skin.Visible = false;
                            RgbSkinColorContainer.Visible = true;
                        }

                        Markings.CurrentSkinColor = _rgbSkinColorSelector.Color;
                        Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(_rgbSkinColorSelector.Color));
                        break;
                    }
                case HumanoidSkinColor.TintedHues:
                    {
                        if (!RgbSkinColorContainer.Visible)
                        {
                            Skin.Visible = false;
                            RgbSkinColorContainer.Visible = true;
                        }

                        var color = SkinColor.TintedHues(_rgbSkinColorSelector.Color);

                        Markings.CurrentSkinColor = color;
                        Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(color));
                        break;
                    }
                case HumanoidSkinColor.VoxFeathers:
                    {
                        if (!RgbSkinColorContainer.Visible)
                        {
                            Skin.Visible = false;
                            RgbSkinColorContainer.Visible = true;
                        }

                        var color = SkinColor.ClosestVoxColor(_rgbSkinColorSelector.Color);

                        Markings.CurrentSkinColor = color;
                        Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(color));
                        break;
                    }
            }

            ReloadProfilePreview();
        }

        [System.Obsolete]
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing)
                return;

            _loadoutWindow?.Close();
            _loadoutWindow = null;
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            ReloadPreview();
        }

        protected override void ExitedTree()
        {
            base.ExitedTree();
            _entManager.DeleteEntity(PreviewDummy);
            PreviewDummy = EntityUid.Invalid;
        }

        private void SetAge(int newAge)
        {
            Profile = Profile?.WithAge(newAge);
            ReloadPreview();
        }

        private void SetSex(Sex newSex)
        {
            Profile = Profile?.WithSex(newSex);
            // for convenience, default to most common gender when new sex is selected
            switch (newSex)
            {
                case Sex.Male:
                    Profile = Profile?.WithGender(Gender.Male);
                    break;
                case Sex.Female:
                    Profile = Profile?.WithGender(Gender.Female);
                    break;
                default:
                    Profile = Profile?.WithGender(Gender.Epicene);
                    break;
            }

            UpdateGenderControls();
            Markings.SetSex(newSex);
            ReloadPreview();
        }

        private void SetGender(Gender newGender)
        {
            Profile = Profile?.WithGender(newGender);
            ReloadPreview();
        }

        private void SetSpecies(string newSpecies)
        {
            Profile = Profile?.WithSpecies(newSpecies);
            OnSkinColorOnValueChanged(); // Species may have special color prefs, make sure to update it.
            Markings.SetSpecies(newSpecies); // Repopulate the markings tab as well.
            // In case there's job restrictions for the species
            RefreshJobs();
            // In case there's species restrictions for loadouts
            RefreshLoadouts();
            UpdateSexControls(); // update sex for new species
            UpdateSpeciesGuidebookIcon();
            ReloadPreview();
        }

        private void SetName(string newName)
        {
            Profile = Profile?.WithName(newName);
            SetDirty();

            if (!IsDirty)
                return;

            _entManager.System<MetaDataSystem>().SetEntityName(PreviewDummy, newName);
        }

        private void SetSpawnPriority(SpawnPriorityPreference newSpawnPriority)
        {
            Profile = Profile?.WithSpawnPriorityPreference(newSpawnPriority);
            SetDirty();
        }

        private void SetArmorPreference(ArmorPreference newArmorPreference)
        {
            Profile = Profile?.WithArmorPreference(newArmorPreference);
            SetDirty();
        }

        private void SetSquadPreference(EntProtoId<SquadTeamComponent>? newSquadPreference)
        {
            Profile = Profile?.WithSquadPreference(newSquadPreference);
            SetDirty();
        }

        private void SetPlaytimePerks(bool playtimePerks)
        {
            Profile = Profile?.WithPlaytimePerks(playtimePerks);
            SetDirty();
        }

        private void SetXenoPrefix(string prefix)
        {
            Profile = Profile?.WithXenoPrefix(prefix);
            SetDirty();
        }

        private void SetXenoPostfix(string postfix)
        {
            Profile = Profile?.WithXenoPostfix(postfix);
            SetDirty();
        }

        private void SetAllegiance(string? allegiance)
        {
            Profile = Profile?.WithAllegiance(allegiance != null ? new Robust.Shared.Prototypes.ProtoId<AllegiancePrototype>(allegiance) : (ProtoId<AllegiancePrototype>?)null);
            SetDirty();
        }

        private void SetOrigin(string? origin)
        {
            Profile = Profile?.WithOrigin(origin != null ? new Robust.Shared.Prototypes.ProtoId<OriginPrototype>(origin) : (ProtoId<OriginPrototype>?)null);
            SetDirty();
        }

        private void SetThreatPreference(string gamemode, string threat, bool pref)
        {
            Profile = Profile?.WithGamemodeThreatPreference(gamemode, new ProtoId<ThreatPrototype>(threat), pref);
            SetDirty();
        }

        /// <summary>
        /// Refreshes the allegiance selector.
        /// </summary>
        public void RefreshAllegiances()
        {
            AllegianceButton.Clear();
            _allegiances.Clear();

            AllegianceButton.AddItem(Loc.GetString("humanoid-profile-editor-allegiance-none"), 0);
            _allegiances.AddRange(_prototypeManager.EnumeratePrototypes<AllegiancePrototype>()
                    .Where(o => o.RoundStart)
                    .OrderBy(o => Loc.GetString(o.Name)));

            for (var i = 0; i < _allegiances.Count; i++)
            {
                var name = Loc.GetString(_allegiances[i].Name);
                AllegianceButton.AddItem(name, i + 1);

                if (Profile?.Allegiance?.Id == _allegiances[i].ID)
                {
                    AllegianceButton.SelectId(i + 1);
                }
            }

            if (Profile?.Allegiance == null)
            {
                AllegianceButton.SelectId(0);
            }
        }

        /// <summary>
        /// Refreshes the origin selector.
        /// </summary>
        public void RefreshOrigins()
        {
            OriginButton.Clear();
            _origins.Clear();

            OriginButton.AddItem(Loc.GetString("humanoid-profile-editor-origin-none"), 0);
            _origins.AddRange(_prototypeManager.EnumeratePrototypes<OriginPrototype>()
                .Where(o => o.RoundStart)
                .OrderBy(o => Loc.GetString(o.Name)));

            for (var i = 0; i < _origins.Count; i++)
            {
                var name = Loc.GetString(_origins[i].Name);
                OriginButton.AddItem(name, i + 1);

                if (Profile?.Origin?.Id == _origins[i].ID)
                {
                    OriginButton.SelectId(i + 1);
                }
            }

            if (Profile?.Origin == null)
            {
                OriginButton.SelectId(0);
            }
        }

        private void UpdateAllegianceControls()
        {
            if (Profile?.Allegiance == null)
            {
                AllegianceButton.SelectId(0);
                return;
            }

            for (var i = 0; i < _allegiances.Count; i++)
            {
                if (_allegiances[i].ID == Profile.Allegiance.Value.Id)
                {
                    AllegianceButton.SelectId(i + 1);
                    return;
                }
            }

            AllegianceButton.SelectId(0);
        }

        private void UpdateOriginControls()
        {
            if (Profile?.Origin == null)
            {
                OriginButton.SelectId(0);
                return;
            }

            for (var i = 0; i < _origins.Count; i++)
            {
                if (_origins[i].ID == Profile.Origin.Value.Id)
                {
                    OriginButton.SelectId(i + 1);
                    return;
                }
            }

            OriginButton.SelectId(0);
        }

        public void RefreshThreatPreferences()
        {
            ColonyThreatPreferenceList.DisposeAllChildren();
            DistressThreatPreferenceList.DisposeAllChildren();
            _threatPreferenceButtons.Clear();

            PopulateThreatPreferenceList(ColonyThreatPreferenceList, GamemodeColonyFall);
            PopulateThreatPreferenceList(DistressThreatPreferenceList, GamemodeDistressSignal);
            SyncThreatPreferenceButtons();
            CrtLobbyTheme.Apply(ColonyThreatPreferenceList);
            CrtLobbyTheme.Apply(DistressThreatPreferenceList);
        }

        private void PopulateThreatPreferenceList(BoxContainer targetList, string gamemode)
        {
            targetList.AddChild(new Label
            {
                Text = "THREATS",
                Margin = new Thickness(6f, 4f, 0f, 6f),
                StyleClasses = { StyleNano.StyleClassCrtHeading }
            });

            foreach (var threat in _prototypeManager.EnumeratePrototypes<ThreatPrototype>()
                         .Where(threat => IsThreatVisibleForGamemode(threat, gamemode))
                         .OrderBy(GetThreatDisplayName))
            {
                var row = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    Margin = new Thickness(6f, 0f, 6f, 4f),
                    SeparationOverride = 4
                };

                row.AddChild(new Label
                {
                    Text = GetThreatDisplayName(threat),
                    HorizontalExpand = true,
                    ClipText = true,
                    VerticalAlignment = VAlignment.Center,
                    ToolTip = threat.ID,
                    StyleClasses = { StyleNano.StyleClassCrtText }
                });

                var yes = MakeThreatPreferenceButton(Loc.GetString("humanoid-profile-editor-antag-preference-yes-button"));
                var no = MakeThreatPreferenceButton(Loc.GetString("humanoid-profile-editor-antag-preference-no-button"));
                var threatId = threat.ID;

                yes.OnPressed += _ =>
                {
                    SetThreatPreference(gamemode, threatId, true);
                    SyncThreatPreferenceButtons();
                };
                no.OnPressed += _ =>
                {
                    SetThreatPreference(gamemode, threatId, false);
                    SyncThreatPreferenceButtons();
                };

                _threatPreferenceButtons.Add((gamemode, threatId, yes, no));
                row.AddChild(yes);
                row.AddChild(no);
                targetList.AddChild(row);
            }
        }

        private Button MakeThreatPreferenceButton(string text)
        {
            return new Button
            {
                Text = text,
                ToggleMode = true,
                MinWidth = 54,
                StyleClasses = { StyleNano.StyleClassCrtButton }
            };
        }

        private void SyncThreatPreferenceButtons()
        {
            foreach (var (gamemode, threatId, yes, no) in _threatPreferenceButtons)
            {
                var selected = Profile?.GetThreatPreferencesForGamemode(gamemode).Any(id => id.Id == threatId) == true;
                yes.Pressed = selected;
                no.Pressed = !selected;
            }
        }

        private static string GetThreatDisplayName(ThreatPrototype threat)
        {
            var id = threat.ID;
            var markerSuffix = "";

            if (id.EndsWith("OnMarker", StringComparison.OrdinalIgnoreCase))
            {
                id = id.Substring(0, id.Length - "OnMarker".Length);
                markerSuffix = " (Marker)";
            }

            if (id.EndsWith("CF", StringComparison.OrdinalIgnoreCase))
                id = id.Substring(0, id.Length - 2);

            if (id.EndsWith("Threat", StringComparison.OrdinalIgnoreCase))
                id = id.Substring(0, id.Length - "Threat".Length);

            if (id.Equals("xeno", StringComparison.OrdinalIgnoreCase))
                return "Xenomorph" + markerSuffix;

            if (id.Equals("ape", StringComparison.OrdinalIgnoreCase))
                return "Apes" + markerSuffix;

            if (id.Equals("cultist", StringComparison.OrdinalIgnoreCase))
                return "Cultists" + markerSuffix;

            if (id.Equals("wendigo", StringComparison.OrdinalIgnoreCase))
                return "Wendigo" + markerSuffix;

            return HumanizePrototypeId(id) + markerSuffix;
        }

        private static bool IsThreatVisibleForGamemode(ThreatPrototype threat, string gamemode)
        {
            if (threat.BlacklistedGamemodes.Any(mode => mode.Equals(gamemode, StringComparison.OrdinalIgnoreCase)))
                return false;

            return threat.whitelistedgamemodes.Count == 0 ||
                   threat.whitelistedgamemodes.Any(mode => mode.Equals(gamemode, StringComparison.OrdinalIgnoreCase));
        }

        private static string HumanizePrototypeId(string id)
        {
            var builder = new System.Text.StringBuilder(id.Length + 8);

            for (var i = 0; i < id.Length; i++)
            {
                var current = id[i];
                if (i > 0)
                {
                    var previous = id[i - 1];
                    var nextIsLower = i + 1 < id.Length && char.IsLower(id[i + 1]);
                    if ((char.IsUpper(current) && (char.IsLower(previous) || nextIsLower)) ||
                        (char.IsDigit(current) && !char.IsDigit(previous)))
                    {
                        builder.Append(' ');
                    }
                }

                builder.Append(current);
            }

            var text = builder.ToString().Trim();
            return text.Length == 0
                ? id
                : text;
        }

        public bool IsDirty
        {
            get => _isDirty;
            set
            {
                if (_isDirty == value)
                    return;

                _isDirty = value;
                UpdateSaveButton();
            }
        }

        private void UpdateNameEdit()
        {
            NameEdit.Text = Profile?.Name ?? "";
        }

        private void UpdateFlavorTextEdit()
        {
            if (_flavorTextEdit != null)
            {
                _flavorTextEdit.TextRope = new Rope.Leaf(Profile?.FlavorText ?? "");
            }
        }

        private void UpdateAgeEdit()
        {
            AgeEdit.Text = Profile?.Age.ToString() ?? "";
        }

        /// <summary>
        /// Updates selected job priorities to the profile's.
        /// </summary>
        private void UpdateJobPriorities()
        {
            foreach (var (gamemode, jobId, prioritySelector) in _jobPriorities)
            {
                var priority = Profile?.GetJobPriorityForGamemode(gamemode, jobId) ?? JobPriority.Never;
                prioritySelector.Select((int)priority);
            }
        }

        private void UpdateSexControls()
        {
            if (Profile == null)
                return;

            SexButton.Clear();

            var sexes = new List<Sex>();

            // add species sex options, default to just none if we are in bizzaro world and have no species
            if (_prototypeManager.TryIndex<SpeciesPrototype>(Profile.Species, out var speciesProto))
            {
                foreach (var sex in speciesProto.Sexes)
                {
                    sexes.Add(sex);
                }
            }
            else
            {
                sexes.Add(Sex.Unsexed);
            }

            // add button for each sex
            foreach (var sex in sexes)
            {
                SexButton.AddItem(Loc.GetString($"humanoid-profile-editor-sex-{sex.ToString().ToLower()}-text"), (int)sex);
            }

            if (sexes.Contains(Profile.Sex))
                SexButton.SelectId((int)Profile.Sex);
            else
                SexButton.SelectId((int)sexes[0]);
        }

        private void UpdateSkinColor()
        {
            if (Profile == null)
                return;

            var skin = _prototypeManager.Index<SpeciesPrototype>(Profile.Species).SkinColoration;

            switch (skin)
            {
                case HumanoidSkinColor.HumanToned:
                    {
                        if (!Skin.Visible)
                        {
                            Skin.Visible = true;
                            RgbSkinColorContainer.Visible = false;
                        }

                        Skin.Value = SkinColor.HumanSkinToneFromColor(Profile.Appearance.SkinColor);

                        break;
                    }
                case HumanoidSkinColor.Hues:
                    {
                        if (!RgbSkinColorContainer.Visible)
                        {
                            Skin.Visible = false;
                            RgbSkinColorContainer.Visible = true;
                        }

                        // set the RGB values to the direct values otherwise
                        _rgbSkinColorSelector.Color = Profile.Appearance.SkinColor;
                        break;
                    }
                case HumanoidSkinColor.TintedHues:
                    {
                        if (!RgbSkinColorContainer.Visible)
                        {
                            Skin.Visible = false;
                            RgbSkinColorContainer.Visible = true;
                        }

                        // set the RGB values to the direct values otherwise
                        _rgbSkinColorSelector.Color = Profile.Appearance.SkinColor;
                        break;
                    }
                case HumanoidSkinColor.VoxFeathers:
                    {
                        if (!RgbSkinColorContainer.Visible)
                        {
                            Skin.Visible = false;
                            RgbSkinColorContainer.Visible = true;
                        }

                        _rgbSkinColorSelector.Color = SkinColor.ClosestVoxColor(Profile.Appearance.SkinColor);

                        break;
                    }
            }

        }

        public void UpdateSpeciesGuidebookIcon()
        {
            if (!_cfgManager.GetCVar(RMCCVars.GuidebookShowEditorSpeciesButton))
                return;

            SpeciesInfoButton.StyleClasses.Clear();

            var species = Profile?.Species;
            if (species is null)
                return;

            if (!_prototypeManager.TryIndex<SpeciesPrototype>(species, out var speciesProto))
                return;

            // Don't display the info button if no guide entry is found
            if (!_prototypeManager.HasIndex<GuideEntryPrototype>(species))
                return;

            const string style = "SpeciesInfoDefault";
            SpeciesInfoButton.StyleClasses.Add(style);
        }

        private void UpdateMarkings()
        {
            if (Profile == null)
            {
                return;
            }

            Markings.SetData(Profile.Appearance.Markings, Profile.Species,
                Profile.Sex, Profile.Appearance.SkinColor, Profile.Appearance.EyeColor
            );
        }

        private void UpdateGenderControls()
        {
            if (Profile == null)
            {
                return;
            }

            PronounsButton.SelectId((int)Profile.Gender);
        }

        private void UpdateSpawnPriorityControls()
        {
            if (Profile == null)
            {
                return;
            }

            SpawnPriorityButton.SelectId((int)Profile.SpawnPriority);
        }

        private void UpdateArmorPreferenceControls()
        {
            if (Profile == null)
            {
                return;
            }

            ArmorPreferenceButton.SelectId((int)Profile.ArmorPreference);
        }

        private void UpdateSquadPreferenceControls()
        {
            if (Profile == null)
            {
                return;
            }

            var index = 0;
            if (Profile.SquadPreference is { } preference)
            {
                var squads = new List<EntityPrototype>(_entManager.System<SquadSystem>().SquadPrototypes)
                    .Select(s => s.ID)
                    .ToList();
                index = squads.IndexOf(preference.Id) + 1;
            }

            SquadPreferenceButton.SelectId(index);
        }

        private void UpdateHairPickers()
        {
            if (Profile == null)
            {
                return;
            }
            var hairMarking = Profile.Appearance.HairStyleId == HairStyles.DefaultHairStyle
                ? new List<Marking>()
                : new() { new(Profile.Appearance.HairStyleId, new List<Color>() { Profile.Appearance.HairColor }) };

            var facialHairMarking = Profile.Appearance.FacialHairStyleId == HairStyles.DefaultFacialHairStyle
                ? new List<Marking>()
                : new() { new(Profile.Appearance.FacialHairStyleId, new List<Color>() { Profile.Appearance.FacialHairColor }) };

            HairStylePicker.UpdateData(
                hairMarking,
                Profile.Species,
                1);
            FacialHairPicker.UpdateData(
                facialHairMarking,
                Profile.Species,
                1);
        }

        private void UpdateCMarkingsHair()
        {
            if (Profile == null)
            {
                return;
            }

            // hair color
            Color? hairColor = null;
            if (Profile.Appearance.HairStyleId != HairStyles.DefaultHairStyle &&
                _markingManager.Markings.TryGetValue(Profile.Appearance.HairStyleId, out var hairProto)
            )
            {
                if (_markingManager.CanBeApplied(Profile.Species, Profile.Sex, hairProto, _prototypeManager))
                {
                    if (_markingManager.MustMatchSkin(Profile.Species, HumanoidVisualLayers.Hair, out var _, _prototypeManager))
                    {
                        hairColor = Profile.Appearance.SkinColor;
                    }
                    else
                    {
                        hairColor = Profile.Appearance.HairColor;
                    }
                }
            }
            if (hairColor != null)
            {
                Markings.HairMarking = new(Profile.Appearance.HairStyleId, new List<Color>() { hairColor.Value });
            }
            else
            {
                Markings.HairMarking = null;
            }
        }

        private void UpdateCMarkingsFacialHair()
        {
            if (Profile == null)
            {
                return;
            }

            // facial hair color
            Color? facialHairColor = null;
            if (Profile.Appearance.FacialHairStyleId != HairStyles.DefaultFacialHairStyle &&
                _markingManager.Markings.TryGetValue(Profile.Appearance.FacialHairStyleId, out var facialHairProto))
            {
                if (_markingManager.CanBeApplied(Profile.Species, Profile.Sex, facialHairProto, _prototypeManager))
                {
                    if (_markingManager.MustMatchSkin(Profile.Species, HumanoidVisualLayers.Hair, out var _, _prototypeManager))
                    {
                        facialHairColor = Profile.Appearance.SkinColor;
                    }
                    else
                    {
                        facialHairColor = Profile.Appearance.FacialHairColor;
                    }
                }
            }
            if (facialHairColor != null)
            {
                Markings.FacialHairMarking = new(Profile.Appearance.FacialHairStyleId, new List<Color>() { facialHairColor.Value });
            }
            else
            {
                Markings.FacialHairMarking = null;
            }
        }

        private void UpdateEyePickers()
        {
            if (Profile == null)
            {
                return;
            }

            Markings.CurrentEyeColor = Profile.Appearance.EyeColor;
            EyeColorPicker.SetData(Profile.Appearance.EyeColor);
        }

        private void UpdateNamedItems()
        {
            NamedItems.PrimaryGun.Text = Profile?.NamedItems.PrimaryGunName ?? string.Empty;
            NamedItems.Sidearm.Text = Profile?.NamedItems.SidearmName ?? string.Empty;
            NamedItems.Helmet.Text = Profile?.NamedItems.HelmetName ?? string.Empty;
            NamedItems.Armor.Text = Profile?.NamedItems.ArmorName ?? string.Empty;
            NamedItems.Sentry.Text = Profile?.NamedItems.SentryName ?? string.Empty;
        }

        private void UpdatePlaytimePerks()
        {
            PlaytimePerksButton.Pressed = Profile?.PlaytimePerks ?? true;
        }

        private void UpdateXenoPrefix()
        {
            XenoPrefix.Text = Profile?.XenoPrefix ?? string.Empty;
        }

        private void UpdateXenoPostfix()
        {
            XenoPostfix.Text = Profile?.XenoPostfix ?? string.Empty;
        }

        private void UpdateSaveButton()
        {
            SaveButton.Disabled = Profile is null || !IsDirty;
            ResetButton.Disabled = Profile is null || !IsDirty;
        }

        private void SetPreviewRotation(Direction direction)
        {
            SpriteView.OverrideDirection = (Direction)((int)direction % 4 * 2);
        }

        private void RandomizeEverything()
        {
            Profile = HumanoidCharacterProfile.Random();
            SetProfile(Profile, CharacterSlot);
            SetDirty();
        }

        private void RandomizeName()
        {
            if (Profile == null) return;
            var name = HumanoidCharacterProfile.GetName(Profile.Species, Profile.Gender);
            SetName(name);
            UpdateNameEdit();
        }

        private async void ExportImage()
        {
            if (_imaging)
                return;

            var dir = SpriteView.OverrideDirection ?? Direction.South;

            // I tried disabling the button but it looks sorta goofy as it only takes a frame or two to save
            _imaging = true;
            await _entManager.System<ContentSpriteSystem>().Export(PreviewDummy, dir, includeId: false);
            _imaging = false;
        }

        private async void ImportProfile()
        {
            if (_exporting || CharacterSlot == null || Profile == null)
                return;

            StartExport();
            await using var file = await _dialogManager.OpenFile(new FileDialogFilters(new FileDialogFilters.Group("yml")));

            if (file == null)
            {
                EndExport();
                return;
            }

            try
            {
                var profile = _entManager.System<HumanoidAppearanceSystem>().FromStream(file, _playerManager.LocalSession!);
                var oldProfile = Profile;
                SetProfile(profile, CharacterSlot);

                IsDirty = !profile.MemberwiseEquals(oldProfile);
            }
            catch (Exception exc)
            {
                _sawmill.Error($"Error when importing profile\n{exc.StackTrace}");
            }
            finally
            {
                EndExport();
            }
        }

        private async void ExportProfile()
        {
            if (Profile == null || _exporting)
                return;

            StartExport();
            var file = await _dialogManager.SaveFile(new FileDialogFilters(new FileDialogFilters.Group("yml")));

            if (file == null)
            {
                EndExport();
                return;
            }

            try
            {
                var dataNode = _entManager.System<HumanoidAppearanceSystem>().ToDataNode(Profile);
                await using var writer = new StreamWriter(file.Value.fileStream);
                dataNode.Write(writer);
            }
            catch (Exception exc)
            {
                _sawmill.Error($"Error when exporting profile\n{exc.StackTrace}");
            }
            finally
            {
                EndExport();
                await file.Value.fileStream.DisposeAsync();
            }
        }

        private void StartExport()
        {
            _exporting = true;
            ImportButton.Disabled = true;
            ExportButton.Disabled = true;
        }

        private void EndExport()
        {
            _exporting = false;
            ImportButton.Disabled = false;
            ExportButton.Disabled = false;
        }
    }
}
