- type: job
  parent: CMJobBase
  id: AU14UPPGROMSquadleader
  roundSide: ThirdParty
  roundForce: GROM
  roundRole: AU14UPPGROMSquadleader
  roundComponents:
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: spp_comsl
  - type: AssignSquad
    whitelist:
      tags:
      - AU14SquadGROM # for future when there's a dedicated map for them, right now does nothing
  - type: Skills
    preset: AU14SkillPresetPlatoonSeniorSergeant
  - type: JobPrefix
    prefix: au-14-job-prefix-uppgrom-squadleader
  - type: MarineOrders
    moveOrderSoundMale:
      collection: AU14MaleMoveOrder
    moveOrderSoundFemale:
      collection: AU14FemaleMoveOrder
    focusOrderSoundMale:
      collection: AU14MaleFocusOrder
    focusOrderSoundFemale:
      collection: AU14FemaleFocusOrder
    holdOrderSoundMale:
      collection: AU14MaleHoldOrder
    holdOrderSoundFemale:
      collection: AU14FemaleHoldOrder # No Russian/UPP voicelines yet, its gonna have to use normal english accent
  - type: RMCTrackable
  - type: SquadLeader
  - type: RMCPointing
  - type: Language
    spokenLanguages:
    - Polish
    - English
    - Russian
    - Spanish
    - Mandarin
    - German
    - TacticalSignLanguage
    understoodLanguages:
    - Polish
    - English
    - Russian
    - Spanish
    - Mandarin
    - German
    - TacticalSignLanguage
    currentLanguage: Polish
    defaultLanguage: Polish

  name: au-14-job-name-uppgrom-squadleader
  description: au14-uppgrom-description
  playTimeTracker: AU14JobUPPGROMSquadLeader
  ranks:
    RMCRankCivilian: []
  chevrons:
    UPP_SeniorLieutenant:
      entity: AU14ChevronUPPNISeniorLieutenant
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobUPPGROMSquadLeader
        time: 36000 # 10 hours
    UPP_Lieutenant:
      entity: AU14ChevronUPPNILieutenant
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobUPPGROMSquadLeader
        time: 18000 # 5 hours
    UPP_JuniorLieutenant:
      entity: AU14ChevronUPPNIJuniorLieutenant
      requirements: []
  spawnMenuRoleName: UPP GROM Squad Leader (Survivor)
  startingGear: AU14GearUPPGROMSquadleader
  greeting: au14-uppgrom-greeting
  icon: "AU14JobIconUPPGROMSquadLeader"
  joinNotifyCrew: false
  supervisors: au-14-job-name-uppgrom-commander
  accessGroups:
  - AU14GovforCommand
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicUPPGROM
  id: AU14JobUPPGROMSquadleader
  name: UPP GROM Squad Leader
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: AU14SquadGROM
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: au-14-job-name-uppgrom-squadleader
    description: au14-uppgrom-description
    reregister: false
    job: AU14UPPGROMSquadleader
    raffle:
      settings: short
    rules: au14-uppgrom-rules

- type: startingGear
  id: AU14GearUPPGROMSquadleader
  equipment:
    id: AU14IDCardUPPGROMSquadleader
    outerClothing: RMCOuterClothingExternalWebbingBrownFull
    jumpsuit: AU14FatiguesUPPGROM
    shoes: RMCBootsSPPFilled
    head: AU14UPPBoonie
    belt: AU14BeltHolsterPistolUPPFull
    pocket1: AU14PouchSlingBinocs
    pocket2: AU14PouchIFAKFill
    back: RMCSatchelSPPFull
    ears: RMCHeadsetGROM
    suitstorage: AU14WeaponRifleAG80Filled

- type: jobIcon
  parent: CMJobIconBase
  id: AU14JobIconUPPGROMSquadLeader
  icon:
    sprite: _RMC14/Interface/cm_job_icons.rsi
    state: upp_lt

- type: playTimeTracker
  id: AU14JobUPPGROMSquadLeader
