- type: job
  parent: CMJobBase
  id: AU14UPPGROMRifleman
  roundSide: ThirdParty
  roundForce: GROM
  roundRole: AU14UPPGROMRifleman
  roundComponents:
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: spp_pvt
  - type: AssignSquad
    whitelist:
      tags:
      - AU14SquadGROM # for future when there's a dedicated map for them, right now does nothing
  - type: Skills
    preset: AU14SkillPresetPlatoonRifleman
  - type: JobPrefix
    prefix: au14-job-prefix-govforsquadrifleman
  - type: Language
    spokenLanguages:
    - Polish
    - Russian
    - Spanish
    - Mandarin
    - German
    - TacticalSignLanguage
    understoodLanguages:
    - Polish
    - Russian
    - Spanish
    - Mandarin
    - German
    - TacticalSignLanguage
    currentLanguage: Polish
    defaultLanguage: Polish

  name: au14-job-name-govforsquadrifleman
  description: au14-uppgrom-description
  playTimeTracker: AU14JobUPPGROMRifleman
  ranks:
    RMCRankCivilian: []
  chevrons:
    UPP_SeniorSergeant:
      entity: AU14ChevronUPPNISeniorSergeant
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobUPPGROMRifleman
        time: 36000 # 10 hours
    UPP_Sergeant:
      entity: AU14ChevronUPPNISergeant
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobUPPGROMRifleman
        time: 18000 # 5 hours
    UPP_Plutonowy:
      entity: AU14ChevronUPPNIPlutonowy
      requirements: []
  spawnMenuRoleName: UPP GROM Rifleman (Survivor)
  startingGear: AU14GearUPPGROMRifleman
  greeting: au14-uppgrom-greeting
  icon: "CMJobIconEmpty"
  joinNotifyCrew: false
  supervisors: au-14-job-name-uppgrom-squadleader
  accessGroups:
  - AU14GovforCommand
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicUPPGROM
  id: AU14JobUPPGROMRifleman
  name: UPP GROM Rifleman
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: AU14SquadGROM
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: au14-job-name-govforsquadrifleman
    description: au14-uppgrom-description
    reregister: false
    job: AU14UPPGROMRifleman
    raffle:
      settings: short
    rules: au14-uppgrom-rules

- type: startingGear
  id: AU14GearUPPGROMRifleman
  equipment:
    id: AU14IDCardUPPGROMRifleman
    outerClothing: RMCOuterClothingExternalWebbingBrownFull
    jumpsuit: AU14FatiguesUPPGROM
    shoes: RMCBootsSPPFilled
    head: AU14UPPNavalInfantryHelmet
    belt: AU14BeltHolsterPistolUPPFull
    pocket1: AU14PouchIFAKFill
    pocket2: AU14PouchIFAKFill
    back: RMCSatchelSPPFull
    ears: RMCHeadsetGROM
    suitstorage: AU14WeaponRifleAG80Filled

- type: playTimeTracker
  id: AU14JobUPPGROMRifleman
