
- type: entity
  parent: CMMobHuman
  id: AU14BaseMobSpeciesOrganicRMCRRT
  abstract: true
  components:
  - type: GhostTakeoverAvailable
  - type: NpcFactionMember
    factions:
    - CMUTWE
  - type: RandomHumanoidAppearance
  - type: RandomHumanoidAppearanceWhitelisted
    allowedMaleHairStyles:
    - RMCHumanHairCrew
    - RMCHumanHairAviator
    - RMCHumanHairJensen
    - RMCHumanHairAverageJoe
    - AU14HumanHairCIA5
    - RMCHumanHairCombover
    - RMCHumanHairCombover2
    - RMCHumanHairCplDietrich
    - RMCHumanHairCut
    - RMCHumanHairHeadStubble
    - RMCHumanHairHighAndTight
    - RMCHumanHairHighfade
    - RMCHumanHairHighlight
    - AU14HumanHairIRS
    - RMCHumanHairLtRasczak
    - RMCHumanHairMarineFade
    - RMCHumanHairMarineFlatTop
    - RMCHumanHairMedfade
    - RMCHumanHairNofade
    - RMCHumanHairShavedpart
    - RMCHumanHairShavedHead
    - RMCHumanHairShort
    - RMCHumanHairSideUndercutHang
    - RMCHumanHairSkinhead
    - RMCHumanHairTaper
    - RMCHumanHairWardaddy
    - RMCHumanHairUndercut
    - RMCHumanHairUndercutTop
    allowedFemaleHairStyles:
    - RMCHumanHairShortbangs
    - RMCHumanHairBobcurl
    - RMCHumanHairMarineBun
    - RMCHumanHairBun
    - RMCHumanHairFringetail
    - AU14HumanHairLowBun
    - AU14HumanHairLowPonyTail
    - AU14HumanHairLowPonyTailAlt
    - RMCHumanHairPonytail1
    - RMCHumanHairPonytail7
    - RMCHumanHairPvtRedding
    - RMCHumanHairPvtVasquez
    - RMCHumanHairLong
    - RMCHumanHairPixieCutLeft
    - RMCHumanHairPixieCutRight
    allowedHairColorsHex:
    - "#0B0B0B"
    - "#1A1A1A"
    - "#222222"
    - "#2B1B0F"
    - "#3B2314"
    - "#4A2E1A"
    - "#5A3A22"
    - "#6B4A2F"
    - "#9C8651"
    - "#B79A5A"
    - "#4A1F12"
    - "#7A5E42"
    allowedEyeColorsHex: [ "#000000" ]
    beardChance: 0.1

# equipment

- type: entity
  parent: RMCBeltSmartGunOperatorPistolFilled
  id: RMCBeltSmartGunOperatorPistolFilledL165A1
  suffix: Filled, RMC, RRT, L165A1
  components:
  - type: StorageFill
    contents:
    - id: RMCMagazineSmartGun
      amount: 4
    - id: AU14L165A1Filled

- type: entity
  parent: RMCPouchDrumPMC
  id: RMCPouchDrumPMCFilled
  suffix: Filled, RMC, RRT
  components:
  - type: StorageFill
    contents:
    - id: RMCMagazineSmartGun
      amount: 3

- type: entity
  parent: AU14SmallBackpackRMC
  id: AU14RMCRRTBackpackCommander
  suffix: Filled, RMC, RRT, Commander
  components:
  - type: StorageFill
    contents:
    - id: CMSandbagEmpty50
    - id: CMEntrenchingTool
    - id: CMCanteen
    - id: AU14MRETWERMC
    - id: AU14MagazineSMGL90A2extended
      amount: 3

- type: entity
  parent: AU14SmallBackpackRMC
  id: AU14RMCRRTBackpackRifleman
  suffix: Filled, RMC, RRT, Rifleman
  components:
  - type: StorageFill
    contents:
    - id: CMSandbagEmpty50
    - id: CMEntrenchingTool
    - id: CMCanteen
    - id: AU14MRETWERMC
    - id: AU14MagazineRifleL90extended
    - id: AU14MagazineRifleL90extended
    - id: AU14MagazineRifleL90
    - id: AU14MagazineRifleL90

- type: entity
  parent: AU14SmallBackpackRMC
  id: AU14RMCRRTBackpackBreacher
  suffix: Filled, RMC, RRT, Breacher
  components:
  - type: StorageFill
    contents:
    - id: CMCanteen
    - id: CMEntrenchingTool
    - id: AU14MRETWERMC
    - id: AU14MagazineRifleL90extended
      amount: 5

- type: entity
  parent: AU14SmallBackpackRMC
  id: AU14RMCRRTBackpackMarksman
  suffix: Filled, RMC, RRT, Marksman
  components:
  - type: StorageFill
    contents:
    - id: CMSandbagEmpty50
    - id: CMEntrenchingTool
    - id: CMCanteen
    - id: AU14MRETWERMC
    - id: AU14MagazineRifleL90Mextended
    - id: AU14MagazineRifleL90Mextended
    - id: AU14MagazineRifleL90M
    - id: AU14MagazineRifleL90M

- type: entity
  parent: RMCPouchMagazine
  id: AU14RMCRTTPouchMagazineL90A2
  suffix: Filled, RMC, RRT, L90A2
  components:
  - type: StorageFill
    contents:
    - id: AU14MagazineSMGL90A2extended
      amount: 3