- type: job
  parent: AU14USArmyTrooperBase
  id: AU14USArmyTrooper
  roundSide: ThirdParty
  roundForce: USARMY
  roundRole: AU14USArmyTrooper
  roundComponents:
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: private
    background:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_ua
  - type: AssignSquad
    whitelist:
      tags:
      - AU14SquadUSArmy
  - type: Skills
    preset: AU14SkillPresetPlatoonRifleman
  - type: SpotterWhitelist
  - type: JobPrefix
    prefix: au14-job-prefix-usarmy-trooper

  name: au14-job-name-usarmy-trooper
  description: au14-job-description-usarmy
  ranks:
    RMCRankCivilian: []
  chevrons:
    USArmy_Specialist:
      entity: AU14ChevronUSArmySpecialist
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobUSArmyTrooper
        time: 36000
    USArmy_PFC:
      entity: AU14ChevronUSArmyPFC
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobUSArmyTrooper
        time: 18000
    USArmy_Private2:
      entity: AU14ChevronUSArmyPrivate2
      requirements: []
  spawnMenuRoleName: US Army Trooper (AU14, surv)
  startingGear: AU14GearUSArmyTrooper
  greeting: au14-usarmy-greeting
  icon: "AU14JobIconUSArmyTrooper"
  joinNotifyCrew: false
  supervisors: cm-job-name-squad-leader
  accessGroups:
  - AU14GovforSquad
  hidden: true

- type: entity
  parent: AU14BaseMobSpeciesOrganicUSArmy
  id: AU14JobUSArmyTrooper
  name: US Army Trooper (Surv)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: AU14SquadUSArmy
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: au14-job-name-usarmy-trooper
    description: au14-job-description-usarmy
    reregister: false
    job: AU14USArmyTrooper
    raffle:
      settings: short
    rules: au14-usarmy-rules

- type: startingGear
  id: AU14GearUSArmyTrooper
  equipment:
    id: AU14IDCardUSArmyTrooper
    outerClothing: AU14ArmorUSArmy
    jumpsuit: AU14ArmyJumpsuitCavalry
    gloves: AU14PVEHandsInsulatedBlackMarine
    shoes: AU14BootsUSArmyFilled
    head: AU14HelmetUSArmy
    mask: RMCMaskKeffiyehBlack
    belt: RMCM1984BeltFilled
    pocket1: AU14PouchIFAKFill
    pocket2: AU14PouchIFAKFill
    back: AU14MolleSatchel
    ears: AU14HeadsetUSArmy
    suitstorage: RMCWeaponRifleM54C
  storage:
    head:
    - AU14GogglesM1A1Ballistic
    back:
    - RMCRadioHandheldColony
    - CMMagazineRifleM54C
    - CMMagazineRifleM54C
    - CMMagazineRifleM54C
    - RMCMagazineRifleM54CHEAPEmpty
    - RMCFlashlight
