- type: job
  parent: CMJobBase
  id: AU14FORECONRiflemanBase
  name: cm-job-name-rifleman
  description: au14-job-description-govforadvisor
  playTimeTracker: AU14JobFORECONRifleman
  basePlaytimeTracker: true
  hidden: true

- type: job
  parent: AU14FORECONRiflemanBase
  id: AU14FORECONRifleman
  roundSide: ThirdParty
  roundForce: FORECON
  roundRole: AU14FORECONRifleman
  roundComponents:
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: private
    background:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_forecon
  - type: NpcFactionMember
    factions:
    - GOVFOR
  - type: AssignSquad
    whitelist:
      tags:
      - RMCSquadFORECON
  - type: Skills
    preset: AU14SkillPresetPlatoonRifleman
  - type: SpotterWhitelist
  - type: JobPrefix
    prefix: cm-job-prefix-rifleman
  - type: LanguagePreset
    spokenLanguages:
    - English
    - TacticalSignLanguage
    understoodLanguages:
    - English
    - TacticalSignLanguage
    currentLanguage: English
    defaultLanguage: English

  name: cm-job-name-rifleman
  description: rmc-job-description-forecon
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMCRankStaffSergeant:
      entity: AU14ChevronUSCMStaffSergeant
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobFORECONRifleman
        time: 36000 #10 hours
    RMCRankSergeant:
      entity: AU14ChevronUSCMSergeant
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobFORECONRifleman
        time: 18000 #5 hours
    RMCRankCorporal:
      entity: AU14ChevronUSCMCorporal
      requirements: []
  spawnMenuRoleName: FORECON Rifleman (AU14, surv)
  startingGear: AU14GearFORECONRifleman
  greeting: au14-forecon-greeting
  icon: "CMJobIconEmpty"
  joinNotifyCrew: false
  supervisors: cm-job-name-squad-leader
  accessGroups:
  - AU14GovforSquad
  hidden: true

- type: entity
  parent: AU14BaseMobSpeciesOrganicFORECON
  id: AU14JobFORECONRifleman
  name: FORECON Rifleman (Surv)
  components:
  - type: Threat
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: SquadFORECON
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: cm-job-name-rifleman
    description: rmc-job-description-forecon
    reregister: false
    job: AU14FORECONRifleman
    raffle:
      settings: short
    rules: au14-forecon-rules

- type: startingGear
  id: AU14GearFORECONRifleman
  equipment:
    id: AU14IDCardFORECONRifleman
    outerClothing: RMCOuterClothingExternalWebbingBrownFull
    jumpsuit: RMCJumpsuitSurvivorMarineDropPouch
    shoes: CMBootsBlackFilled
    head: ArmorHelmetM10
    belt: AU14BeltPostelPistolM48A4
    pocket1: AU14PouchIFAKFill
    pocket2: AU14PouchIFAKFill
    back: RMCSatchelMarineForeconSurvivorFill
    ears: RMCHeadsetForecon
    suitstorage: WeaponRifleM4SPRFilled
  storage:
    back:
    - RMCAttachmentRailFlashlight
    - CMMagazineRifleM4SPR
    - CMMagazineRifleM4SPR
    - CMMagazineRifleM4SPR

- type: playTimeTracker
  id: AU14JobFORECONRifleman
