# Command
- type: rank
  id: AU14RankPrDRegionDirector
  name: PSC Regional Director
  prefix: PSC-RD
  paygrade: PSC-C12

- type: rank
  id: AU14RankPrDOperationsDirector
  name: PSC Director of Operations
  prefix: PSC-DO
  paygrade: PSC-C11

- type: rank
  id: AU14RankPrDDeputyDirector
  name: Deputy Director of Operations
  prefix: PSC-DDO
  paygrade: PSC-C10

# Supervisory
- type: rank
  id: AU14RankPrDCommanderSenior
  name: Senior Response Unit Commander
  prefix: RU. SrCDR.
  paygrade: PSC-S3

- type: rank
  id: AU14RankPrDCommander
  name: Response Unit Commander
  prefix: RU. CDR.
  paygrade: PSC-S2

- type: rank
  id: AU14RankPrDAdjutant
  name: Response Unit Adjutant
  prefix: RU. ADJ.
  paygrade: PSC-S1

# Response Unit
- type: rank
  id: AU14RankPrDEnforcerLead
  name: Lead Response Unit Enforcer
  prefix: RU. LdENF.
  paygrade: PSC-R6

- type: rank
  id: AU14RankPrDEnforcerSenior
  name: Senior Response Unit Enforcer
  prefix: RU. SrENF.
  paygrade: PSC-R5

- type: rank
  id: AU14RankPrDEnforcer
  name: Response Unit Enforcer
  prefix: RU. ENF.
  paygrade: PSC-R4

- type: rank
  id: AU14RankPrDSeniorOperator
  name: Senior Operator
  prefix: RU. SrOPR.
  paygrade: PSC-R3

- type: rank
  id: AU14RankPrDOperator
  name: Response Unit Operator
  prefix: RU. OPR.
  paygrade: PSC-R2

- type: rank
  id: AU14RankPrDAssociate
  name: Associate Response Unit
  prefix: ARU.
  paygrade: PSC-R1

- type: rank
  id: AU14RankPrDRecruit
  name: Response Unit in Training
  prefix: RU. IT.
  paygrade: PSC-R0

# Aviation
- type: rank
  id: AU14RankPrDSeniorCrewChief
  name: Senior Response Unit Crew Chief
  prefix: SR. CC.
  paygrade: PSC-AVC2

- type: rank
  id: AU14RankPrDCrewChief
  name: Response Unit Crew Chief
  prefix: RU. CC.
  paygrade: PSC-AVC1

- type: rank
  id: AU14RankPrDSeniorPilot
  name: Senior Response Unit Pilot
  prefix: SR. PLT.
  paygrade: PSC-AVO2

- type: rank
  id: AU14RankPrDPilot
  name: Response Unit Pilot
  prefix: PLT.
  paygrade: PSC-AVO1

# Synthetic
- type: rank
  id: AU14RankPrDSynth1
  name: Response Unit Synthetic Grade 1
  prefix: RU. SYN.
  paygrade: PSC-RUSYN1

- type: rank
  id: AU14RankPrDSynth2
  name: Response Unit Synthetic Grade 2
  prefix: RU. SYN. Grade 2
  paygrade: PSC-RUSYN2

- type: rank
  id: AU14RankPrDSynth3
  name: Response Unit Synthetic Grade 3
  prefix: RU. SYN. Grade 3
  paygrade: PSC-RUSYN3

- type: rank
  id: AU14RankPrDSynth4
  name: Response Unit Synthetic Grade 4
  prefix: RU. SYN. Grade 4
  paygrade: PSC-RUSYN4

- type: rank
  id: AU14RankPrDSynth5
  name: Response Unit Synthetic Grade 5
  prefix: RU. SYN. Grade 5
  paygrade: PSC-RUSYN5
