- type: entity
  parent: AU14BaseMobSpeciesOrganicMisc
  id: AU14BaseMobSpeciesOrganicBaseMilitary
  abstract: true
  components:
  - type: GhostTakeoverAvailable

- type: entity
  parent: AU14BaseMobSpeciesOrganicBaseMilitary
  id: AU14IntelThirdPartyK9Handler
  name: S&R K9 Handler
  components:
  - type: GhostRoleApplySpecial
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: S&R K9 Handler
    description: You and your loyal canine companion were flying around and noticed a sudden long-range signal burst nearby. You decide to land and check it out.
    job: AU14JobThirdPartyK9Handler
    raffle:
      settings: short
  - type: Skills
    preset: AU14SkillPresetPlatoonHospitalCorpsman

- type: partySpawn
  id: AU14IntelThirdPartyK9HandlerSpawn
  leadersToSpawn:
    AU14IntelThirdPartyK9Handler: 1
  gruntsToSpawn:
    AU14MobK9BagMedicGhostRole: 1
  scalewithpop: false
  spawnTogether: true

- type: thirdParty
  id: AU14IntelThirdPartyK9
  partyspawn: AU14IntelThirdPartyK9HandlerSpawn
  entrymethod: shuttle
  dropshippath: /Maps/_AU14/ShuttlesDropships/rmc_ert_response_shuttle.yml
  weight: 1
  minplayers: 500
  maxplayers: 600
  GhostsNeeded: 600
  roundstart: false

- type: entity
  parent: CMIDCardBase
  id: AU14IDCardSquadK9Handler
  name: k9 handler ID card
  components:
  - type: PresetIdCard
    job: AU14JobThirdPartyK9Handler
  - type: ItemIFF
    factions:
    - FactionSurvivor
