- type: job
  parent: CMJobBase
  id: AU14JobCLFMachineGunner
  roundSide: ThirdParty
  roundForce: CLF
  roundRole: CLFMachineGunner
  roundComponents:
  - type: NpcFactionMember
    factions:
    - CLF
  - type: CLFMember
  - type: Skills
    skills:
      RMCSkillEndurance: 2
      RMCSkillFirearms: 2
      RMCSkillConstruction: 2
      RMCSkillEngineer: 3
      RMCSkillFireman: 2
      RMCSkillVehicles: 1
      RMCSkillPolice: 1
  - type: JobPrefix
    prefix: au14-job-prefix-clfmachinegunner
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14colonyjobicons.rsi
      state: colonist
  - type: ShowMarineIcons
    factions:
    - CLF
  - type: FactionLanguageMember
    factionTag: CLF

  name: au14-job-name-clfmachinegunner
  description: au14-job-description-clfmachinegunner
  setPreference: true
  ignoreAllegiance: true
  playTimeTracker: AU14JobCLFMachineGunner
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - NonResuscitable
    - Epilepsy
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCLFMachineGunner
  icon: "RMCJobIconCLFSpecialist"
  hasIcon: false
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-clflrs
  accessGroups:
  - Colonist
  roleWeight: 0.25

- type: startingGear
  id: AU14GearCLFMachineGunner
  equipment:
    outerClothing: AU14ArmorBallisticVest
    gloves: CMHandsInsulated
    shoes: RMCBootsPMCFilled
    jumpsuit: AU14CMJumpsuitColonistCLF
    id: AU14IDCardColonyColonist
  inhand:
  - RMCWeaponLMGM60
  - RMCCLFArmband

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCLFMachineGunner
  name: Spawn Point CLF Machine Gunner
  components:
  - type: SpawnPoint
    job_id: AU14JobCLFMachineGunner
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCLFMachineGunner
  isHumanoid: true
