- type: entity
  id: AU14SkillPresetPlatoonSeniorSergeant
  name: Senior Sergeant
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 2
      RMCSkillCqc: 2
      RMCSkillEndurance: 3
      RMCSkillEngineer: 2
      RMCSkillFirearms: 2
      RMCSkillFireman: 2
      RMCSkillVehicles: 1
      RMCSkillOverwatch: 1
      RMCSkillPilot: 1
      RMCSkillLeadership: 3
      RMCSkillIntel: 1
      RMCSkillPowerLoader: 1
      RMCSkillMedical: 1
      RMCSkillSurgery: 1
      RMCSkillNavigations: 1
      RMCSkillPolice: 1
      RMCSkillJtac: 4

- type: entity
  id: AU14SkillPresetPlatoonSergeant
  name: Sergeant
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillLeadership: 2
      RMCSkillJtac: 3
      RMCSkillCqc: 1
      RMCSkillFirearms: 2
      RMCSkillEndurance: 2
      RMCSkillConstruction: 2
      RMCSkillEngineer: 3
      RMCSkillFireman: 2
      RMCSkillPolice: 1
      RMCSkillVehicles: 1

- type: entity
  id: AU14SkillPresetPlatoonRTO
  name: Radio Traffic Operator
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillLeadership: 1
      RMCSkillJtac: 4
      RMCSkillFirearms: 1
      RMCSkillCqc: 1
      RMCSkillEndurance: 1
      RMCSkillConstruction: 2
      RMCSkillEngineer: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 1

- type: entity
  id: AU14SkillPresetPlatoonRifleman
  name: Rifleman
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 1
      RMCSkillCqc: 1
      RMCSkillEndurance: 1
      RMCSkillEngineer: 1
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 1
      RMCSkillJtac: 1

- type: entity
  id: AU14SkillPresetPlatoonAutomaticRifleman
  name: Automatic Rifleman
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 1
      RMCSkillCqc: 1
      RMCSkillEndurance: 2
      RMCSkillEngineer: 1
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 1
      RMCSkillSmartGun: 1
      RMCSkillJtac: 1

- type: entity
  id: AU14SkillPresetPlatoonCombatTechnician
  name: Combat Technician
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 4
      RMCSkillCqc: 1
      RMCSkillEndurance: 1
      RMCSkillEngineer: 4
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 1
      RMCSkillJtac: 2
      RMCSkillPowerLoader: 2
