- type: entity
  id: AU14SkillPresetOfficerMedical
  name: Chief Medical Officer
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillLeadership: 3
      RMCSkillJtac: 2
      RMCSkillNavigations: 1
      RMCSkillOverwatch: 1
      RMCSkillIntel: 1
      RMCSkillCqc: 1
      RMCSkillFirearms: 1
      RMCSkillEndurance: 2
      RMCSkillPilot: 1
      RMCSkillEngineer: 1
      RMCSkillConstruction: 1
      RMCSkillFireman: 2
      RMCSkillMedical: 5
      RMCSkillSurgery: 4
      RMCSkillPolice: 1
      RMCSkillResearch: 1

- type: entity
  id: AU14SkillPresetMilitaryDoctor
  name: Military Doctor
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 1
      RMCSkillOverwatch: 1
      RMCSkillLeadership: 1
      RMCSkillIntel: 1
      RMCSkillMedical: 4
      RMCSkillSurgery: 4
      RMCSkillPolice: 1

- type: entity
  id: AU14SkillPresetPlatoonHospitalCorpsman
  name: Hospital Corpsman
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 1
      RMCSkillCqc: 1
      RMCSkillEndurance: 1
      RMCSkillEngineer: 1
      RMCSkillFirearms: 1
      RMCSkillFireman: 3
      RMCSkillVehicles: 1
      RMCSkillMedical: 2
      RMCSkillSurgery: 1
      RMCSkillJtac: 1
