- type: job
  abstract: true
  parent: AU14JobMilitaryBase
  id: AU14JobSquadCombatTechBaseAbstract
  name: au14-job-name-govforsquadcombattech
  description: au14-job-description-govforsquadcombattech
  icon: "AU14JobIconGovCT"
  spawnMenuRoleName: Combat Tech (GOVFOR)
  playTimeTracker: AU14JobGOVFORSquadCombatTech
  startingGear: AU14GearGOVFORSquadCombatTech
  dummyStartingGear: AU14GearGOVFORCTDummy
  overwatchRoleName: au14-job-name-govforsquadcombattech
  overwatchSortPriority: -5
  accessGroups:
  - AU14GovforEngineer

- type: job
  abstract: true
  parent: AU14JobSquadCombatTechBaseAbstract
  id: AU14JobSquadCombatTechBase
  roundRole: SquadCombatTech
  roundProfiles:
  - AU14RoundJobProfileMilitaryBase
  roundComponents:
  - type: Skills
    preset: AU14SkillPresetPlatoonCombatTechnician
  - type: JobPrefix
    prefix: au14-job-prefix-govforsquadcombattech
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14govforjobicons.rsi
      state: govfor_ct
  - type: CMVendorUser
    id: AU14JobGOVFORSquadCombatTech
    points: 50
  roundForceComponents:
    OPFOR:
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14opforjobicons.rsi
        state: ct
    - type: CMVendorUser
      id: AU14JobOPFORSquadCombatTech
      points: 50
    RMC:
    - type: JobPrefix
      prefix: au14-job-prefix-govforsquadcombattechRMC
    WYPMC:
    - type: Skills
      skills:
        RMCSkillEndurance: 1
        RMCSkillFirearms: 2
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillFireman: 1
        RMCSkillVehicles: 1
        RMCSkillPolice: 1

  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
    - NonResuscitable
    - NoEnglish
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMCRankCorporal:
      entity: AU14ChevronUSCMCorporal
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFORSquadCombatTech
        time: 216000 # 60 hours
    RMCRankLanceCorporal:
      entity: AU14ChevronUSCMLanceCorporal
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFORSquadCombatTech
        time: 108000 # 30 hours
    RMCRankPrivateFirstClass:
      entity: AU14ChevronUSCMPrivateFirstClass
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFORSquadCombatTech
        time: 54000 # 15 hours
    RMCRankPrivate:
      entity: AU14ChevronUSCMPrivate
      requirements: []

- type: playTimeTracker
  id: AU14JobGOVFORSquadCombatTech
  isHumanoid: true

- type: startingGear
  id: AU14GearGOVFORSquadCombatTech
  equipment:
    id: AU14IDCardSquadCombatTech
    ears: AU14HeadsetGovforMarine

- type: startingGear
  id: AU14GearGOVFORCTDummy
  equipment:
    outerClothing: AU14ArmorM3JungleThree
    shoes: AU14BootsJungle
    head: AU14JungleM10Helmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetGovforMarine

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORSquadCombatTech
  name: Spawn Point GOVFOR Comtech
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORSquadCombatTech
  - type: Sprite
    state: syn_spawn

- type: job
  parent: AU14JobSquadCombatTechBase
  id: AU14JobGOVFORSquadCombatTech
  hidden: false
  setPreference: true
  basePlaytimeTracker: true

- type: roleLoadout
  id: JobAU14JobGOVFORSquadCombatTech
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: job
  parent: AU14JobSquadCombatTechBase
  id: AU14JobOPFORSquadCombatTech
  roundSide: Opfor
  roundForce: OPFOR
  icon: "AU14JobIconOPFORCT"
  spawnMenuRoleName: Combat Tech (OPFOR)
  supervisors: au14-job-supervisors-opfor
  startingGear: AU14GearOPFORSquadCombatTech
  dummyStartingGear: AU14GearOPFORCTDummy
  accessGroups:
  - AU14OpforEngineer

- type: startingGear
  id: AU14GearOPFORSquadCombatTech
  equipment:
    id: AU14IDCardOPFORCT
    ears: AU14HeadsetOpforMarine

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointOPFORSquadCombatTech
  name: Spawn Point OPFOR Comtech
  components:
  - type: SpawnPoint
    job_id: AU14JobOPFORSquadCombatTech
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearOPFORCTDummy
  equipment:
    outerClothing: AU14ArmorM3JungleThree
    shoes: AU14BootsJungle
    head: AU14JungleM10Helmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetOpforMarine

- type: job
  parent: AU14JobSquadCombatTechBase
  id: AU14JobGOVFORSquadCombatTechRMC
  roundForce: RMC
  name: au14-job-name-govforsquadcombattechRMC
  spawnMenuRoleName: Combat Tech (TWE RMC)
  ranks:
    RMC_Corporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 216000 # 60 hours
    RMC_LanceCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 108000 # 30 hours
    RMC_Marine: []

- type: job
  parent: AU14JobSquadCombatTechBase
  id: AU14JobGOVFORSquadCombatTechUPP
  roundForce: UPP
  spawnMenuRoleName: Combat Tech (UPP)
  ranks:
    UPP_Corporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadCombatTech
      time: 216000 # 60 hours
    UPP_SeniorGefreiter:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadCombatTech
      time: 108000 # 30 hours
    UPP_Gefreiter:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadCombatTech
      time: 54000 # 15 hours
    UPP_Private: []

- type: job
  parent: AU14JobSquadCombatTechBase
  id: AU14JobGOVFORSquadCombatTechWYPMC
  roundForce: WYPMC
  name: PMC Combat Technician
  spawnMenuRoleName: Combat Tech (WYPMC)
  ranks:
    AU14RankWeYuSeniorOperator:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadCombatTech
      time: 108000 # 30 hours
    AU14RankWeYuOperator: []
