- type: job
  parent: CMJobBase
  id: AU14RMCRRTRifleman
  roundSide: ThirdParty
  roundForce: RMC
  roundRole: AU14RMCRRTRifleman
  roundComponents:
  - type: Skills
    skills:
        RMCSkillEndurance: 2
        RMCSkillFirearms: 2
        RMCSkillConstruction: 1
        RMCSkillEngineer: 1
        RMCSkillFireman: 2
        RMCSkillVehicles: 1
        RMCSkillPolice: 2
        RMCSkillJtac: 1
        RMCSkillMedical: 1
        RMCSkillMeleeWeapons: 1
        RMCSkillCqc: 2
  - type: JobPrefix
    prefix: au14-job-prefix-govforsquadrifleman

  name: au14-job-name-govforsquadrifleman
  description: au14-rmcert-rules
  playTimeTracker: AU14JobRMCRRTRifleman
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMC_Marine:
      entity: AU14ChevronRMCMarine
      requirements: []
  spawnMenuRoleName: RMC RRT Rifleman
  startingGear: AU14GearRMCRRTRifleman
  icon: "RMCJobIconRoyalCommando"
  joinNotifyCrew: false
  supervisors: au-14-job-name-rmcrrt-commander
  accessGroups:
  - AU14GovforSquad
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicRMCRRT
  id: AU14JobRMCRRTRifleman
  name: RMC reaction troop rifleman
  components:
  - type: GhostRoleApplySpecial
    squad: AU14SquadRMCRRT
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: RMC reaction troop rifleman
    description: You have been dispatched as a Royal Marines Commando Rapid Reaction Troop member. The details of the mission have not been disclosed to you, however your main objective is to assist GOVFOR forces in the area of operation. You are friendly to GOVFOR command and neutral to civilians.
    job: AU14RMCRRTRifleman
    raffle:
      settings: short
    rules: au14-rmcert-rules

- type: startingGear
  id: AU14GearRMCRRTRifleman
  equipment:
    id: AU14IDCardRMCRRTRifleman
    outerClothing: AU14ArmorRMC
    jumpsuit: AU14FatiguesBlackRMC
    shoes: RMCBootsRoyalFilled
    eyes: AU14GogglesM1A1Ballistic
    mask: RMCMaskScarfTan
    head: AU14HeadHelmetRMC
    gloves: AU14HandsRMC
    belt: AU14BeltMarineRMCFullL90
    pocket1: RMCPouchToolsSocMarineRaiderFill
    pocket2: AU14PouchIFAKFill
    back: AU14RMCRRTBackpackRifleman
    ears: AU14HeadsetRMCRRT
    suitstorage: AU14WeaponRifleL90Full

- type: playTimeTracker
  id: AU14JobRMCRRTRifleman
