- type: job
  parent: CMJobBase
  id: AU14USArmyCMTBase
  name: au14-job-name-usarmy-cmt
  description: au14-job-description-usarmy
  playTimeTracker: AU14JobUSArmyCMT
  basePlaytimeTracker: true
  hidden: true

- type: job
  parent: AU14USArmyCMTBase
  id: AU14JobUSArmyCMTArmored
  roundSide: ThirdParty
  roundForce: USARMY
  roundRole: USArmyCMTArmored
  roundComponents:
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: engi
    background:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_ua
  - type: AssignSquad
    whitelist:
      tags:
      - AU14SquadUSArmy
  - type: Skills
    preset: AU14SkillPresetPlatoonHospitalCorpsman
  - type: SpotterWhitelist
  - type: JobPrefix
    prefix: au14-job-prefix-usarmy-cmt

  name: au14-job-name-usarmy-cmt
  description: au14-job-description-usarmy
  ranks:
    RMCRankCivilian: []
  chevrons:
    USArmy_Corporal:
      entity: AU14ChevronUSArmyCorporal
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobUSArmyCMT
        time: 36000
    USArmy_Specialist:
      entity: AU14ChevronUSArmySpecialist
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobUSArmyCMT
        time: 18000
    USArmy_PFC:
      entity: AU14ChevronUSArmyPFC
      requirements: []
  spawnMenuRoleName: US Army Combat Medical Tech (AU14, 3rd Party)
  startingGear: AU14GearUSArmyCMTArmored
  greeting: au14-usarmy-armored-greeting
  icon: "AU14JobIconUSArmyCMT"
  joinNotifyCrew: false
  supervisors: cm-job-name-squad-leader
  accessGroups:
  - AU14GovforSquad
  hidden: true

- type: entity
  parent: AU14BaseMobSpeciesOrganicUSArmy
  id: AU14JobUSArmyCMTArmored
  name: US Army Combat Medical Technician (ERT)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: AU14SquadUSArmy32nd
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: au14-job-name-usarmy-cmt
    description: au14-job-description-usarmy
    reregister: false
    job: AU14JobUSArmyCMTArmored
    raffle:
      settings: short
    rules: au14-usarmy-rules

- type: startingGear
  id: AU14GearUSArmyCMTArmored
  equipment:
    id: AU14IDCardUSArmyCMT
    outerClothing: AU14ArmorUSArmyNormal
    jumpsuit: AU14ArmyJumpsuitArmored
    gloves: AU14PVEHandsInsulatedBlackMarine
    shoes: AU14BootsUSArmyFilled
    eyes: RMCWeldingGoggles
    mask: RMCMaskKeffiyehBlue
    head: AU14HelmetUSArmy
    belt: AU14BeltMedicBagSupportSynthRMC
    pocket1: AU14PouchIFAKFill
    pocket2: RMCPouchMagazine
    back: AU14CMDefibrillator
    ears: AU14HeadsetUSArmyERT
    suitstorage: RMCWeaponRifleM54CFilled
  storage:
    head:
    - RMCGogglesBallisticPolarizedBlue
    pocket2:
    - CMMagazineRifleM54C
    - CMMagazineRifleM54C
    - CMMagazineRifleM54C

- type: jobIcon
  parent: CMJobIconBase
  id: AU14JobIconUSArmyCMT
  icon:
    sprite: _AU14/Interface/job_icons.rsi
    state: hudsquad_cmt

- type: playTimeTracker
  id: AU14JobUSArmyCMT
