- type: job
  parent: CMJobBase
  id: AU14USArmySynthBase
  name: rmc-job-name-forecon-synth
  description: au14-job-description-usarmy
  playTimeTracker: AU14JobUSArmySynth
  basePlaytimeTracker: true
  hidden: true

- type: job
  parent: AU14USArmySynthBase
  id: AU14JobUSArmySynthArmored
  roundSide: ThirdParty
  roundForce: USARMY
  roundRole: USArmySynthArmored
  roundComponents:
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: forecon_synth
  - type: AssignSquad
    whitelist:
      tags:
      - AU14SquadUSArmy
  - type: Skills
    skills:
      RMCSkillCqc: 5
      RMCSkillEngineer: 4
      RMCSkillConstruction: 3
      RMCSkillFirearms: 2
      RMCSkillOverwatch: 1
      RMCSkillMedical: 4
      RMCSkillSurgery: 3
      RMCSkillResearch: 1
      RMCSkillMeleeWeapons: 2
      RMCSkillPilot: 2
      RMCSkillPolice: 2
      RMCSkillFireman: 5
      RMCSkillPowerLoader: 2
      RMCSkillVehicles: 2
      RMCSkillJtac: 3
      RMCSkillIntel: 2
      RMCSkillDomestics: 2
      RMCSkillNavigations: 1
  - type: DemoSpecWhitelist
  - type: GrenadeSpecWhitelist
  - type: ScoutWhitelist
  - type: SniperWhitelist
  - type: PyroWhitelist
  - type: JobPrefix
    prefix: rmc-job-prefix-synth
  - type: MeleeWeapon
    soundHit:
      path: /Audio/_RMC14/Weapons/synthpunch1.ogg
      params:
        variation: 0.15
        volume: -1
    angle: 30
    animation: WeaponArcFist
    attackRate: 1
    damage:
      types:
        Blunt: 35
  - type: Synth
  - type: Language
    preset: AU14LanguagePresetSynth
  - type: LanguageLearning
    preset: AU14LanguageLearningPresetSynth

  name: rmc-job-name-forecon-synth
  description: au14-job-description-usarmy
  ranks:
    RMCRankSyntheticColonist: []
  chevrons:
    USArmy_ChiefWarrantOfficer5:
      entity: AU14ChevronUSArmyChiefWarrantOfficer5
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobUSArmySynth
        time: 252000
    USArmy_ChiefWarrantOfficer4:
      entity: AU14ChevronUSArmyChiefWarrantOfficer4
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobUSArmySynth
        time: 180000
    USArmy_ChiefWarrantOfficer3:
      entity: AU14ChevronUSArmyChiefWarrantOfficer3
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobUSArmySynth
        time: 36000
    USArmy_ChiefWarrantOfficer2:
      entity: AU14ChevronUSArmyChiefWarrantOfficer2
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobUSArmySynth
        time: 18000
    USArmy_WarrantOfficer1:
      entity: AU14ChevronUSArmyWarrantOfficer
      requirements: []
  spawnMenuRoleName: US Army Synthetic (AU14, 3rd Party)
  startingGear: AU14GearUSArmySynthArmored
  greeting: au14-usarmy-armored-greeting
  icon: "AU14JobIconUSArmySynth"
  joinNotifyCrew: false
  supervisors: rmc-job-name-forecon-commander
  accessGroups:
  - AU14GovforCommand
  hidden: true

- type: entity
  parent: AU14BaseMobSpeciesOrganicUSArmy
  id: AU14JobUSArmySynthArmored
  name: US Army Synthetic (ERT)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: AU14SquadUSArmy32nd
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: rmc-job-name-forecon-synth
    description: au14-job-description-usarmy
    reregister: false
    job: AU14JobUSArmySynthArmored
    raffle:
      settings: short
    rules: au14-usarmy-rules

- type: startingGear
  id: AU14GearUSArmySynthArmored
  equipment:
    id: AU14IDCardUSArmySynth
    outerClothing: AU14ArmorUSArmySynth
    head: AU14JunglePatrolCap
    jumpsuit: AU14ArmyJumpsuitArmored
    gloves: AU14PVEHandsInsulatedBlackMarine
    shoes: AU14BootsUSArmyFilled
    belt: AU14BeltMedicBagSupportSynthRMC
    pocket1: AU14PouchToolsFilledComtech
    pocket2: AU14PouchPoliceEquipmentSupportSynth
    back: AU14CMDefibrillator
    ears: AU14HeadsetUSArmyERT

- type: jobIcon
  parent: CMJobIconBase
  id: AU14JobIconUSArmySynth
  icon:
    sprite: _AU14/Interface/job_icons.rsi
    state: hudsquad_syn_army

- type: playTimeTracker
  id: AU14JobUSArmySynth
