- type: job
  parent: CMJobBase
  id: AU14USArmySquadLeaderBase
  name: cm-job-name-squad-leader
  description: au14-job-description-usarmy
  playTimeTracker: AU14JobUSArmySquadLeader
  basePlaytimeTracker: true
  hidden: true

- type: job
  parent: AU14USArmySquadLeaderBase
  id: AU14JobUSArmySquadleaderArmored
  roundSide: ThirdParty
  roundForce: USARMY
  roundRole: USArmySquadleaderArmored
  roundComponents:
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: leader
    background:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_ua
  - type: AssignSquad
    whitelist:
      tags:
      - AU14SquadUSArmy
  - type: Skills
    preset: AU14SkillPresetPlatoonSeniorSergeant
  - type: SpotterWhitelist
  - type: JobPrefix
    prefix: cm-job-prefix-squad-leader
  - type: MarineOrders
    moveOrderSoundMale:
      collection: AU14MaleMoveOrder
    moveOrderSoundFemale:
      collection: AU14FemaleMoveOrder
    focusOrderSoundMale:
      collection: AU14MaleFocusOrder
    focusOrderSoundFemale:
      collection: AU14FemaleFocusOrder
    holdOrderSoundMale:
      collection: AU14MaleHoldOrder
    holdOrderSoundFemale:
      collection: AU14FemaleHoldOrder
  - type: SquadLeader
  - type: RMCTrackable
  - type: RMCPointing

  name: cm-job-name-squad-leader
  description: au14-job-description-usarmy
  ranks:
    RMCRankCivilian: []
  chevrons:
    USArmy_FirstSergeant:
      entity: AU14ChevronUSArmyFirstSergeant
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobUSArmySquadLeader
        time: 36000
    USArmy_MasterSergeant:
      entity: AU14ChevronUSArmyMasterSergeant
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobUSArmySquadLeader
        time: 18000
    USArmy_SergeantFirstClass:
      entity: AU14ChevronUSArmySergeantFirstClass
      requirements: []
  spawnMenuRoleName: US Army Squad Leader (AU14, 3rd Party)
  startingGear: AU14GearUSArmySquadleaderArmored
  greeting: au14-usarmy-armored-greeting
  icon: "AU14JobIconUSArmySL"
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-platco
  accessGroups:
  - AU14GovforCommand
  hidden: true

- type: entity
  parent: AU14BaseMobSpeciesOrganicUSArmy
  id: AU14JobUSArmySquadLeaderArmored
  name: US Army Squad Leader (ERT)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: AU14SquadUSArmy32nd
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: cm-job-name-squad-leader
    description: au14-job-description-usarmy
    reregister: false
    job: AU14JobUSArmySquadleaderArmored
    raffle:
      settings: short
    rules: au14-usarmy-rules

- type: startingGear
  id: AU14GearUSArmySquadleaderArmored
  equipment:
    id: AU14IDCardUSArmySquadleader
    outerClothing: AU14ArmorUSArmyNormal
    jumpsuit: AU14ArmyJumpsuitArmored
    gloves: AU14PVEHandsInsulatedBlackMarine
    shoes: AU14BootsUSArmyFilled
    mask: RMCMaskScarfTan
    head: AU14HelmetUSArmy
    belt: AU14BeltHolsterPistolUSArmyFull
    pocket1: AU14PouchSlingBinocs
    pocket2: AU14PouchIFAKFill
    back: AU14MolleSatchel
    ears: AU14HeadsetUSArmyERT
    suitstorage: RMCWeaponRifleM54C
  storage:
    head:
      - AU14GogglesM1A1DarkBallistic
    back:
    - CMMagazineRifleM54C
    - CMMagazineRifleM54C
    - CMMagazineRifleM54C
    - CMMagazineRifleM54C

- type: jobIcon
  parent: CMJobIconBase
  id: AU14JobIconUSArmySL
  icon:
    sprite: _AU14/Interface/job_icons.rsi
    state: hudsquad_sl_army

- type: playTimeTracker
  id: AU14JobUSArmySquadLeader
