- type: job
  parent: CMJobBase
  id: AU14LACNCommandoSpotter
  roundSide: ThirdParty
  roundForce: LACN
  roundRole: AU14LACNCommandoSpotter
  roundComponents:
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: spotter
  - type: Skills
    skills:
      RMCSkillCqc: 1
      RMCSkillEndurance: 1
      RMCSkillFirearms: 2
      RMCSkillFireman: 2
      RMCSkillIntel: 2
      RMCSkillJtac: 4
      RMCSkillMedical: 1
      RMCSkillVehicles: 1
  - type: SpotterWhitelist
  - type: JobPrefix
    prefix: au14-job-prefix-forecon-spotter
  - type: Language
    spokenLanguages:
    - English
    - Brazilian
    - Spanish
    understoodLanguages:
    - English
    - Brazilian
    - Spanish
    currentLanguage: Brazilian
    defaultLanguage: Brazilian

  name: au14-job-name-forecon-spotter
  playTimeTracker: AU14LACNCommandoSpotter
  description: au14-lacncommando-description
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMCRankChiefWarrantOfficer:
      entity: AU14ChevronLACNMasterChief
      requirements:
      - !type:RoleTimeRequirement
        role: AU14LACNCommandoSpotter
        time: 18000 # 5 hours
    RMCRankWarrantOfficer:
      entity: AU14ChevronLACNSeniorChief
      requirements: []
  spawnMenuRoleName: LACN Commando Spotter (AU14, 3rd Party)
  startingGear: AU14GearLACNCommandoSniperTeamSpotter
  greeting: au14-lacncommando-description
  icon: "CMJobIconEmpty"
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-loner
  hidden: true

- type: entity
  parent: AU14BaseMobSpeciesOrganicLACN
  suffix: AU14, LACN
  id: AU14JobCommandoSniperTeamSpotter
  name: LACN Commando Spotter (3rd party)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: AU14SquadLACNCommando
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: au14-job-name-forecon-spotter
    description: au14-lacncommando-description
    reregister: false
    job: AU14LACNCommandoSpotter
    raffle:
      settings: short
    rules: au14-lacncommandosniper-rules

- type: startingGear
  id: AU14GearLACNCommandoSniperTeamSpotter
  equipment:
    id: AU14IDCardLACNCommandoSpotter
    outerClothing: AU14LACNCommandoArmorStandard
    jumpsuit: AU14LACNUniformCoat
    shoes: AU14LACNBoots
    mask: RMCMaskScarfTanDown
    head: AU14LACNCommandoBeanie
    gloves: AU14LACNGloves
    belt: AU14BeltHolsterPistolLACNTPR23B
    pocket1: AU14PouchSlingBinocs
    pocket2: AU14PouchIFAKFill
    back: AU14LACNBackpackSpotter
    ears: AU14HeadsetGovforMarine
    suitstorage: RMCWeaponRifleL42A

- type: playTimeTracker
  id: AU14LACNCommandoSpotter
