- type: job
  parent: CMJobBase
  id: AU14JobFORECONSpotterBase
  name: au14-job-name-forecon-spotter
  description: rmc-job-description-forecon-detachment
  playTimeTracker: AU14FORECONSpotterDetachment
  basePlaytimeTracker: true
  hidden: true

- type: job
  parent: AU14JobFORECONSpotterBase
  id: AU14FORECONSpotterDetachment
  roundSide: ThirdParty
  roundForce: FORECON
  roundRole: AU14FORECONSpotterDetachment
  roundComponents:
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: spotter
  - type: Skills
    preset: AU14SkillPresetPlatoonRifleman
  - type: SpotterWhitelist
  - type: JobPrefix
    prefix: au14-job-prefix-forecon-spotter
  - type: LanguagePreset
    spokenLanguages:
    - English
    - TacticalSignLanguage
    understoodLanguages:
    - English
    - TacticalSignLanguage
    currentLanguage: English
    defaultLanguage: English

  name: au14-job-name-forecon-spotter
  description: rmc-job-description-forecon-detachment
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMCRankWarrantOfficer:
      entity: AU14ChevronUSCMChiefWarrantOfficer2
      requirements: []
  spawnMenuRoleName: FORECON Spotter (AU14, Detachment)
  startingGear: AU14GearFORECONSpotterDetachment
  greeting: au14-forecon-detachment-greeting
  icon: "AU14Spotter"
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-platco
  accessGroups:
  - AU14GovforSquad
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicFORECON
  suffix: AU14, FORECON, Detachment
  id: AU14JobFORECONSpotterDetachment
  name: FORECON Spotter (Detachment)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: SquadFORECON
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: au14-job-name-forecon-spotter
    description: rmc-job-description-forecon-detachment
    reregister: false
    job: AU14FORECONSpotterDetachment
    raffle:
      settings: short
    rules: au14-forecon-detachment-rules

- type: startingGear
  id: AU14GearFORECONSpotterDetachment
  equipment:
    id: AU14IDCardFORECONSpotterDetachment
    ears: AU14HeadsetFORECONERT
  inhand:
  - AU14KitFORECONDetachmentUniform
  - AU14KitFORECONDetachmentSpotter

- type: jobIcon
  parent: CMJobIconBase
  id: AU14Spotter
  icon:
    sprite: _RMC14/Interface/cm_job_icons.rsi
    state: hudsquad_ass

- type: playTimeTracker
  id: AU14FORECONSpotterDetachment
