- type: loadout
  id: BeltUtilityFilledAU14
  equipment:
    belt: AU14BeltUtilityFilled

- type: loadout
  id: IntelDetectorAU14
  equipment:
    belt: RMCIntelDetector

- type: loadout
  id: BeltSecurityMPFilledAU14
  equipment:
    belt: CMBeltSecurityMPFilled

- type: loadout
  id: EngiBeltUtilityFilledAU14
  equipment:
    belt: AU14BeltUtilityFilled

- type: loadout
  id: BeltUtilityGeneralAU14
  equipment:
    belt: RMCBeltUtilityGeneral

- type: loadout
  id: BeltMedicalFilledAU14
  equipment:
    belt: AU14BeltMedicalFilled

- type: loadout
  id: BeltMedicBagFilledAU14
  equipment:
    belt: AU14BeltMedicBagFilled
