- type: job
  parent: CMJobBase
  id: AU14JobCivilianProfessorVonBandolier
  roundSide: ThirdParty
  roundForce: MISC
  roundRole: CivilianProfessorVonBandolier
  roundComponents:
  - type: NpcFactionMember
    factions:
    - AUBureau
  - type: Skills
    skills:
        RMCSkillConstruction: 2
        RMCSkillCqc: 2
        RMCSkillEndurance: 2
        RMCSkillFirearms: 3
        RMCSkillFireman: 2
        RMCSkillIntel: 1
        RMCSkillJtac: 1
        RMCSkillLeadership: 1
        RMCSkillMedical: 2
        RMCSkillSurgery: 1
        RMCSkillVehicles: 1
  - type: JobPrefix
    prefix: au14-job-prefix-civiliancolonist
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth

  name: Professor Von Bandolier
  description: Find the biggest and most dangerous game, whether that is space alien or a man with a gun and eloquently shoot them.
  setPreference: true
  playTimeTracker: AU14JobCivilianProfessorVonBandolier
  ranks:
    AU14RankScientistProfessor: []
  startingGear: AU14GearProfessorVonBandolier
  icon: "CMJobIconEmpty"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-loner
  accessGroups:
  - Colonist
  roleWeight: 0.25
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicMisc
  id: AU14PartyJobProfessorVonBandolier
  name: Professor Von Bandolier
  components:
  - type: GhostTakeoverAvailable
  - type: RandomHumanoidAppearanceWhitelisted #civilian type
    allowedMaleHairStyles:
    - RMCHumanHairBalding
    - RMCHumanHairCrew
    - RMCHumanHairLtRasczak
    allowedFemaleHairStyles:
    - AU14HumanHairLowPonyTail
    - RMCHumanHairFlair2
    - AU14HumanHairElegant
    allowedHairColorsHex:
    - "#995b2e"
    allowedEyeColorsHex: [ "#995b2e" ]
    beardChance: 0
  - type: GhostRoleApplySpecial
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: Professor Von Bandolier
    description: Find the biggest and most dangerous game, whether that is space alien or a man with a gun and eloquently shoot them.
    reregister: false
    job: AU14JobCivilianProfessorVonBandolier
    raffle:
      settings: short
    rules: au14-professorvonbandolier-rules

- type: partySpawn
  id: ProfessorVonBandolierSpawn
  leadersToSpawn:
    AU14PartyJobVonBandolier: 1
  scalewithpop: false
  spawnTogether: true

- type: thirdParty
  id: ProfessorVonBandolier
  partyspawn: ProfessorVonBandolierSpawn
  entrymethod: shuttle
  weight: 1
  minplayers: 50
  maxplayers: 400
  GhostsNeeded: 0
  roundstart: true

- type: startingGear
  id: AU14GearProfessorVonBandolier
  equipment:
    id: AU14IDCardCivilianProfessorVonBandolier
    outerClothing: CMArmorDutchJacketVonBandolier
    jumpsuit: RMCJumpsuitDutchBandolier
    shoes: RMCBootsVanBandolier
    head: AU14HeadPithHelmet
    gloves: RMCHandsDeluxeMarine
    belt: AU14M276ShotgunShellLoadingRigBlackVonBandolier
    pocket1: RMCPouchMagazinePistolLargeVonBandolier
    pocket2: RMCPouchMedkitVonBandolier
    back: AU14WeaponRifleTwoBore
    suitstorage: RMCBeltHolsterRevolverVonBandolier

- type: entity
  parent: AU14M276ShotgunShellLoadingRigBlack
  id: AU14M276ShotgunShellLoadingRigBlackVonBandolier
  suffix: Filled, Professor Von Bandolier
  components:
  - type: StorageFill
    contents:
    - id: AU14CartridgeRifleTwoBore
      amount: 14

- type: entity
  parent: CMArmorDutchJacket
  id: CMArmorDutchJacketVonBandolier
  suffix: Filled, Professor Von Bandolier
  components:
  - type: StorageFill
    contents:
    - id: RMCShioRoyalsCase
    - id: RMCZippoGold

- type: entity
  parent: RMCPouchMedkit
  id: RMCPouchMedkitVonBandolier
  suffix: Filled, Professor Von Bandolier
  components:
  - type: StorageFill
    contents:
    - id: AU14HemostaticGauzePacket
    - id: AU14Tourniquet
    - id: AU14Tourniquet
    - id: CMPacketPillsTricordrazine
    - id: AU14PacketPillsTramadol
    - id: CMUSplintItem
    - id: CMUSplintItem

- type: entity
  parent: RMCPouchMagazinePistolLarge
  id: RMCPouchMagazinePistolLargeVonBandolier
  suffix: Filled, Professor Von Bandolier
  components:
  - type: StorageFill
    contents:
    - id: RMCSpeedLoader44Marksman
      amount: 6

- type: entity
  parent: RMCBeltHolsterRevolver
  id: RMCBeltHolsterRevolverVonBandolier
  suffix: Filled, Professor Von Bandolier
  components:
  - type: StorageFill
    contents:
    - id: RMCWeaponRevolverM44Marksman
    - id: RMCSpeedLoader44Marksman
      amount: 6

- type: playTimeTracker
  id: AU14JobCivilianProfessorVonBandolier
  isHumanoid: true
