- type: job
  parent: CMJobBase
  id: AU14JobCLFMachineGunnerReinforcement
  roundSide: ThirdParty
  roundForce: CLF
  roundRole: CLFMachineGunnerReinforcement
  roundComponents:
  - type: EquipEntityPreset
    preset: AU14CLFGuerillaReinforcement
  - type: NpcFactionMember
    factions:
    - CLF
  - type: CLFMember
  - type: Skills
    skills:
      RMCSkillEndurance: 2
      RMCSkillCqc: 1
      RMCSkillMedical: 1
      RMCSkillFirearms: 1
      RMCSkillEngineer: 1
      RMCSkillVehicles: 1
      RMCSkillPolice: 2
      RMCSkillJtac: 2
      RMCSkillSmartGun: 1
  - type: JobPrefix
    prefix: au14-job-prefix-clfmachinegunner
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth
  - type: ShowMarineIcons
    factions:
    - CLF
  - type: FactionLanguageMember
    factionTag: CLF

  name: au14-job-name-clfmachinegunner
  description: au14-job-description-clfmachinegunner
  setPreference: true
  ignoreAllegiance: true
  playTimeTracker: AU14JobCLFMachineGunner
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - NonResuscitable
    - Epilepsy
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCLFMachineGunnerReinforcement
  spawnMenuRoleName: CLF Machinegunner (Reinforcements)
  icon: "CMJobIconEmpty"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-clflrs
  accessGroups:
  - Colonist
  roleWeight: 0.25
  hidden: false

- type: startingGear
  id: AU14GearCLFMachineGunnerReinforcement
  equipment:
    outerClothing: AU14ArmorBallisticVest
    gloves: CMHandsInsulated
    neck: RMCCLFArmband
    id: AU14IDCardColonyColonist
  inhand:
  - RMCWeaponLMGM60
  - AU14CLFHeadset

- type: entity
  parent: AU14BaseMobSpeciesOrganicBaseMilitary
  id: AU14IntelThirdPartyCLFInsurgentReinforcementsMachineGunner
  name: Insurgent Machine Gunner
  components:
  - type: GhostRoleApplySpecial
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: Insurgent Reinforcements
    description: You have been sent from a neighboring insurgent cell to aid the uprising in this area. Report to the local cell leader for orders.
    job: AU14JobCLFMachineGunnerReinforcement
    raffle:
      settings: short
  - type: Skills
    skills:
       RMCSkillEndurance: 2
       RMCSkillFirearms: 2
       RMCSkillConstruction: 2
       RMCSkillEngineer: 3
       RMCSkillFireman: 2
       RMCSkillVehicles: 1
       RMCSkillPolice: 1
