- type: job
  parent: CMJobBase
  id: AU14JobWYPMCPartyEngineer #m41a/2
  roundSide: ThirdParty
  roundForce: WY
  roundRole: WYPMCPartyEngineer
  roundComponents:
  - type: NpcFactionMember
    factions:
    - AUWeYu
  - type: Skills
    preset: AU14SkillPresetPlatoonCombatTechnician
  - type: JobPrefix
    prefix: au14-job-prefix-govforsquadcombattech
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth

  name: au14-job-name-wypmc-engineer
  description: au14-pmcparty-description
  playTimeTracker: AU14JobWYPMCPartyEngineer
  ranks:
    AU14RankWeYuOperator: []
  spawnMenuRoleName: WY PMC Combat Engineer (3rd party, M41A/2)
  startingGear: AU14GearWYPMCPartyEngineer
  greeting: au14-pmcparty-greeting
  icon: "RMCJobIconPMCEngineer"
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-wy
  accessGroups:
  - auwy
  - AUPrisonStaff
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicWeYu
  id: AU14JobWYPMCPartyEngineer
  name: WY PMC Party Combat Engineer (3rd party, M41A/2)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: SquadPMC
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: au14-job-name-wypmc-engineer
    description: au14-pmcparty-description
    reregister: false
    job: AU14JobWYPMCPartyEngineer
    raffle:
      settings: short
    rules: au14-wypmc-description

- type: startingGear
  id: AU14GearWYPMCPartyEngineer
  equipment:
    id: AU14IDCardColonyCorporateLiaison
    outerClothing: AU14WYPMCArmorEngineer
    jumpsuit: AU14WYPMCFatiguesEngineer
    shoes: RMCBootsPMCFilled
    head: AU14ArmorHelmetPMCTacticalEngi
    gloves: AU14PVEHandsInsulatedBlackMarine
    belt: AU14BeltUtilityFilled
    pocket1: RMCPouchMagazineLargePMC
    pocket2: AU14PouchIFAKFill
    back: RMCSatchelLightpackWeYa
    ears: RMCHeadsetDistressWeYa
    suitstorage: RMCWeaponRifleM54C2
  storage:
    belt:
    - AU14MaintenanceJack
    pocket1:
    - CMMagazineRifleM54CAP
    - CMMagazineRifleM54CAP
    - CMMagazineRifleM54CAP
    - CMMagazineRifleM54CAP
    back:
    - RMCMREWeYa
    - CMCanteen
    - AU14CMDefibrillator
    - CMMagazineRifleM54CAP
    - CMMagazineRifleM54CAP
    - RMCExplosivePlastic
    - RMCExplosivePlastic

- type: playTimeTracker
  id: AU14JobWYPMCPartyEngineer
