- type: job
  parent: CMJobBase
  id: AU14JobWYPMCPartyContractorBase
  name: PMC Contractor
  description: au14-pmcparty-description
  playTimeTracker: AU14JobWYPMCPartyContractor
  basePlaytimeTracker: true
  hidden: true

- type: job
  parent: AU14JobWYPMCPartyContractorBase
  id: AU14JobWYPMCPartyContractor #m41a/2
  roundSide: ThirdParty
  roundForce: WY
  roundRole: WYPMCPartyContractor
  roundComponents:
  - type: NpcFactionMember
    factions:
    - AUWeYu
  - type: Skills
    skills:
      RMCSkillEndurance: 3
      RMCSkillFirearms: 2
      RMCSkillConstruction: 2
      RMCSkillEngineer: 2
      RMCSkillFireman: 2
      RMCSkillPolice: 2
  - type: JobPrefix
    prefix: au14-job-prefix-AU14JobGOVFORSquadRiflemanWYPMC
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth
  name: PMC Contractor
  description: au14-pmcparty-description
  ranks:
    AU14RankWeYuRecruit: []
  startingGear: AU14GearWYPMCPartyContractor
  greeting: au14-pmcparty-greeting
  icon: "RMCJobIconPMCStandard"
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-wy
  accessGroups:
  - auwy
  - AUPrisonStaff
  hidden: false

- type: job
  parent: AU14JobWYPMCPartyContractorBase
  id: AU14JobWYPMCPartyContractorM39B2
  roundSide: ThirdParty
  roundForce: WY
  roundRole: WYPMCPartyContractorM39B2
  roundComponents:
  - type: NpcFactionMember
    factions:
    - AUWeYu
  - type: Skills
    skills:
      RMCSkillEndurance: 1
      RMCSkillFirearms: 2
      RMCSkillConstruction: 2
      RMCSkillEngineer: 3
      RMCSkillFireman: 1
      RMCSkillVehicles: 1
      RMCSkillPolice: 1
  - type: JobPrefix
    prefix: au14-job-prefix-AU14JobGOVFORSquadRiflemanWYPMC
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth
  name: PMC Contractor
  description: au14-pmcparty-description
  ranks:
    AU14RankWeYuRecruit: []
  spawnMenuRoleName: WY PMC Contractor (3rd party, M39B/2)
  startingGear: AU14GearWYPMCPartyContractorM39B2
  greeting: au14-pmcparty-greeting
  icon: "RMCJobIconPMCStandard"
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-wy
  accessGroups:
  - auwy
  - AUPrisonStaff
  hidden: false

- type: job
  parent: AU14JobWYPMCPartyContractorBase
  id: AU14JobWYPMCPartyContractorNSG23
  roundSide: ThirdParty
  roundForce: WY
  roundRole: WYPMCPartyContractorNSG23
  roundComponents:
  - type: NpcFactionMember
    factions:
    - AUWeYu
  - type: Skills
    skills:
      RMCSkillEndurance: 1
      RMCSkillFirearms: 2
      RMCSkillConstruction: 2
      RMCSkillEngineer: 3
      RMCSkillFireman: 1
      RMCSkillVehicles: 1
      RMCSkillPolice: 1
  - type: JobPrefix
    prefix: au14-job-prefix-AU14JobGOVFORSquadRiflemanWYPMC
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth
  name: PMC Contractor
  description: au14-pmcparty-description
  ranks:
    AU14RankWeYuRecruit: []
  spawnMenuRoleName: WY PMC Contractor (3rd party, NSG-23)
  startingGear: AU14GearWYPMCPartyContractorNSG23
  greeting: au14-pmcparty-greeting
  icon: "RMCJobIconPMCStandard"
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-wy
  accessGroups:
  - auwy
  - AUPrisonStaff
  hidden: false

- type: job
  parent: AU14JobWYPMCPartyContractorBase
  id: AU14JobWYPMCPartyContractorM42A # m42a
  roundSide: ThirdParty
  roundForce: WY
  roundRole: WYPMCPartyContractorM42A
  roundComponents:
  - type: NpcFactionMember
    factions:
    - AUWeYu
  - type: Skills
    skills:
      RMCSkillEndurance: 1
      RMCSkillFirearms: 2
      RMCSkillConstruction: 2
      RMCSkillEngineer: 3
      RMCSkillFireman: 1
      RMCSkillVehicles: 1
      RMCSkillPolice: 1
  - type: JobPrefix
    prefix: au14-job-prefix-AU14JobGOVFORSquadRiflemanWYPMC
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth
  name: PMC Sniper
  description: au14-pmcparty-description
  ranks:
    AU14RankWeYuOperator: []
  spawnMenuRoleName: WY PMC Sniper (3rd party, M42A)
  startingGear: AU14GearWYPMCPartyContractorM42A
  greeting: au14-pmcparty-greeting
  icon: "RMCJobIconPMCSniper"
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-wy
  accessGroups:
  - auwy
  - AUPrisonStaff
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicWeYu
  id: AU14JobWYPMCPartyContractor
  name: WY PMC Party Contractor (3rd party, M41A/2)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: SquadPMC
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: PMC Contractor
    description: au14-pmcparty-description
    reregister: false
    job: AU14JobWYPMCPartyContractor
    raffle:
      settings: short
    rules: au14-wypmc-description

- type: entity
  parent: AU14BaseMobSpeciesOrganicWeYu
  id: AU14JobWYPMCPartyContractorM39B2
  name: WY PMC Party Contractor (3rd party, M39B/2)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: SquadPMC
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: PMC Contractor
    description: au14-pmcparty-description
    reregister: false
    job: AU14JobWYPMCPartyContractorM39B2
    raffle:
      settings: short
    rules: au14-wypmc-description

- type: entity
  parent: AU14BaseMobSpeciesOrganicWeYu
  id: AU14JobWYPMCPartyContractorNSG23
  name: WY PMC Party Contractor (3rd party, NSG-23)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: SquadPMC
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: PMC Contractor
    description: au14-pmcparty-description
    reregister: false
    job: AU14JobWYPMCPartyContractorNSG23
    raffle:
      settings: short
    rules: au14-wypmc-description

- type: entity
  parent: AU14BaseMobSpeciesOrganicWeYu
  id: AU14JobWYPMCPartyContractorM42A
  name: WY PMC Party Sniper (3rd party, M42A)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: SquadPMC
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: PMC Sniper
    description: au14-pmcparty-description
    reregister: false
    job: AU14JobWYPMCPartyContractorM42A
    raffle:
      settings: short
    rules: au14-wypmc-description

- type: startingGear
  id: AU14GearWYPMCPartyContractor
  equipment:
    id: AU14IDCardColonyCorporateLiaison
    outerClothing: AU14WYPMCArmor
    jumpsuit: AU14WYPMCFatigues
    shoes: RMCBootsPMCFilled
    head: AU14ArmorHelmetPMCTactical
    gloves: AU14PVEHandsInsulatedBlackMarine
    belt: RMCMK80BeltPMCFilled
    pocket1: RMCPouchMagazineLargePMC
    pocket2: AU14PouchIFAKFill
    back: RMCSatchelLightpackWeYa
    ears: RMCHeadsetDistressWeYa
    suitstorage: RMCWeaponRifleM54C2
  storage:
    pocket1:
    - CMMagazineRifleM54CAP
    - CMMagazineRifleM54CAP
    - CMMagazineRifleM54CAP
    - CMMagazineRifleM54CAP
    back:
    - RMCMREWeYa
    - CMCanteen
    - CMMagazineRifleM54CAP
    - CMMagazineRifleM54CAP
    - CMMagazineRifleM54CAP
    - RMCGrenadeBlastM12
    - RMCGrenadeBlastM12

- type: startingGear
  id: AU14GearWYPMCPartyContractorM39B2
  parent: AU14GearWYPMCPartyContractor
  equipment:
    outerClothing: AU14WYPMCArmorMin
    suitstorage: RMCWeaponSMGM63B2
  storage:
    pocket1:
    - CMMagazineSMGM63AP
    - CMMagazineSMGM63AP
    - CMMagazineSMGM63AP
    - CMMagazineSMGM63AP
    back:
    - RMCMREWeYa
    - CMCanteen
    - CMMagazineSMGM63AP
    - CMMagazineSMGM63AP
    - CMMagazineSMGM63AP
    - RMCGrenadeBlastM12
    - RMCGrenadeBlastM12

- type: startingGear
  id: AU14GearWYPMCPartyContractorNSG23
  parent: AU14GearWYPMCPartyContractor
  equipment:
    suitstorage: RMCWeaponRifleSSG45
  storage:
    pocket1:
    - RMCMagazineRifleSSG45AP
    - RMCMagazineRifleSSG45AP
    - RMCMagazineRifleSSG45AP
    - RMCMagazineRifleSSG45AP
    back:
    - RMCMREWeYa
    - CMCanteen
    - RMCMagazineRifleSSG45AP
    - RMCMagazineRifleSSG45AP
    - RMCMagazineRifleSSG45AP
    - RMCGrenadeBlastM12
    - RMCGrenadeBlastM12

- type: startingGear
  id: AU14GearWYPMCPartyContractorM42A
  parent: AU14GearWYPMCPartyContractor
  equipment:
    outerClothing: AU14WYPMCArmorMin
    head: AU14WYPMCSniperHat
    suitstorage: CMM96SSniperRifle
  storage:
    pocket1:
    - CMMagazineSniperM96S
    - CMMagazineSniperM96S
    - CMMagazineSniperM96S
    - CMMagazineSniperM96S
    back:
    - RMCMREWeYa
    - CMCanteen
    - CMMagazineSniperM96S
    - CMMagazineSniperM96S
    - CMMagazineSniperM96S
    - RMCGrenadeBlastM12
    - RMCGrenadeBlastM12

- type: playTimeTracker
  id: AU14JobWYPMCPartyContractor
