- type: job
  parent: AU14FORECONSmartGunOperatorBase
  id: AU14FORECONFirstReconSmartGunOperator
  roundSide: ThirdParty
  roundForce: FORECON
  roundRole: AU14FORECONFirstReconSmartGunOperator
  roundComponents:
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: smartgunner
    background:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_forecon
  - type: AssignSquad
    whitelist:
      tags:
      - AU14SquadFirstRecon
  - type: Skills
    preset: AU14SkillPresetPlatoonAutomaticRifleman
  - type: SpotterWhitelist
  - type: JobPrefix
    prefix: cm-job-prefix-gun-operator
  - type: LanguagePreset
    spokenLanguages:
    - English
    - TacticalSignLanguage
    understoodLanguages:
    - English
    - TacticalSignLanguage
    currentLanguage: English
    defaultLanguage: English

  name: au14-job-name-govforsquadautomaticriflemanRMC
  description: au14-job-description-forecon-firstrecon
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMCRankLanceCorporal:
      entity: AU14ChevronUSCMLanceCorporal
      requirements: []
  spawnMenuRoleName: FORECON Automatic Rifleman (AU14, 3rd party)
  startingGear: AU14GearFORECONFirstReconSmartGunOperator
  greeting: au14-job-description-forecon-firstrecon-greeting
  icon: "CMJobIconEmpty"
  joinNotifyCrew: false
  supervisors: cm-job-name-squad-leader
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicFORECON
  id: AU14JobFORECONFirstReconSmartGunOperator
  name: FORECON Automatic Rifleman (3rd party)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: AU14SquadFirstRecon
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: cm-job-name-smart-gun-operator
    description: au14-job-description-forecon-firstrecon
    reregister: false
    job: AU14FORECONFirstReconSmartGunOperator
    raffle:
      settings: short
    rules: au14-forecon-rules

- type: startingGear
  id: AU14GearFORECONFirstReconSmartGunOperator
  equipment:
    id: AU14IDCardFORECONFirstReconSmartGunOperator
    outerClothing: AU14ArmorCBRN
    jumpsuit: AU14JumpsuitFORECONDesert
    shoes: CMBootsBrownFilled
    head: AU14DesertM10Helmet
    belt: CMBeltMarine
    pocket1: AU14PouchIFAKFill
    pocket2: AU14PouchIFAKFill
    back: CMSatchelMarine
    ears: RMCHeadsetForecon
    suitstorage: AU14WeaponRifleM41AE2Recon
  storage:
    back:
    - AU14CBRNKitUA
    - AU14DesertBoonieHat
    - RMCHelmetGarbNightVision
    belt:
    - CMMagazineRifleM54CE2
    - CMMagazineRifleM54CE2
    - CMMagazineRifleM54CE2
    - CMMagazineRifleM54CMK1
    - CMMagazineRifleM54CMK1
    head:
    - AU14HelmetGarbM10SkrimDesert
    - AU14GogglesM1A1ClearBallistic
