name: Changelog

concurrency:
  group: update-changelog
  cancel-in-progress: false

on:
  # workflow_run:
  #   workflows: ["Publish"]
  #   types: [completed]    # Publish
  schedule:
    - cron: "0 10 * * *"    # Daily
  workflow_dispatch:        # Manual
    inputs:
      start_date:
        description: "Backfill from date (ISO 8601), automatic when empty"
        required: false
      category:
        description: "Changelog category, keep default"
        required: false
        default: "CMU"

jobs:
  update:
    runs-on: ubuntu-latest
    if: >
      vars.DONT_UPDATE_CHANGELOG != 'true'
      && (github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success')
    outputs:
      changes_detected: ${{ steps.auto-commit.outputs.changes_detected }}
      commit_hash: ${{ steps.auto-commit.outputs.commit_hash }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Parse PRs into Parts
        run: Tools/update_changelog_parts.py Resources/Changelog/Parts --category ${{inputs.category || 'CMU' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          START_DATE: ${{ inputs.start_date }}

      - name: Update changelog
        run: Tools/update_changelog.py Resources/Changelog/CMU.yml
          Resources/Changelog/Parts --category ${{ inputs.category || 'CMU' }}

      - uses: stefanzweifel/git-auto-commit-action@v7.1.0
        id: auto-commit
        with:
          commit_message: "Auto-update changelog [skip ci]"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

  discord-webhook:
    name: Discord webhook
    runs-on: ubuntu-latest
    needs: update
    if: needs.update.outputs.changes_detected == 'true'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          ref: ${{ needs.update.outputs.commit_hash }}
          fetch-depth: 2

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run Discord changelog script
        run: Tools/actions_changelogs_since_last_run.py
        env:
          CHANGELOG_FILE: Resources/Changelog/CMU.yml
          CHANGELOG_PREVIOUS_REF: HEAD^
          DISCORD_WEBHOOK_URL: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK }}
