- type: job
  parent: CMJobBase
  id: AU14JobIPIEPPO
  roundSide: ThirdParty
  roundForce: WY
  roundRole: IPIEPPO
  roundComponents:
  - type: Skills
    skills:
      RMCSkillCqc: 2
      RMCSkillEndurance: 2
      RMCSkillFirearms: 2
      RMCSkillFireman: 2
      RMCSkillMeleeWeapons: 2
      RMCSkillIntel: 1
      RMCSkillOverwatch: 1
      RMCSkillPolice: 2
      RMCSkillVehicles: 1
      RMCSkillMedical: 2
  - type: JobPrefix
    prefix: au14-job-prefix-corporateliaison
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth
  - type: AssignSquad
    whitelist:
      tags:
      - SquadPMC
  - type: NpcFactionMember
    factions:
    - GOVFOR
  - type: Marine
    Faction: govfor

  name: IPIE Personal Protection Officer
  description: au14-ipie-ppo-description
  playTimeTracker: AU14JobIPIEPPO
  ranks:
    AU14RankWYSecurityOfficer: []
  spawnMenuRoleName: WY IPIE Personal Protection Officer (3rd party)
  startingGear: AU14GearIPIEPPO
  greeting: au14-ipie-greeting
  icon: "CMJobIconLiaison"
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-wy
  accessGroups:
  - Colonist
  - auadmin
  - AUPrisonStaff
  - auwy
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicWeYu
  id: AU14JobIPIEPPO
  name: WY IPIE Personal Protection Officer (3rd party)
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: SquadPMC
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: IPE Personal Protection Officer
    description: au14-ipie-ppo-description
    reregister: false
    job: AU14JobIPIEPPO
    raffle:
      settings: short
    rules: au14-ipie-ppo-description

- type: startingGear
  id: AU14GearIPIEPPO
  equipment:
    id: AU14IDCardColonyCorporateLiaison
    outerClothing: AU14WYPPOArmor
    jumpsuit: CMJumpsuitLiaisonField
    belt: RMCMK80BeltPMCFilled
    shoes: RMCShoesLaceup
    head: AU14WYPPOCap
    back: CMSatchel
    ears: AU14ColonyWeylandHeadset
    pocket1: AU14PouchPoliceEquipmentSupportSynth
    pocket2: AU14PouchIFAKFill
  storage:
    back:
    - CMStunbaton
    - RMCWeaponTaser

- type: playTimeTracker
  id: AU14JobIPIEPPO
