- type: job
  abstract: true
  parent: CMJobBase
  id: AUThreatJobBase
  description: null
  joinNotifyCrew: false
  icon: "AU14JobIconThreatMember"
  supervisors: au-job-name-threat-leader
  accessGroups:
  - CMAccessXeno
  hasIcon: false

- type: job
  parent: AUThreatJobBase
  id: AU14JobThreatLeader
  name: au-job-name-threat-leader
  description: au-job-description-threat-leader
  setPreference: true
  playTimeTracker: AUJobThreatLeader
  # requirements:
  # - !type:RoleTimeRequirement
  #    role: AUJobThreatMember
  #    time: 10800 # 3 hours
  supervisors: nobody
  icon: "AU14JobIconThreatLeader"
  jobPreviewEntity: RMCPlayerXenoQueenPreview
  accessGroups:
  - CMAccessXeno
  - CMAccessXenoQueen

- type: playTimeTracker
  id: AUJobThreatLeader

- type: job
  parent: AUThreatJobBase
  id: AU14JobThreatMember
  name: au-job-name-threat-member
  description: au-job-description-threat-member
  setPreference: true
  playTimeTracker: AUJobThreatMember
  supervisors: nobody
  icon: "AU14JobIconThreatMember"
  jobPreviewEntity: RMCPlayerXenoQueenPreview
  accessGroups:
  - CMAccessXeno
  - CMAccessXenoQueen
  hidden: false # CMJobXenoBase has hidden: true

- type: playTimeTracker
  id: AUJobThreatMember
